package com.google.android.apps.gsa.p8852u;

import com.google.protobuf.C62957cd;
import com.google.protobuf.C62959cf;
import org.chromium.net.PrivateKeyType;

/* renamed from: com.google.android.apps.gsa.u.b */
/* compiled from: PG */
public enum C118569b implements C62957cd {
    UNKNOWN_METRIC_TYPE(0),
    LATENCY_MICROS(1),
    DEPRECATED_FRAME_DURATION_MILLIS(2),
    NETWORK_BYTES_SENT(3),
    NETWORK_BYTES_RECEIVED(4),
    ON_DISK_BYTES(5),
    STORAGE_BYTES_READ(6),
    COUNT(7),
    DEPRECATED_JANK_FRAMES(8),
    DEPRECATED_JANK_DAVEY_JUNIOR_FRAMES(9),
    DEPRECATED_JANK_DAVEY_FRAMES(10),
    TASKGRAPH_SHUTDOWN_MICROS(11),
    TASKGRAPH_TASK_PRODUCER_EXECUTION_MICROS(12),
    TASKGRAPH_TASK_UI_EXECUTION_MICROS(13),
    TASKGRAPH_TASK_UI_QUEUING_MICROS(14),
    TASKGRAPH_UI_QUEUING_MICROS(15),
    TASKGRAPH_UI_THREAD_EXECUTION_MICROS(51),
    BACKGROUND_TASK_COUNT(16),
    BACKGROUND_TASK_STOP_COUNT(20),
    BACKGROUND_TASK_SCHEDULE_MILLIS(21),
    BACKGROUND_TASK_DURATION_MILLIS(22),
    MONET_RENDER_LATENCY_MILLIS(17),
    WORKER_LATENCY_MICROS(18),
    EVENT_LOGGER_RECORD_MICROS(19),
    EVENT_LOGGER_FLUSH_SECS(23),
    DOWNLOAD_MANAGER_BYTES_RECEIVED(24),
    BACKGROUND_TASK_EXTRAS_SIZE_BYTES(25),
    TELEMETRY_OVER_EVENT_LIMIT_COUNT(26),
    SEARCH_COOKIE_TOTAL_COUNT(27),
    SEARCH_COOKIE_LOGGED_OUT_WITHOUT_ACCOUNT_COUNT(28),
    SEARCH_COOKIE_LOGGED_OUT_WITH_ACCOUNT_WITHOUT_AUTH_TOKEN_COUNT(29),
    SEARCH_COOKIE_LOGGED_OUT_WITH_ACCOUNT_WITH_AUTH_TOKEN_COUNT(30),
    SEARCH_COOKIE_LOGGED_OUT_WITH_ACCOUNT_WITH_EXCEPTION_COUNT(31),
    SEARCH_NOW_ACTIVITY_BOOTSTRAPPED(32),
    SUBRESOURCES_CACHE_LATENCY(33),
    SUBRESOURCES_CACHE_SUCCESS_RATE(34),
    SUBRESOURCES_CLEANUP_LATENCY(35),
    SUBRESOURCES_CLEANUP_SUCCESS_RATE(36),
    SUBRESOURCES_FETCH_SUCCESS_RATE(37),
    SEARCH_SERVICE_LIFETIME_SECS(38),
    BROTLI_LOADING_TIME_MILLIS(39),
    SNA_BOOTSTRAPPED_FROM_FILE_COUNT(40),
    SNA_BOOTSTRAPPED_FROM_SEARCH_SERVICE_AS_FALLBACK_COUNT(41),
    SNA_BOOTSTRAPPED_FROM_SEARCH_SERVICE_ON_FIRST_ATTEMPT_COUNT(42),
    SNA_BOOTSTRAPPED_WITHOUT_USING_SEARCH_ACTIVITY_COUNT(43),
    SNA_BOOTSTRAP_TOTAL_COUNT(44),
    PUMPKIN_USER_VALIDATOR_GET_POSTERIOR_LATENCY(45),
    SUBRESOURCES_RETRIEVAL_SUCCESS_RATE(46),
    SUBRESOURCES_OFFLINE_RETRIEVAL_SUCCESS_RATE(47),
    ASSISTANT_CLIENT_SYNC_CHAT_HISTORY_LATENCY(48),
    ASSISTANT_CLIENT_SYNC_WEBANSWERS_HISTORY_LATENCY(49),
    ASSISTANT_CLIENT_SYNC_ZERO_STATE_LATENCY(50),
    ASSISTANT_CLIENT_SYNC_ZERO_STATE_ASYNC_UPDATE_LATENCY(253),
    ASSISTANT_CLIENT_SYNC_MEDIA_RECOMMENDATION_LATENCY(229),
    ASSISTANT_CLIENT_SYNC_PROACTIVE_SYNC_REQUEST_LATENCY(297),
    ASSISTANT_CLIENT_SYNC_PROACTIVE_GETCONTENT_REQUEST_LATENCY(298),
    ASSISTANT_CLIENT_SYNC_OPA_TV_RECS_LATENCY(147),
    ASSISTANT_CLIENT_SYNC_OPA_TV_SEARCH_TAB_LATENCY(330),
    ASSISTANT_CLIENT_SYNC_CONTACT_UPLOAD_LATENCY(172),
    ASSISTANT_CLIENT_SYNC_NOTIFICATIONS_LATENCY(222),
    ASSISTANT_CLIENT_SYNC_CHALKBOARD_PREFETCH_LATENCY(316),
    SQLITE_CONNECTION_LATENCY_MICROS(52),
    SQLITE_READ_LATENCY_MICROS(53),
    SQLITE_CURSOR_LATENCY_MICROS(54),
    SQLITE_WRITE_LATENCY_MICROS(55),
    ASSISTANT_CLIENT_SYNC_GROWTH_CLIENT_SYNC_LATENCY(56),
    PROACTIVE_CONTENT_STORE_CACHE_HITS(57),
    PROACTIVE_CONTENT_STORE_CACHE_MISSES(58),
    PROACTIVE_CONTENT_STORE_CACHE_SKIPS(59),
    PROACTIVE_CONTENT_STORE_HASH_LATENCY(60),
    PROACTIVE_FEED_AD_VIEW_REPORTING(230),
    PROACTIVE_FEED_ATTENTION_LOG_ABANDONED(300),
    PROACTIVE_FEED_ATTENTION_LOG_REPORTED(301),
    PROACTIVE_FEED_ATTENTION_LOG_STARTED(302),
    PROACTIVE_FEED_ATTENTION_LOG_SUCCESSFUL_LATENCY(303),
    PROACTIVE_FEED_ATTENTION_LOG_ABANDONED_LATENCY(304),
    PROACTIVE_FEED_CLICK_SRP_COUNT(142),
    PROACTIVE_FEED_ENTRY_TREE_MISMATCH_FOUND(224),
    PROACTIVE_FEED_ENTRY_TREE_MISMATCH_RESOLVED(225),
    PROACTIVE_FEED_SURFACE_TYPE_MISMATCH_FOUND(226),
    PROACTIVE_FEED_SURFACE_TYPE_MISMATCH_RESOLVED(227),
    PROACTIVE_FEED_CREATE_STREAM_SUCCESS_RATE(248),
    PROACTIVE_FEED_CREATE_STREAM_SUCCESS_FULL_REFRESH_RATE(243),
    PROACTIVE_FEED_CREATE_STREAM_ERROR_TIMEOUT(245),
    PROACTIVE_FEED_CREATE_STREAM_ERROR_EXECUTION(246),
    PROACTIVE_FEED_CREATE_STREAM_ERROR_OTHER(247),
    PROACTIVE_FEED_MULTIPLE_STREAM_CONTROLLERS_CREATED(258),
    PROACTIVE_FEED_SECOND_SCREEN_REQUEST_SUCCESS_RATE(376),
    PROACTIVE_INFINITE_FEED_CURSOR_INITIALIZATION_ERROR(235),
    PROACTIVE_SPINNER_TOTAL_SHOW(250),
    PROACTIVE_SPINNER_TOTAL_HIDE(251),
    PROACTIVE_FIRST_LOAD_CARD_COUNT(254),
    PROACTIVE_CACHE_FETCHED_ENTRY_COUNT(PrivateKeyType.INVALID),
    PROACTIVE_NETWORK_FETCHED_ENTRY_COUNT(256),
    PROACTIVE_CACHE_FETCH_STARTED_COUNT(264),
    PROACTIVE_NETWORK_FETCH_STARTED_COUNT(265),
    GELLER_DATA_LOOKUP_SUCCESS_LATENCY(61),
    MONET_RESTORE_SUCCESS_RATE(62),
    GELLER_FOOTPRINTS_GET_READ_RESPONSE_SUCCESS_LATENCY(63),
    GELLER_FOOTPRINTS_READ_SUCCESS_LATENCY(64),
    GELLER_DATA_LOOKUP_FAILURE_LATENCY(65),
    GELLER_FOOTPRINTS_GET_READ_RESPONSE_FAILURE_LATENCY(66),
    GELLER_FOOTPRINTS_READ_FAILURE_LATENCY(67),
    GELLER_GET_CONTACT_ANNOTATIONS_ONLINE_RETRIEVAL_RATE(118),
    GELLER_GET_CONTACT_ANNOTATIONS_OFFLINE_RETRIEVAL_RATE(119),
    GELLER_GET_CONTACT_RELATIONSHIP_LIKE_ONLINE_RETRIEVAL_RATE(144),
    GELLER_GET_CONTACT_RELATIONSHIP_LIKE_OFFLINE_RETRIEVAL_RATE(145),
    GELLER_GET_CONTACTS_ONLINE_RETRIEVAL_RATE(120),
    GELLER_GET_CONTACTS_OFFINE_RETRIEVAL_RATE(121),
    GELLER_GET_CONTACT_ANNOTATIONS_SUCCESS_RATE(71),
    GELLER_NETWORK_CONNECTION_ONLINE(72),
    GELLER_NETWORK_CONNECTION_OFFLINE(73),
    GELLER_SYNC_WORKER_VALID_NOTIFICATION_RATE(173),
    GELLER_SYNC_WORKER_DATA_FETCH_SUCCESS_RATE(174),
    GELLER_SYNC_WORKER_WEB_SEARCH_DELETION_NOTIFICATION_COUNT(582),
    GELLER_NGA_LOOKUP_SUCCESS_LATENCY_MILLIS_ANSWERS(186),
    GELLER_NGA_LOOKUP_FAILURE_LATENCY_MILLIS_ANSWERS(187),
    GELLER_NGA_CACHE_ACCESS_SUCCESS_RATE_ANSWERS(188),
    GELLER_NGA_CORPUS_SIZE_BYTES_ACTION_HISTORY(305),
    GELLER_NGA_CORPUS_SIZE_BYTES_ANSWERS(189),
    GELLER_NGA_CORPUS_SIZE_BYTES_APP_ACTIONS(306),
    GELLER_NGA_CORPUS_SIZE_BYTES_ASSISTANT_DISTILLED_ACTION_USER_MODEL(307),
    GELLER_NGA_CORPUS_SIZE_BYTES_ASSISTANT_SETTINGS(308),
    GELLER_NGA_CORPUS_SIZE_BYTES_DEEPLINK(309),
    GELLER_NGA_CORPUS_SIZE_BYTES_JINN_ALL_DJ(310),
    GELLER_NGA_CORPUS_SIZE_BYTES_JINN_STARLIGHT(311),
    GELLER_NGA_CORPUS_SIZE_BYTES_JINN_VOICE_PROFILE(312),
    GELLER_NGA_CORPUS_SIZE_BYTES_PKG_ENTITIES(313),
    GELLER_NGA_CORPUS_SIZE_BYTES_PRIVACY_SETTINGS(314),
    GELLER_NGA_SYNC_LATENCY_MILLIS_ACTION_HISTORY(267),
    GELLER_NGA_SYNC_LATENCY_MILLIS_ANSWERS(268),
    GELLER_NGA_SYNC_LATENCY_MILLIS_APP_ACTIONS(269),
    GELLER_NGA_SYNC_LATENCY_MILLIS_ASSISTANT_DISTILLED_ACTION_USER_MODEL(270),
    GELLER_NGA_SYNC_LATENCY_MILLIS_ASSISTANT_SETTINGS(271),
    GELLER_NGA_SYNC_LATENCY_MILLIS_DEEPLINK(272),
    GELLER_NGA_SYNC_LATENCY_MILLIS_JINN_ALL_DJ(273),
    GELLER_NGA_SYNC_LATENCY_MILLIS_JINN_STARLIGHT(274),
    GELLER_NGA_SYNC_LATENCY_MILLIS_JINN_VOICE_PROFILE(275),
    GELLER_NGA_SYNC_LATENCY_MILLIS_PKG_ENTITIES(276),
    GELLER_NGA_SYNC_LATENCY_MILLIS_PRIVACY_SETTINGS(277),
    GELLER_NGA_SYNC_SUCCESS_RATE_ACTION_HISTORY(279),
    GELLER_NGA_SYNC_SUCCESS_RATE_ANSWERS(280),
    GELLER_NGA_SYNC_SUCCESS_RATE_APP_ACTIONS(281),
    GELLER_NGA_SYNC_SUCCESS_RATE_ASSISTANT_DISTILLED_ACTION_USER_MODEL(282),
    GELLER_NGA_SYNC_SUCCESS_RATE_ASSISTANT_SETTINGS(283),
    GELLER_NGA_SYNC_SUCCESS_RATE_DEEPLINK(284),
    GELLER_NGA_SYNC_SUCCESS_RATE_JINN_ALL_DJ(285),
    GELLER_NGA_SYNC_SUCCESS_RATE_JINN_STARLIGHT(286),
    GELLER_NGA_SYNC_SUCCESS_RATE_JINN_VOICE_PROFILE(287),
    GELLER_NGA_SYNC_SUCCESS_RATE_PKG_ENTITIES(288),
    GELLER_NGA_SYNC_SUCCESS_RATE_PRIVACY_SETTINGS(289),
    HOTWORD_SPEAKER_ID_FAILED_IN_NAVIGATION_COUNT(278),
    HOTWORD_SPEAKER_ID_PASSED_IN_NAVIGATION_COUNT(299),
    HOTWORD_AUDIO_DUMP_OUTSIDE_ENROLLMENT_COUNT(327),
    HOTWORD_MODEL_MDD_ADD_PENDING(556),
    HOTWORD_MODEL_MDD_ADD_FAILED(557),
    HOTWORD_MODEL_MDD_ADD_ALREADY_DOWNLOADED(558),
    HOTWORD_MODEL_MDD_ADD_LOST(559),
    LENS_APP_SHORTCUT_REQUESTED(455),
    LENS_APP_SHORTCUT_INSTALLED(456),
    QSB_WIDGET_APP_SHORTCUT_REQUESTED(567),
    QSB_WIDGET_APP_SHORTCUT_INSTALLED(568),
    LENS_APP_SHORTCUT_MENU_CLICKED(471),
    LENS_CAMERA_BLOCKED_ON_STARTUP_COUNT(448),
    LENS_CAMERA_GRANTED_ON_STARTUP_COUNT(449),
    LENS_CAMERA_PENDING_ON_STARTUP_SHOW_FALLBACK_COUNT(450),
    LENS_CAMERA_PENDING_ON_STARTUP_SHOW_ONBOARDING_COUNT(451),
    LENS_CLOUD_COPY_ZERO_STATE_RETRY_DEVICE_LIST_COUNT(402),
    LENS_CLOUD_COPY_AUTO_REFRESH_DEVICE_LIST_COUNT(403),
    LENS_CLOUD_COPY_TOOLBELT_CHIP_DEVICE_LIST_COUNT(404),
    LENS_CLOUD_COPY_REFRESH_BUTTON_DEVICE_LIST_COUNT(434),
    LENS_INSTANT_TEXT_SELECTION_MISMATCH(68),
    LENS_INSTANT_TEXT_SELECTION_MISMATCH_WORDS(69),
    LENS_INSTANT_TEXT_SELECTION_MISMATCH_CHARACTERS(70),
    LENS_INTENT_OPENER_DISPATCH_TO_CALLBACK_SUCCESS_RATE(379),
    LENS_RESULTS_PANEL_IMAGE_LOAD_SUCCESS_RATE(457),
    LENS_SRP_CACHE_HIT(481),
    LENS_SRP_CACHE_MISS(482),
    LENS_UDC_SETTINGS_CHECK_ATTEMPT_COUNT(540),
    LENS_UDC_SETTINGS_CHECK_SUCCESS_RATE(541),
    LENS_VIEW_INIT_CORE_FEATURES_MILLIS(405),
    LENS_VIEW_INIT_DEFERRED_FEATURES_MILLIS(406),
    LENS_VIEW_INIT_FEEDBACK_FOOTER(407),
    LENS_VIEW_INIT_FILTER_SELECTOR_MILLIS(408),
    LENS_VIEW_INIT_FROZEN_IMAGE_MILLIS(409),
    LENS_VIEW_INIT_GLEAM_MILLIS(410),
    LENS_VIEW_INIT_MAIN_MILLIS(411),
    LENS_VIEW_INIT_OVERLAY_BUTTONS_MILLIS(412),
    LENS_VIEW_INIT_REGION_SEARCH_BUTTON_MILLIS(413),
    LENS_VIEW_INIT_ROOT_MILLIS(414),
    LENS_VIEW_INIT_TEXT_OVERLAY_MILLIS(415),
    LENS_VIEW_INIT_THINKING_GLEAMS_MILLIS(416),
    VOICE_MATCH_INVITE_MESSAGE(74),
    VOICE_MATCH_INVITE_MESSAGE_FROM_SETTINGS(75),
    VOICE_MATCH_DEEPLINK_WELCOME_SCREEN_COUNT(143),
    VOICE_MATCH_DEEPLINK_HEY_GOOGLE_MIGRATION_COUNT(219),
    VOICE_MATCH_KITKAT_MODEL_CLEANUP_COUNT(228),
    VOICE_MATCH_NO_THANKS_THRESHOLD_REACHED(233),
    JS_EXT_IS_TRUSTED_CALL_COUNT(76),
    JS_EXT_OPEN_IN_APP_CALL_COUNT(77),
    JS_EXT_OPEN_IN_APP_FULLSCREEN_CALL_COUNT(78),
    JS_EXT_OPEN_IN_APP_SAME_SESSION_CALL_COUNT(79),
    JS_EXT_REPLACE_SEARCH_BOX_CALL_COUNT(80),
    JS_EXT_CAN_URI_BE_HANDLED_CALL_COUNT(81),
    JS_EXT_CAN_URI_BE_HANDLED_BY_PACKAGE_CALL_COUNT(82),
    JS_EXT_OPEN_WITH_PACKAGE_CALL_COUNT(83),
    JS_EXT_OPEN_WITH_PACAGE_WITH_ACCOUNT_EXTRAS_CALL_COUNT(84),
    JS_EXT_CAN_LAUNCH_APP_CALL_COUNT(85),
    JS_EXT_LAUNCH_APP_CALL_COUNT(86),
    JS_EXT_LAUNCH_APP_VIA_INTENT_URI_CALL_COUNT(87),
    JS_EXT_REGISTER_RECEIVER_CALL_COUNT(88),
    JS_EXT_UNREGISTER_RECEIVER_CALL_COUNT(89),
    JS_EXT_DELAYED_PAGE_LOAD_CALL_COUNT(90),
    JS_EXT_PAGE_READY_CALL_COUNT(91),
    JS_EXT_PREFETCH_CALL_COUNT(92),
    JS_EXT_ADD_IN_APP_URL_PATTERN_CALL_COUNT(93),
    JS_EXT_ADD_OPTIONS_MENU_ITEM_CALL_COUNT(94),
    JS_EXT_REQUEST_UPDATE_HOST_APP_CALL_COUNT(95),
    JS_EXT_LOG_CLIENT_EVENT_CALL_COUNT(96),
    JS_EXT_GET_NETWORK_CONNECTION_TYPE_CALL_COUNT(97),
    JS_EXT_SET_NATIVE_UI_STATE_CALL_COUNT(98),
    JS_EXT_GET_SCROLL_TOP_CALL_COUNT(99),
    JS_EXT_GET_HEADER_PADDING_HEIGHT_CALL_COUNT(100),
    JS_EXT_GET_FOOTER_PADDING_HEIGHT_CALL_COUNT(101),
    JS_EXT_GET_DETAILED_NETWORK_CONNECTION_TYPE_CALL_COUNT(102),
    JS_EXT_SHARE_CALL_COUNT(103),
    JS_EXT_INSTALL_SHORTCUT_CALL_COUNT(104),
    JS_EXT_HAS_HOMESCREEN_SHORTCUT_CALL_COUNT(105),
    JS_EXT_INSTALL_HOMESCREEN_SHORTCUT_CALL_COUNT(106),
    JS_EXT_UPDATE_HOMESCREEN_SHORTCUT_CALL_COUNT(107),
    JS_EXT_REGISTER_PAGE_VISIBILITY_LISTENER_CALL_COUNT(108),
    JS_EXT_GET_PAGE_VISIBILITY_CALL_COUNT(109),
    JS_EXT_SEND_GENERIC_CLIENT_EVENT_CALL_COUNT(110),
    JS_EXT_GO_BACK_CALL_COUNT(111),
    JS_EXT_RESTORE_WEBPAGE_SCROLL_POSITION_CALL_COUNT(112),
    JS_EXT_GET_FIRST_BYTE_TIME_MILLIS_CALL_COUNT(113),
    JS_EXT_GET_CACHED_SEARCH_RESULT_ID_CALL_COUNT(114),
    JS_EXT_PREWARM_IMAGE_VIEWER_CALL_COUNT(115),
    JS_EXT_OPEN_IMAGE_VIEWER_CALL_COUNT(116),
    JS_EXT_CLOSE_PAGE_CALL_COUNT(117),
    LABS_TOTAL_FEATURES_ON_RATE(165),
    LABS_PINCH_TO_ZOOM_FEATURE_RATE(166),
    LABS_TEST_FEATURE_RATE(167),
    PUMPKIN_LOCAL_INTENT_VALIDATOR_SUCCESS_COUNT(122),
    PUMPKIN_LOCAL_INTENT_VALIDATOR_FAILURE_COUNT(123),
    PUMPKIN_ADDRESS_VALIDATOR_SUCCESS_COUNT(124),
    PUMPKIN_ADDRESS_VALIDATOR_FAILURE_COUNT(125),
    OPA_ACQUISITION_NOTIFICATION_SERVER_RPC_RESPONSE_VALID_COUNT(126),
    OPA_ACQUISITION_NOTIFICATION_SERVER_RPC_RESPONSE_SUCCESS_LATENCY(127),
    OPA_ACQUISITION_NOTIFICATION_SERVER_RPC_FAILURE_LATENCY(128),
    OPA_ACQUISITION_NOTIFICATION_VALID_PAYLOAD_COUNT(129),
    OPA_AUTO_CONVERSATION_END_TIMEOUT_COUNT(163),
    GOOGLE_HOME_APP_DOWNLOAD_LINK_CLICKED_ON_VOICE_MATCH_SUMMARY_SCREEN(130),
    PROACTIVE_CARD_CREATED_CARDS_UNIQUE_CONTENT(223),
    PROACTIVE_REQUEST_BUILD_TIME_MILLIS(131),
    PROACTIVE_REQUEST_LATENCY_MILLIS(132),
    PROACTIVE_RESPONSE_SUCCESS(133),
    RESPONSE_PROCESS_TIME_MILLIS(134),
    PROACTIVE_INFINITE_FEED_CONFIG_FLAG_FORCE_UPDATE(190),
    PROACTIVE_INFINITE_FEED_RESPONSE_SUCCESS(168),
    PROACTIVE_INFINITE_FEED_REQUEST_BUILD_TIME_MILLIS(169),
    PROACTIVE_INFINITE_FEED_REQUEST_LATENCY_MILLIS(170),
    PROACTIVE_INFINITE_FEED_RESPONSE_PROCESS_TIME_MILLIS(171),
    PROACTIVE_PAGINATED_REQUEST_BUILD_TIME_MILLIS(137),
    PROACTIVE_PAGINATED_REQUEST_LATENCY_MILLIS(138),
    PROACTIVE_PAGINATED_RESPONSE_SUCCESS(139),
    PROACTIVE_PAGINATED_RESPONSE_PROCESS_TIME_MILLIS(140),
    PROACTIVE_PAGINATED_ENTRY_TREE_MISMATCH(185),
    PROACTIVE_PAGINATED_REQUEST_FIRST_SENT_FOR_TOKEN(360),
    PROACTIVE_PAGINATED_RESPONSE_FIRST_ATTEMPT_SUCCESS_FOR_TOKEN(361),
    PROACTIVE_PAGINATED_RESPONSE_EVENTUAL_SUCCESS_FOR_TOKEN(362),
    PROACTIVE_PAGINATED_RESPONSE_FAILURES_BEFORE_EVENTUAL_SUCCESS_FOR_TOKEN(363),
    PROACTIVE_FEED_LENGTH_AT_END(182),
    PROACTIVE_FEED_INDEX_AT_END(183),
    PROACTIVE_FEED_SHORT_FEED(220),
    PROACTIVE_FEED_SERVER_INDEX_AT_END(184),
    PROACTIVE_FEED_TREE_MISMATCH_DURING_RESTORE(221),
    PROACTIVE_FEED_STORE_WRITE_SUCCESS(234),
    PROACTIVE_FEED_AGE(257),
    PROACTIVE_FEED_PRUNED_ENTRY_TREE_NODES_DURING_RESTORE(266),
    PROACTIVE_STREAM_CONTROLLER_CLASSIC_RESTORE_FAILED(249),
    PROACTIVE_FEED_CREATE_STREAM_LATENCY_MILLIS(259),
    PROACTIVE_STREAM_CONTROLLER_IN_MEMORY_RESTORE_LATENCY_MILLIS(260),
    PROACTIVE_STREAM_CONTROLLER_LOAD_FROM_DISK_RESTORE_LATENCY_MILLIS(261),
    PROACTIVE_NOW_CONTROLLER_INITIALIZE_VIA_ONCREATE(262),
    PROACTIVE_NOW_CONTROLLER_SUCCESSFULLY_RESTORED_STREAM(263),
    PROACTIVE_ENTRY_TREE_WRITER_INITIALIZATION_LATENCY_MILLIS(252),
    GOOGLE_HOME_PERSONAL_RESULTS_OPTIN(135),
    GOOGLE_HOME_PERSONAL_RESULTS_OPTOUT(136),
    EMBEDDED_ASSISTANT_NLU_NOT_LOADED_IN_TIME_COUNT(141),
    EMBEDDED_ASSISTANT_NLU_LOADING_MILLIS(146),
    OFFLINE_LOCAL_BIASING_EMPTY_RECOGNITIONCONTEXT_APPLIED_COUNT(157),
    OFFLINE_LOCAL_BIASING_FENCE_FAILED_CREATION_COUNT(161),
    OFFLINE_LOCAL_BIASING_FENCE_FAILED_DESTRUCTION_COUNT(162),
    OFFLINE_LOCAL_BIASING_FENCE_SUCCESSFUL_CREATION_COUNT(148),
    OFFLINE_LOCAL_BIASING_FENCE_SUCCESSFUL_DESTRUCTION_COUNT(149),
    OFFLINE_LOCAL_BIASING_LOCATION_ACQUIRED_FAILURE_COUNT(152),
    OFFLINE_LOCAL_BIASING_LOCATION_ACQUIRED_SUCCESS_COUNT(151),
    OFFLINE_LOCAL_BIASING_LOCATION_POLLED_COUNT(150),
    OFFLINE_LOCAL_BIASING_MINIMUM_RADIUS_FENCE_CREATED(160),
    OFFLINE_LOCAL_BIASING_MODEL_DATA_ABSENT_COUNT(154),
    OFFLINE_LOCAL_BIASING_MODEL_DATA_PRESENT_COUNT(153),
    OFFLINE_LOCAL_BIASING_MODEL_READ_FAILED_COUNT(156),
    OFFLINE_LOCAL_BIASING_MODEL_READ_SUCCESS_COUNT(155),
    OFFLINE_LOCAL_BIASING_NONEMPTY_RECOGNITIONCONTEXT_APPLIED_COUNT(158),
    OFFLINE_LOCAL_BIASING_ONEOFF_TASK_SCHEDULED_COUNT(159),
    BLUETOOTH_SCO_CONNECTION_LATENCY(164),
    QWARK_ACTIVITY_FOREGROUND_INITIAL_RECONNECTION_LATENCY_MILLIS(175),
    QWARK_ACTIVITY_FOREGROUND_FOLLOWUP_RECONNECTION_LATENCY_MILLIS(176),
    QWARK_ACTIVITY_NON_FOREGROUND_RECONNECTION_LATENCY_MILLIS(177),
    QWARK_ACTIVITY_RESTART_WHITOUT_CONNECTION_TIME_MILLIS(178),
    QWARK_ACTIVITY_FOREGROUND_CONNECTION_DROP_ELAPSED_TIME_MILLIS(179),
    CCT_WAIT_FOR_SESSION_SUCCESS_RATE(180),
    CCT_SERVICE_CONNECTION_LATENCY_MILLIS(181),
    BACKGROUND_RETRY_ONBOARDING_ACCEPTED(191),
    BACKGROUND_RETRY_ONBOARDING_DECLINED(192),
    BACKGROUND_RETRY_ONBOARDING_DISMISSED(193),
    BACKGROUND_RETRY_IMPLICIT_OPTIN(194),
    BACKGROUND_RETRY_EXPLICIT_OPTIN(195),
    BACKGROUND_RETRY_CANCELED(196),
    BACKGROUND_RETRY_STARTED(197),
    BACKGROUND_RETRY_RESCHEDULED(198),
    BACKGROUND_RETRY_PENDING_QUERY_EXPIRED(199),
    BACKGROUND_RETRY_MAX_ATTEMPTS_EXCEEDED(200),
    BACKGROUND_RETRY_SEARCH_GRAPH_SUCCESS_RATE(201),
    BACKGROUND_RETRY_BLACKLISTED_ERROR(202),
    BACKGROUND_RETRY_NOTIFICATION_TAPPED(203),
    BACKGROUND_RETRY_NOTIFICATION_DELETED(204),
    BACKGROUND_RETRY_PENDING_QUERY_DELETED_FROM_RECENTLY(205),
    BACKGROUND_RETRY_COMPLETED_QUERY_DELETED_FROM_RECENTLY(206),
    BACKGROUND_RETRY_COMPLETED_QUERY_EXPIRED(207),
    BACKGROUND_RETRY_RESULTS_OPENED_FROM_RECENTLY(208),
    BACKGROUND_RETRY_CACHE_HIT_RATE(209),
    BACKGROUND_RETRY_SETTING_TOGGLED_ON(210),
    BACKGROUND_RETRY_SETTING_TOGGLED_OFF(211),
    BACKGROUND_RETRY_NOTIFICATIONS_DISABLED_DIALOG_SHOWN(212),
    BACKGROUND_RETRY_DATA_SAVER_ENABLED_DIALOG_SHOWN(213),
    BACKGROUND_RETRY_PENDING_QUEUE_SIZE(214),
    BACKGROUND_RETRY_COMPLETED_QUEUE_SIZE(215),
    SILK_GSAS_CLICKED_IMMERSIVE_COUNT(216),
    SILK_GSAS_CLICKED_MEDIA_COUNT(217),
    SILK_GSAS_CLICKED_NO_CORPUS_COUNT(218),
    ASSISTANT_SETTINGS_PROVIDER_INDEXED_COUNT(231),
    ASSISTANT_SETTINGS_OPENED_FROM_SEARCH_COUNT(232),
    EUA_SEQUENCE_ID_RESET(236),
    EUA_SEQUENCE_ID_PERSIST_FAILURE(237),
    EUA_SEQUENCE_ID_PERSIST_SUCCESS(238),
    EUA_PERSIST_COUNT(239),
    EUA_DEFERRED_PERSIST_COUNT(240),
    EUA_UPLOAD_COUNT(241),
    EUA_RETAINED_COUNT(242),
    NGA_INITIAL_DOWNLOAD_AUTOMATICALLY_STARTED_COUNT(290),
    NGA_INITIAL_DOWNLOAD_AUTOMATICALLY_SUCCEEDED_COUNT(291),
    NGA_INITIAL_DOWNLOAD_MANUALLY_STARTED_COUNT(292),
    NGA_INITIAL_DOWNLOAD_MANUALLY_SUCCEEDED_COUNT(293),
    NGA_BACKGROUND_DOWNLOAD_SUCCEEDED_COUNT(294),
    NGA_INITIAL_DOWNLOAD_AUTOMATIC_CANCELED_COUNT(295),
    NGA_INITIAL_DOWNLOAD_MANUAL_CANCELED_COUNT(296),
    NGA_INITIAL_DOWNLOAD_UI_CREATED(315),
    NGA_INITIAL_DOWNLOAD_FAILURE_NO_NETWORK(321),
    NGA_INITIAL_DOWNLOAD_FAILURE_MDD(322),
    NGA_INITIAL_DOWNLOAD_FAILURE_AUTOMATIC_FLAG_DISABLED(323),
    NGA_INITIAL_DOWNLOAD_FAILURE_AUTOMATIC_MOBILE_DATA_LIMIT(324),
    NGA_INITIAL_DOWNLOAD_FAILURE_AUTOMATIC_OTHER_NETWORK(325),
    NGA_INITIAL_DOWNLOAD_FAILURE_OTHER(326),
    NGA_DATA_SYNC_DOWNLOADED_GROUP_NO_CONFIG(531),
    VOICE_MATCH_ENROLLMENT_STATE_UNDECIDED_TO_ENROLLED_COUNT(317),
    VOICE_MATCH_ENROLLMENT_STATE_UNDECIDED_TO_DECLINED_COUNT(318),
    VOICE_MATCH_ENROLLMENT_STATE_DECLINED_TO_ENROLLED_COUNT(319),
    VOICE_MATCH_ENROLLMENT_STATE_ENROLLED_TO_DECLINED_COUNT(320),
    CACHE_REFRESH_COUNT(328),
    CACHE_DUPLICATE_REFRESH_COUNT(329),
    CACHE_SUGGESTIONS_SEEN_REFRESH_COUNT(331),
    ASSISTANT_CLIENT_SYNC_TAPAS_SERVER_LATENCY(364),
    TAPAS_APP_SOURCE_LATENCY_MILLIS(332),
    TAPAS_APP_ACTIONS_SHORTCUT_SOURCE_LATENCY_MILLIS(513),
    TAPAS_APP_ACTION_SOURCE_LATENCY_MILLIS(344),
    TAPAS_COMMS_SOURCE_LATENCY_MILLIS(333),
    TAPAS_COMPLETE_SERVER_SOURCE_LATENCY_MILLIS(334),
    TAPAS_GEO_SOURCE_LATENCY_MILLIS(335),
    TAPAS_ICING_SOURCE_LATENCY_MILLIS(336),
    TAPAS_MEDIA_SOURCE_LATENCY_MILLIS(337),
    TAPAS_MESSAGE_SOURCE_LATENCY_MILLIS(338),
    TAPAS_MIX_RESPONSE_LATENCY_MILLIS(339),
    TAPAS_MIX_RESPONSE_0_PREFIX_LATENCY_MILLIS(478),
    TAPAS_MIX_RESPONSE_N_PREFIX_LATENCY_MILLIS(479),
    TAPAS_NOTIFICATION_SOURCE_LATENCY_MILLIS(340),
    TAPAS_SHORTCUT_SOURCE_LATENCY_MILLIS(341),
    TAPAS_SUGGESTION_FETCH_LATENCY_MILLIS(342),
    TAPAS_SUGGESTION_FETCH_SUCCESS_COUNT(533),
    TAPAS_SUGGESTION_FETCH_0_PREFIX_LATENCY_MILLIS(474),
    TAPAS_SUGGESTION_FETCH_0_PREFIX_SUCCESS_COUNT(534),
    TAPAS_SUGGESTION_FETCH_N_PREFIX_LATENCY_MILLIS(475),
    TAPAS_SUGGESTION_FETCH_N_PREFIX_SUCCESS_COUNT(535),
    TAPAS_SUGGESTION_RENDER_LATENCY_MILLIS(343),
    TAPAS_SUGGESTION_RENDER_0_PREFIX_LATENCY_MILLIS(476),
    TAPAS_SUGGESTION_RENDER_N_PREFIX_LATENCY_MILLIS(477),
    TAPAS_SERVER_SOURCE_SUCCESS_COUNT(244),
    TAPAS_SERVER_SOURCE_TIMEOUT_COUNT(458),
    TAPAS_SERVER_SOURCE_FAILURE_COUNT(459),
    TAPAS_SERVER_SOURCE_ZERO_PREFIX_SUCCESS_COUNT(462),
    TAPAS_SERVER_SOURCE_N_PREFIX_SUCCESS_COUNT(463),
    TAPAS_SERVER_SOURCE_ZERO_PREFIX_LATENCY_MILLIS(464),
    TAPAS_SERVER_SOURCE_N_PREFIX_LATENCY_MILLIS(465),
    TAPAS_SERVER_SOURCE_SUCCESS_N_PREFIX_LATENCY_MILLIS(472),
    TAPAS_SERVER_SOURCE_TIMEOUT_N_PREFIX_LATENCY_MILLIS(473),
    TAPAS_BLUE_CHIP_SERVICE_FETCH_LATENCY_MILLIS(501),
    TAPAS_GEMINI_GRPC_SETUP_LATENCY_MILLIS(561),
    TAPAS_GEMINI_GRPC_TRANSIT_LATENCY_MILLIS(562),
    ASSISTANT_REQUEST_BUILD_TIME(345),
    ASSISTANT_REQUEST_DEVICE_CAPABILITIES_BUILD_TIME(348),
    ASSISTANT_REQUEST_BUILD_TIME_MS(350),
    ASSISTANT_REQUEST_SIZE_BYTES(346),
    ASSISTANT_REQUEST_DEVICE_CAPABILITIES_BUILD_TIME_MS(351),
    ASSISTANT_REQUEST_DEVICE_CAPABILITIES_SIZE_BYTES(347),
    OFFLINE_INTERPRETER_TRANSLATE_SUCCESS_RATE(349),
    OFFLINE_INTERPRETER_OFFLINE_USAGE_RATE(544),
    OFFLINE_INTERPRETER_DOWNLOAD_SUCCESS_RATE(545),
    OFFLINE_INTERPRETER_DELETE_SUCCESS_RATE(546),
    PODCAST_SERVICE_LATENCY_MILLIS(352),
    PODCAST_SERVICE_STATUS_OK_COUNT(353),
    PODCAST_SERVICE_STATUS_ERROR_PERMISSION_DENIED_COUNT(354),
    PODCAST_SERVICE_STATUS_ERROR_INVALID_ARGUMENT_COUNT(355),
    PODCAST_SERVICE_STATUS_ERROR_UNAUTHENTICATED_COUNT(356),
    PODCAST_SERVICE_STATUS_ERROR_OTHER_COUNT(357),
    ALL_DEEPLINK(358),
    SEARCH_DEEPLINK(359),
    SPEAKER_ID_ADAPTATION_TASK_ACCOUNT_ERROR_COUNT(365),
    SPEAKER_ID_ADAPTATION_TASK_VOICE_MATCH_ERROR_COUNT(366),
    SPEAKER_ID_ADAPTATION_TASK_NO_UTTERANCES_ERROR_COUNT(367),
    SPEAKER_ID_ADAPTATION_TASK_ENROLLMENT_UTTERANCES_ERROR_COUNT(368),
    SPEAKER_ID_ADAPTATION_TASK_ADAPTATION_UTTERANCES_ERROR_COUNT(369),
    SPEAKER_ID_ADAPTATION_TASK_ENROLLMENT_SERVICE_ERROR_COUNT(370),
    SPEAKER_ID_ADAPTATION_TASK_RE_ENROLL_ERROR_COUNT(371),
    SPEAKER_ID_ADAPTATION_TASK_SUCCESS_COUNT(372),
    SPEAKER_ID_ADAPTATION_PROCESSING_NO_UTTERANCES_ERROR_COUNT(373),
    SPEAKER_ID_ADAPTATION_PROCESSING_MULTIPLE_UTTERANCES_ERROR_COUNT(374),
    SPEAKER_ID_ADAPTATION_TASK_NO_RECENT_UTTERANCES_COUNT(375),
    SPEAKER_ID_ADAPTATION_PROCESSING_ADAPT_FALSE_WITH_NO_UTTERANCE(435),
    SPEAKER_ID_ADAPTATION_PROCESSING_ADAPT_FALSE(436),
    SPEAKER_ID_ADAPTATION_PROCESSING_FILE_ERROR_COUNT(437),
    SPEAKER_ID_ADAPTATION_PROCESSING_COMPLETE(438),
    SPEAKER_ID_ADAPTATION_PROCESSING_DELETE_OLD_UTTERANCE(439),
    MORRIS_CLIENT_APP_CRASH_COUNT(377),
    MORRIS_ASSISTANT_PROCESS_CRASH_COUNT(378),
    OPA_ALTT_TASK_DISABLED_COUNT(380),
    OPA_ALTT_TASK_DONE_COUNT(381),
    OPA_ALTT_SPEAKER_ID_MODEL_TRANSITION_DISABLED_COUNT(382),
    OPA_ALTT_SPEAKER_ID_MODEL_TRANSITION_USER_PROFILE_LANG_ENABLED_COUNT(383),
    OPA_ALTT_SPEAKER_ID_MODEL_TRANSITION_OLD_ID_NOT_FOUND_COUNT(384),
    OPA_ALTT_SPEAKER_ID_MODEL_TRANSITION_FINISHED_COUNT(385),
    PODCAST_DOWNLOAD_LEGACY_DIRECTORY_FILE_COUNT(386),
    PODCAST_DOWNLOAD_DIRECTORY_FILE_COUNT(387),
    ACETONE_SHARED_OVERLAY_OEM_PARTNER_ICON_WIDTH(388),
    ACETONE_SHARED_OVERLAY_OEM_PARTNER_ICON_HEIGHT(389),
    ACETONE_SHARED_OVERLAY_OEM_PARTNER_ICON_INVALID_COUNT(390),
    ACETONE_OVERLAY_ORIENTATION_MISMATCH(452),
    ACETONE_OVERLAY_ORIENTATION_MISMATCH_RESOLVED(453),
    ACETONE_OVERLAY_ORIENTATION_MISMATCH_RESOLVED_DELAY(454),
    ACETONE_GET_VOICE_SEARCH_LANGUAGE_SERVICE_INVOCATION_COUNT(466),
    ACETONE_IS_VOICE_DETECTION_RUNNING_SERVICE_INVOCATION_COUNT(467),
    ACETONE_REQUEST_VOICE_DETECTION_INVOCATION_COUNT(468),
    ACETONE_HAS_OVERLAY_CONTENT_INVOCATION_COUNT(469),
    ACETONE_START_SEARCH_INVOCATION_COUNT(470),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_REFRESH_LATENCY_MILLIS(391),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_SOFT_TIMEOUT_COUNT(392),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_HARD_TIMEOUT_COUNT(393),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_INVALID_COUNT(394),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_READ_FAIL_COUNT(395),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_REFRESH_DEVICE_CP2_QUERY_ERROR_COUNT(396),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_REFRESH_MISSING_ACCOUNT_ERROR_COUNT(397),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_MISSING_COUNT(398),
    LOGS_BASED_TOP_CONTACT_LOOKUP_INELIGIBLE_CONTACT_COUNT(399),
    LOGS_BASED_TOP_CONTACT_LOOKUP_GELLER_UPLOAD_UNAVAILABLE_COUNT(400),
    LOGS_BASED_TOP_CONTACT_LOOKUP_CONTACTS_NO_AFFINITY_SCORE_COUNT(401),
    APP_OPS_ACTIVITY_RECOGNITION_COUNT(421),
    APP_OPS_BLUETOOTH_COUNT(569),
    APP_OPS_CALENDAR_COUNT(417),
    APP_OPS_CALL_LOG_COUNT(433),
    APP_OPS_CALL_PHONE_COUNT(430),
    APP_OPS_CAMERA_COUNT(429),
    APP_OPS_CONTACTS_COUNT(418),
    APP_OPS_EXTERNAL_STORAGE_COUNT(431),
    APP_OPS_GET_ACCOUNT_COUNT(432),
    APP_OPS_LOCATION_COUNT(419),
    APP_OPS_MEDIA_AUDIO_COUNT(581),
    APP_OPS_MEDIA_IMAGES_COUNT(579),
    APP_OPS_MEDIA_VIDEO_COUNT(580),
    APP_OPS_MICROPHONE_COUNT(420),
    APP_OPS_OTHER_COUNT(422),
    APP_OPS_READ_PHONE_STATE(443),
    APP_OPS_SMS_COUNT(428),
    SMARTSPACE_TRIGGER_LOCATION_UPDATE_LATENCY_MILLIS(423),
    SMARTSPACE_TRIGGER_LOCATION_UPDATE_COUNT(424),
    SMARTSPACE_TRIGGER_LOCATION_UPDATE_DISCARD_COUNT(460),
    SMARTSPACE_TRIGGER_LOCATION_UPDATE_MAX_AGE_DISCARD_COUNT(461),
    SMARTSPACE_TRIGGER_LOCATION_UPDATE_SPEED_LIMIT_DISCARD_COUNT(500),
    SMARTSPACE_TRIGGER_LOCATION_UPDATE_TIMEOUT_COUNT(440),
    SMARTSPACE_TRIGGER_SCREEN_ON_COUNT(445),
    SMARTSPACE_TRIGGER_TIME_TICK_COUNT(446),
    SMARTSPACE_TRIGGER_LAUNCHER_VISIBILITY_COUNT(447),
    SMARTSPACE_HEURISTIC_CLEAR_CHIP_COUNT(441),
    SMARTSPACE_HEURISTIC_THROTTLING_COUNT(442),
    SMARTSPACE_HEURISTIC_WIFI_COUNT(444),
    SMARTSPACE_LOCATION_INFERENCE_LATENCY_MILLIS(425),
    SMARTSPACE_LOCATION_INFERENCE_LAST_COUNT(426),
    SMARTSPACE_LOCATION_INFERENCE_FRESH_COUNT(427),
    SMARTSPACE_PLACE_FEEDBACK(480),
    SMARTSPACE_SEARCH_PROCESS_DOWN_COUNT(502),
    SMARTSPACE_SEARCH_PROCESS_STARTED_COUNT(483),
    SMARTSPACE_HAMMERSPACE_INDEX_DOWNLOAD_COUNT(487),
    SMARTSPACE_HAMMERSPACE_SLICES_DOWNLOAD_COUNT(488),
    SMARTSPACE_FEATURE_ASSISTANT_SHOPPING_LIST_COUNT(524),
    SMARTSPACE_FEATURE_GPAY_LOYALTY_CARD_COUNT(525),
    SMARTSPACE_FEATURE_KEEP_SHOPPING_LIST_COUNT(526),
    SMARTSPACE_FEATURE_KEEP_SLICEPROVIDER_COUNT(497),
    SMARTSPACE_ALARM_SUGGESTIONS_LATENCY_MILLIS(499),
    SMARTSPACE_HABITS_PROFILES_PRESENT(503),
    SMARTSPACE_HABITS_PROFILES_FAILURE(514),
    SMARTSPACE_HABITS_ACTIVITIES_PROFILE_PRESENT(504),
    SMARTSPACE_HABITS_HOME_AUTOMATION_PROFILE_PRESENT(505),
    SMARTSPACE_HABITS_MEDIA_PROFILE_PRESENT(506),
    SMARTSPACE_HABITS_MEDIA_PROFILE_AGE_SECONDS(528),
    SMARTSPACE_HABITS_AWAKE_PROFILE_PRESENT(507),
    SMARTSPACE_HABITS_SHOPPING_PROFILE_PRESENT(508),
    SMARTSPACE_HABITS_LOCATION_CAFE_PROFILE_PRESENT(517),
    SMARTSPACE_HABITS_LOCATION_GAS_STATION_PROFILE_PRESENT(518),
    SMARTSPACE_HABITS_LOCATION_PARKING_PROFILE_PRESENT(519),
    SMARTSPACE_HABITS_LOCATION_RESTAURANT_PROFILE_PRESENT(520),
    SMARTSPACE_HABITS_LOCATION_SHOPPING_CENTER_PROFILE_PRESENT(521),
    SMARTSPACE_HABITS_LOCATION_STORE_PROFILE_PRESENT(522),
    SMARTSPACE_HABITS_LOCATION_TRANSIT_STATION_PROFILE_PRESENT(523),
    SMARTSPACE_HABITS_ON_FIRST_ACCESS_PRESENT(509),
    SMARTSPACE_HABITS_ON_FIRST_ACCESS_FAILURE(515),
    SMARTSPACE_HABITS_TIME_SPENT_RATIO_THRESHOLD_EXCEEDED_RATE(530),
    SMARTSPACE_HYBRID_HOTSEAT_SUGGESTION_COUNT(547),
    SMARTSPACE_HYBRID_HOTSEAT_SUGGESTION_CONTEXT_COUNT(548),
    SMARTSPACE_WIDGET_SIZE_DIP(510),
    SMARTSPACE_HABITS_PERSONALIZATION_ENABLED_STATUS(511),
    SMARTSPACE_HABITS_CAST_DEVICE_FOUND(512),
    SMARTSPACE_TRIGGER_HEADPHONE_COUNT(516),
    SMARTSPACE_CHIME_REGISTRATION_TRIGGER(536),
    SMARTSPACE_CHIME_REGISTRATION_FAILURE(537),
    SMARTSPACE_CHIME_REGISTRATION_SUCCESS(538),
    SMARTSPACE_CHIME_REGISTRATION_WORKER_ENQUEUE_FAILURE(539),
    SMARTSPACE_WEATHER_PERIODIC_POLLING_TASK_TRIGGER(542),
    SMARTSPACE_WEATHER_PERIODIC_POLLING_REQUEST_START_EVENT(543),
    SMARTSPACE_WEATHER_UPDATE_REQUEST(549),
    SMARTSPACE_WEATHER_UPDATE_ACTION(550),
    SMARTSPACE_WEATHER_UPDATE_STORAGE(551),
    SMARTSPACE_WEATHER_SEND_SURFACE(552),
    PCP_SMARTSPACE_WEATHER_UPDATE(553),
    PCP_SMARTSPACE_WEATHER_NOTIFICATION(554),
    SMARTSPACE_CALENDAR_UPDATE_REQUEST(563),
    SMARTSPACE_CALENDAR_UPDATE_STORAGE(564),
    SMARTSPACE_CALENDAR_SEND_SURFACE(565),
    PCP_SMARTSPACE_CALENDAR_NOTIFICATION(566),
    SMARTSPACE_CALENDAR_UPDATE_THIRD_PARTY(570),
    SMARTSPACE_CALENDAR_UPDATE_WORK_PROFILE(571),
    VOICE_MATCH_INCOMPLETE_ENROLLED_ON_FIRST_ATTEMPT_COUNT(484),
    VOICE_MATCH_INCOMPLETE_ENROLLED_ON_SECOND_ATTEMPT_COUNT(485),
    VOICE_MATCH_INCOMPLETE_ENROLLED_ON_THIRD_OR_LATER_ATTEMPT_COUNT(486),
    PACKAGE_SUSPENDED_EVENT_COUNT(489),
    PACKAGE_UNSUSPENDED_IN_ACETONE_EVENT_COUNT(490),
    ACETONE_ACCESS_IN_SUSPENDED_MODE_COUNT(491),
    MEDIA_GLANCEABILITY_PREVIOUS(492),
    MEDIA_GLANCEABILITY_PAUSE(493),
    MEDIA_GLANCEABILITY_PLAY(494),
    MEDIA_GLANCEABILITY_NEXT(495),
    MEDIA_GLANCEABILITY_SESSION_DESTROYED(496),
    MEDIA_GLANCEABILITY_CARD_IMPRESSION(527),
    MEDIA_GLANCEABILITY_TIME_OUT(529),
    VOICE_MATCH_SETTING_ERROR_FROM_DECLINED_STATE(498),
    SEARCH_PROCESS_LIFETIME(532),
    GMM_STATE_PARAMS_PROTO_FILLER_GRPC_FETCH_COUNT(572),
    CLIENT_EVENT_EMITTED_COUNT(573),
    SEARCH_CLIENT_EVENT_EMITTED_RATE(574),
    AAP_HOTWORD_DETECTED_COUNT(575),
    AAP_HOTWORD_ONGOING_SESSION_DETECTED_COUNT(577),
    AAP_HOTWORD_ONGOING_SESSION_DETECTED_TNG_COUNT(578),
    WEBVIEWS_CREATED(576),
    ACTIVITY_ONCREATE_COUNT(583),
    PROVIDER_QUERY_COUNT(584),
    PROVIDER_INSERT_COUNT(585),
    PROVIDER_UPDATE_COUNT(586),
    PROVIDER_DELETE_COUNT(587),
    PROVIDER_OPEN_FILE_COUNT(588),
    PROVIDER_GET_TYPE_COUNT(589),
    MANIFEST_RECEIVER_ON_RECEIVE_COUNT(590),
    SERVICE_ONCREATE_COUNT(591);
    

    /* renamed from: ks */
    public final int f329776ks;

    private C118569b(int i) {
        this.f329776ks = i;
    }

    /* renamed from: a */
    public static C118569b m196859a(int i) {
        switch (i) {
            case 0:
                return UNKNOWN_METRIC_TYPE;
            case 1:
                return LATENCY_MICROS;
            case 2:
                return DEPRECATED_FRAME_DURATION_MILLIS;
            case 3:
                return NETWORK_BYTES_SENT;
            case 4:
                return NETWORK_BYTES_RECEIVED;
            case 5:
                return ON_DISK_BYTES;
            case 6:
                return STORAGE_BYTES_READ;
            case 7:
                return COUNT;
            case 8:
                return DEPRECATED_JANK_FRAMES;
            case 9:
                return DEPRECATED_JANK_DAVEY_JUNIOR_FRAMES;
            case 10:
                return DEPRECATED_JANK_DAVEY_FRAMES;
            case 11:
                return TASKGRAPH_SHUTDOWN_MICROS;
            case 12:
                return TASKGRAPH_TASK_PRODUCER_EXECUTION_MICROS;
            case 13:
                return TASKGRAPH_TASK_UI_EXECUTION_MICROS;
            case 14:
                return TASKGRAPH_TASK_UI_QUEUING_MICROS;
            case 15:
                return TASKGRAPH_UI_QUEUING_MICROS;
            case 16:
                return BACKGROUND_TASK_COUNT;
            case 17:
                return MONET_RENDER_LATENCY_MILLIS;
            case 18:
                return WORKER_LATENCY_MICROS;
            case 19:
                return EVENT_LOGGER_RECORD_MICROS;
            case 20:
                return BACKGROUND_TASK_STOP_COUNT;
            case 21:
                return BACKGROUND_TASK_SCHEDULE_MILLIS;
            case 22:
                return BACKGROUND_TASK_DURATION_MILLIS;
            case 23:
                return EVENT_LOGGER_FLUSH_SECS;
            case 24:
                return DOWNLOAD_MANAGER_BYTES_RECEIVED;
            case 25:
                return BACKGROUND_TASK_EXTRAS_SIZE_BYTES;
            case 26:
                return TELEMETRY_OVER_EVENT_LIMIT_COUNT;
            case 27:
                return SEARCH_COOKIE_TOTAL_COUNT;
            case 28:
                return SEARCH_COOKIE_LOGGED_OUT_WITHOUT_ACCOUNT_COUNT;
            case 29:
                return SEARCH_COOKIE_LOGGED_OUT_WITH_ACCOUNT_WITHOUT_AUTH_TOKEN_COUNT;
            case 30:
                return SEARCH_COOKIE_LOGGED_OUT_WITH_ACCOUNT_WITH_AUTH_TOKEN_COUNT;
            case 31:
                return SEARCH_COOKIE_LOGGED_OUT_WITH_ACCOUNT_WITH_EXCEPTION_COUNT;
            case 32:
                return SEARCH_NOW_ACTIVITY_BOOTSTRAPPED;
            case 33:
                return SUBRESOURCES_CACHE_LATENCY;
            case 34:
                return SUBRESOURCES_CACHE_SUCCESS_RATE;
            case 35:
                return SUBRESOURCES_CLEANUP_LATENCY;
            case 36:
                return SUBRESOURCES_CLEANUP_SUCCESS_RATE;
            case 37:
                return SUBRESOURCES_FETCH_SUCCESS_RATE;
            case 38:
                return SEARCH_SERVICE_LIFETIME_SECS;
            case 39:
                return BROTLI_LOADING_TIME_MILLIS;
            case 40:
                return SNA_BOOTSTRAPPED_FROM_FILE_COUNT;
            case 41:
                return SNA_BOOTSTRAPPED_FROM_SEARCH_SERVICE_AS_FALLBACK_COUNT;
            case 42:
                return SNA_BOOTSTRAPPED_FROM_SEARCH_SERVICE_ON_FIRST_ATTEMPT_COUNT;
            case 43:
                return SNA_BOOTSTRAPPED_WITHOUT_USING_SEARCH_ACTIVITY_COUNT;
            case 44:
                return SNA_BOOTSTRAP_TOTAL_COUNT;
            case 45:
                return PUMPKIN_USER_VALIDATOR_GET_POSTERIOR_LATENCY;
            case 46:
                return SUBRESOURCES_RETRIEVAL_SUCCESS_RATE;
            case 47:
                return SUBRESOURCES_OFFLINE_RETRIEVAL_SUCCESS_RATE;
            case 48:
                return ASSISTANT_CLIENT_SYNC_CHAT_HISTORY_LATENCY;
            case 49:
                return ASSISTANT_CLIENT_SYNC_WEBANSWERS_HISTORY_LATENCY;
            case 50:
                return ASSISTANT_CLIENT_SYNC_ZERO_STATE_LATENCY;
            case 51:
                return TASKGRAPH_UI_THREAD_EXECUTION_MICROS;
            case 52:
                return SQLITE_CONNECTION_LATENCY_MICROS;
            case 53:
                return SQLITE_READ_LATENCY_MICROS;
            case 54:
                return SQLITE_CURSOR_LATENCY_MICROS;
            case 55:
                return SQLITE_WRITE_LATENCY_MICROS;
            case 56:
                return ASSISTANT_CLIENT_SYNC_GROWTH_CLIENT_SYNC_LATENCY;
            case 57:
                return PROACTIVE_CONTENT_STORE_CACHE_HITS;
            case 58:
                return PROACTIVE_CONTENT_STORE_CACHE_MISSES;
            case 59:
                return PROACTIVE_CONTENT_STORE_CACHE_SKIPS;
            case 60:
                return PROACTIVE_CONTENT_STORE_HASH_LATENCY;
            case 61:
                return GELLER_DATA_LOOKUP_SUCCESS_LATENCY;
            case 62:
                return MONET_RESTORE_SUCCESS_RATE;
            case 63:
                return GELLER_FOOTPRINTS_GET_READ_RESPONSE_SUCCESS_LATENCY;
            case 64:
                return GELLER_FOOTPRINTS_READ_SUCCESS_LATENCY;
            case 65:
                return GELLER_DATA_LOOKUP_FAILURE_LATENCY;
            case 66:
                return GELLER_FOOTPRINTS_GET_READ_RESPONSE_FAILURE_LATENCY;
            case 67:
                return GELLER_FOOTPRINTS_READ_FAILURE_LATENCY;
            case 68:
                return LENS_INSTANT_TEXT_SELECTION_MISMATCH;
            case 69:
                return LENS_INSTANT_TEXT_SELECTION_MISMATCH_WORDS;
            case 70:
                return LENS_INSTANT_TEXT_SELECTION_MISMATCH_CHARACTERS;
            case 71:
                return GELLER_GET_CONTACT_ANNOTATIONS_SUCCESS_RATE;
            case 72:
                return GELLER_NETWORK_CONNECTION_ONLINE;
            case 73:
                return GELLER_NETWORK_CONNECTION_OFFLINE;
            case 74:
                return VOICE_MATCH_INVITE_MESSAGE;
            case 75:
                return VOICE_MATCH_INVITE_MESSAGE_FROM_SETTINGS;
            case 76:
                return JS_EXT_IS_TRUSTED_CALL_COUNT;
            case 77:
                return JS_EXT_OPEN_IN_APP_CALL_COUNT;
            case 78:
                return JS_EXT_OPEN_IN_APP_FULLSCREEN_CALL_COUNT;
            case 79:
                return JS_EXT_OPEN_IN_APP_SAME_SESSION_CALL_COUNT;
            case 80:
                return JS_EXT_REPLACE_SEARCH_BOX_CALL_COUNT;
            case 81:
                return JS_EXT_CAN_URI_BE_HANDLED_CALL_COUNT;
            case 82:
                return JS_EXT_CAN_URI_BE_HANDLED_BY_PACKAGE_CALL_COUNT;
            case 83:
                return JS_EXT_OPEN_WITH_PACKAGE_CALL_COUNT;
            case 84:
                return JS_EXT_OPEN_WITH_PACAGE_WITH_ACCOUNT_EXTRAS_CALL_COUNT;
            case 85:
                return JS_EXT_CAN_LAUNCH_APP_CALL_COUNT;
            case 86:
                return JS_EXT_LAUNCH_APP_CALL_COUNT;
            case 87:
                return JS_EXT_LAUNCH_APP_VIA_INTENT_URI_CALL_COUNT;
            case 88:
                return JS_EXT_REGISTER_RECEIVER_CALL_COUNT;
            case 89:
                return JS_EXT_UNREGISTER_RECEIVER_CALL_COUNT;
            case 90:
                return JS_EXT_DELAYED_PAGE_LOAD_CALL_COUNT;
            case 91:
                return JS_EXT_PAGE_READY_CALL_COUNT;
            case 92:
                return JS_EXT_PREFETCH_CALL_COUNT;
            case 93:
                return JS_EXT_ADD_IN_APP_URL_PATTERN_CALL_COUNT;
            case 94:
                return JS_EXT_ADD_OPTIONS_MENU_ITEM_CALL_COUNT;
            case 95:
                return JS_EXT_REQUEST_UPDATE_HOST_APP_CALL_COUNT;
            case 96:
                return JS_EXT_LOG_CLIENT_EVENT_CALL_COUNT;
            case 97:
                return JS_EXT_GET_NETWORK_CONNECTION_TYPE_CALL_COUNT;
            case 98:
                return JS_EXT_SET_NATIVE_UI_STATE_CALL_COUNT;
            case 99:
                return JS_EXT_GET_SCROLL_TOP_CALL_COUNT;
            case 100:
                return JS_EXT_GET_HEADER_PADDING_HEIGHT_CALL_COUNT;
            case 101:
                return JS_EXT_GET_FOOTER_PADDING_HEIGHT_CALL_COUNT;
            case 102:
                return JS_EXT_GET_DETAILED_NETWORK_CONNECTION_TYPE_CALL_COUNT;
            case 103:
                return JS_EXT_SHARE_CALL_COUNT;
            case 104:
                return JS_EXT_INSTALL_SHORTCUT_CALL_COUNT;
            case 105:
                return JS_EXT_HAS_HOMESCREEN_SHORTCUT_CALL_COUNT;
            case 106:
                return JS_EXT_INSTALL_HOMESCREEN_SHORTCUT_CALL_COUNT;
            case 107:
                return JS_EXT_UPDATE_HOMESCREEN_SHORTCUT_CALL_COUNT;
            case 108:
                return JS_EXT_REGISTER_PAGE_VISIBILITY_LISTENER_CALL_COUNT;
            case 109:
                return JS_EXT_GET_PAGE_VISIBILITY_CALL_COUNT;
            case 110:
                return JS_EXT_SEND_GENERIC_CLIENT_EVENT_CALL_COUNT;
            case 111:
                return JS_EXT_GO_BACK_CALL_COUNT;
            case 112:
                return JS_EXT_RESTORE_WEBPAGE_SCROLL_POSITION_CALL_COUNT;
            case 113:
                return JS_EXT_GET_FIRST_BYTE_TIME_MILLIS_CALL_COUNT;
            case 114:
                return JS_EXT_GET_CACHED_SEARCH_RESULT_ID_CALL_COUNT;
            case 115:
                return JS_EXT_PREWARM_IMAGE_VIEWER_CALL_COUNT;
            case 116:
                return JS_EXT_OPEN_IMAGE_VIEWER_CALL_COUNT;
            case 117:
                return JS_EXT_CLOSE_PAGE_CALL_COUNT;
            case 118:
                return GELLER_GET_CONTACT_ANNOTATIONS_ONLINE_RETRIEVAL_RATE;
            case 119:
                return GELLER_GET_CONTACT_ANNOTATIONS_OFFLINE_RETRIEVAL_RATE;
            case 120:
                return GELLER_GET_CONTACTS_ONLINE_RETRIEVAL_RATE;
            case 121:
                return GELLER_GET_CONTACTS_OFFINE_RETRIEVAL_RATE;
            case 122:
                return PUMPKIN_LOCAL_INTENT_VALIDATOR_SUCCESS_COUNT;
            case 123:
                return PUMPKIN_LOCAL_INTENT_VALIDATOR_FAILURE_COUNT;
            case 124:
                return PUMPKIN_ADDRESS_VALIDATOR_SUCCESS_COUNT;
            case 125:
                return PUMPKIN_ADDRESS_VALIDATOR_FAILURE_COUNT;
            case 126:
                return OPA_ACQUISITION_NOTIFICATION_SERVER_RPC_RESPONSE_VALID_COUNT;
            case 127:
                return OPA_ACQUISITION_NOTIFICATION_SERVER_RPC_RESPONSE_SUCCESS_LATENCY;
            case 128:
                return OPA_ACQUISITION_NOTIFICATION_SERVER_RPC_FAILURE_LATENCY;
            case 129:
                return OPA_ACQUISITION_NOTIFICATION_VALID_PAYLOAD_COUNT;
            case 130:
                return GOOGLE_HOME_APP_DOWNLOAD_LINK_CLICKED_ON_VOICE_MATCH_SUMMARY_SCREEN;
            case 131:
                return PROACTIVE_REQUEST_BUILD_TIME_MILLIS;
            case 132:
                return PROACTIVE_REQUEST_LATENCY_MILLIS;
            case 133:
                return PROACTIVE_RESPONSE_SUCCESS;
            case 134:
                return RESPONSE_PROCESS_TIME_MILLIS;
            case 135:
                return GOOGLE_HOME_PERSONAL_RESULTS_OPTIN;
            case 136:
                return GOOGLE_HOME_PERSONAL_RESULTS_OPTOUT;
            case 137:
                return PROACTIVE_PAGINATED_REQUEST_BUILD_TIME_MILLIS;
            case 138:
                return PROACTIVE_PAGINATED_REQUEST_LATENCY_MILLIS;
            case 139:
                return PROACTIVE_PAGINATED_RESPONSE_SUCCESS;
            case 140:
                return PROACTIVE_PAGINATED_RESPONSE_PROCESS_TIME_MILLIS;
            case 141:
                return EMBEDDED_ASSISTANT_NLU_NOT_LOADED_IN_TIME_COUNT;
            case 142:
                return PROACTIVE_FEED_CLICK_SRP_COUNT;
            case 143:
                return VOICE_MATCH_DEEPLINK_WELCOME_SCREEN_COUNT;
            case 144:
                return GELLER_GET_CONTACT_RELATIONSHIP_LIKE_ONLINE_RETRIEVAL_RATE;
            case 145:
                return GELLER_GET_CONTACT_RELATIONSHIP_LIKE_OFFLINE_RETRIEVAL_RATE;
            case 146:
                return EMBEDDED_ASSISTANT_NLU_LOADING_MILLIS;
            case 147:
                return ASSISTANT_CLIENT_SYNC_OPA_TV_RECS_LATENCY;
            case 148:
                return OFFLINE_LOCAL_BIASING_FENCE_SUCCESSFUL_CREATION_COUNT;
            case 149:
                return OFFLINE_LOCAL_BIASING_FENCE_SUCCESSFUL_DESTRUCTION_COUNT;
            case 150:
                return OFFLINE_LOCAL_BIASING_LOCATION_POLLED_COUNT;
            case 151:
                return OFFLINE_LOCAL_BIASING_LOCATION_ACQUIRED_SUCCESS_COUNT;
            case 152:
                return OFFLINE_LOCAL_BIASING_LOCATION_ACQUIRED_FAILURE_COUNT;
            case 153:
                return OFFLINE_LOCAL_BIASING_MODEL_DATA_PRESENT_COUNT;
            case 154:
                return OFFLINE_LOCAL_BIASING_MODEL_DATA_ABSENT_COUNT;
            case 155:
                return OFFLINE_LOCAL_BIASING_MODEL_READ_SUCCESS_COUNT;
            case 156:
                return OFFLINE_LOCAL_BIASING_MODEL_READ_FAILED_COUNT;
            case 157:
                return OFFLINE_LOCAL_BIASING_EMPTY_RECOGNITIONCONTEXT_APPLIED_COUNT;
            case 158:
                return OFFLINE_LOCAL_BIASING_NONEMPTY_RECOGNITIONCONTEXT_APPLIED_COUNT;
            case 159:
                return OFFLINE_LOCAL_BIASING_ONEOFF_TASK_SCHEDULED_COUNT;
            case 160:
                return OFFLINE_LOCAL_BIASING_MINIMUM_RADIUS_FENCE_CREATED;
            case 161:
                return OFFLINE_LOCAL_BIASING_FENCE_FAILED_CREATION_COUNT;
            case 162:
                return OFFLINE_LOCAL_BIASING_FENCE_FAILED_DESTRUCTION_COUNT;
            case 163:
                return OPA_AUTO_CONVERSATION_END_TIMEOUT_COUNT;
            case 164:
                return BLUETOOTH_SCO_CONNECTION_LATENCY;
            case 165:
                return LABS_TOTAL_FEATURES_ON_RATE;
            case 166:
                return LABS_PINCH_TO_ZOOM_FEATURE_RATE;
            case 167:
                return LABS_TEST_FEATURE_RATE;
            case 168:
                return PROACTIVE_INFINITE_FEED_RESPONSE_SUCCESS;
            case 169:
                return PROACTIVE_INFINITE_FEED_REQUEST_BUILD_TIME_MILLIS;
            case 170:
                return PROACTIVE_INFINITE_FEED_REQUEST_LATENCY_MILLIS;
            case 171:
                return PROACTIVE_INFINITE_FEED_RESPONSE_PROCESS_TIME_MILLIS;
            case 172:
                return ASSISTANT_CLIENT_SYNC_CONTACT_UPLOAD_LATENCY;
            case 173:
                return GELLER_SYNC_WORKER_VALID_NOTIFICATION_RATE;
            case 174:
                return GELLER_SYNC_WORKER_DATA_FETCH_SUCCESS_RATE;
            case 175:
                return QWARK_ACTIVITY_FOREGROUND_INITIAL_RECONNECTION_LATENCY_MILLIS;
            case 176:
                return QWARK_ACTIVITY_FOREGROUND_FOLLOWUP_RECONNECTION_LATENCY_MILLIS;
            case 177:
                return QWARK_ACTIVITY_NON_FOREGROUND_RECONNECTION_LATENCY_MILLIS;
            case 178:
                return QWARK_ACTIVITY_RESTART_WHITOUT_CONNECTION_TIME_MILLIS;
            case 179:
                return QWARK_ACTIVITY_FOREGROUND_CONNECTION_DROP_ELAPSED_TIME_MILLIS;
            case 180:
                return CCT_WAIT_FOR_SESSION_SUCCESS_RATE;
            case 181:
                return CCT_SERVICE_CONNECTION_LATENCY_MILLIS;
            case 182:
                return PROACTIVE_FEED_LENGTH_AT_END;
            case 183:
                return PROACTIVE_FEED_INDEX_AT_END;
            case 184:
                return PROACTIVE_FEED_SERVER_INDEX_AT_END;
            case 185:
                return PROACTIVE_PAGINATED_ENTRY_TREE_MISMATCH;
            case 186:
                return GELLER_NGA_LOOKUP_SUCCESS_LATENCY_MILLIS_ANSWERS;
            case 187:
                return GELLER_NGA_LOOKUP_FAILURE_LATENCY_MILLIS_ANSWERS;
            case 188:
                return GELLER_NGA_CACHE_ACCESS_SUCCESS_RATE_ANSWERS;
            case 189:
                return GELLER_NGA_CORPUS_SIZE_BYTES_ANSWERS;
            case 190:
                return PROACTIVE_INFINITE_FEED_CONFIG_FLAG_FORCE_UPDATE;
            case 191:
                return BACKGROUND_RETRY_ONBOARDING_ACCEPTED;
            case 192:
                return BACKGROUND_RETRY_ONBOARDING_DECLINED;
            case 193:
                return BACKGROUND_RETRY_ONBOARDING_DISMISSED;
            case 194:
                return BACKGROUND_RETRY_IMPLICIT_OPTIN;
            case 195:
                return BACKGROUND_RETRY_EXPLICIT_OPTIN;
            case 196:
                return BACKGROUND_RETRY_CANCELED;
            case 197:
                return BACKGROUND_RETRY_STARTED;
            case 198:
                return BACKGROUND_RETRY_RESCHEDULED;
            case 199:
                return BACKGROUND_RETRY_PENDING_QUERY_EXPIRED;
            case 200:
                return BACKGROUND_RETRY_MAX_ATTEMPTS_EXCEEDED;
            case 201:
                return BACKGROUND_RETRY_SEARCH_GRAPH_SUCCESS_RATE;
            case 202:
                return BACKGROUND_RETRY_BLACKLISTED_ERROR;
            case 203:
                return BACKGROUND_RETRY_NOTIFICATION_TAPPED;
            case 204:
                return BACKGROUND_RETRY_NOTIFICATION_DELETED;
            case 205:
                return BACKGROUND_RETRY_PENDING_QUERY_DELETED_FROM_RECENTLY;
            case 206:
                return BACKGROUND_RETRY_COMPLETED_QUERY_DELETED_FROM_RECENTLY;
            case 207:
                return BACKGROUND_RETRY_COMPLETED_QUERY_EXPIRED;
            case 208:
                return BACKGROUND_RETRY_RESULTS_OPENED_FROM_RECENTLY;
            case 209:
                return BACKGROUND_RETRY_CACHE_HIT_RATE;
            case 210:
                return BACKGROUND_RETRY_SETTING_TOGGLED_ON;
            case 211:
                return BACKGROUND_RETRY_SETTING_TOGGLED_OFF;
            case 212:
                return BACKGROUND_RETRY_NOTIFICATIONS_DISABLED_DIALOG_SHOWN;
            case 213:
                return BACKGROUND_RETRY_DATA_SAVER_ENABLED_DIALOG_SHOWN;
            case 214:
                return BACKGROUND_RETRY_PENDING_QUEUE_SIZE;
            case 215:
                return BACKGROUND_RETRY_COMPLETED_QUEUE_SIZE;
            case 216:
                return SILK_GSAS_CLICKED_IMMERSIVE_COUNT;
            case 217:
                return SILK_GSAS_CLICKED_MEDIA_COUNT;
            case 218:
                return SILK_GSAS_CLICKED_NO_CORPUS_COUNT;
            case 219:
                return VOICE_MATCH_DEEPLINK_HEY_GOOGLE_MIGRATION_COUNT;
            case 220:
                return PROACTIVE_FEED_SHORT_FEED;
            case 221:
                return PROACTIVE_FEED_TREE_MISMATCH_DURING_RESTORE;
            case 222:
                return ASSISTANT_CLIENT_SYNC_NOTIFICATIONS_LATENCY;
            case 223:
                return PROACTIVE_CARD_CREATED_CARDS_UNIQUE_CONTENT;
            case 224:
                return PROACTIVE_FEED_ENTRY_TREE_MISMATCH_FOUND;
            case 225:
                return PROACTIVE_FEED_ENTRY_TREE_MISMATCH_RESOLVED;
            case 226:
                return PROACTIVE_FEED_SURFACE_TYPE_MISMATCH_FOUND;
            case 227:
                return PROACTIVE_FEED_SURFACE_TYPE_MISMATCH_RESOLVED;
            case 228:
                return VOICE_MATCH_KITKAT_MODEL_CLEANUP_COUNT;
            case 229:
                return ASSISTANT_CLIENT_SYNC_MEDIA_RECOMMENDATION_LATENCY;
            case 230:
                return PROACTIVE_FEED_AD_VIEW_REPORTING;
            case 231:
                return ASSISTANT_SETTINGS_PROVIDER_INDEXED_COUNT;
            case 232:
                return ASSISTANT_SETTINGS_OPENED_FROM_SEARCH_COUNT;
            case 233:
                return VOICE_MATCH_NO_THANKS_THRESHOLD_REACHED;
            case 234:
                return PROACTIVE_FEED_STORE_WRITE_SUCCESS;
            case 235:
                return PROACTIVE_INFINITE_FEED_CURSOR_INITIALIZATION_ERROR;
            case 236:
                return EUA_SEQUENCE_ID_RESET;
            case 237:
                return EUA_SEQUENCE_ID_PERSIST_FAILURE;
            case 238:
                return EUA_SEQUENCE_ID_PERSIST_SUCCESS;
            case 239:
                return EUA_PERSIST_COUNT;
            case 240:
                return EUA_DEFERRED_PERSIST_COUNT;
            case 241:
                return EUA_UPLOAD_COUNT;
            case 242:
                return EUA_RETAINED_COUNT;
            case 243:
                return PROACTIVE_FEED_CREATE_STREAM_SUCCESS_FULL_REFRESH_RATE;
            case 244:
                return TAPAS_SERVER_SOURCE_SUCCESS_COUNT;
            case 245:
                return PROACTIVE_FEED_CREATE_STREAM_ERROR_TIMEOUT;
            case 246:
                return PROACTIVE_FEED_CREATE_STREAM_ERROR_EXECUTION;
            case 247:
                return PROACTIVE_FEED_CREATE_STREAM_ERROR_OTHER;
            case 248:
                return PROACTIVE_FEED_CREATE_STREAM_SUCCESS_RATE;
            case 249:
                return PROACTIVE_STREAM_CONTROLLER_CLASSIC_RESTORE_FAILED;
            case 250:
                return PROACTIVE_SPINNER_TOTAL_SHOW;
            case 251:
                return PROACTIVE_SPINNER_TOTAL_HIDE;
            case 252:
                return PROACTIVE_ENTRY_TREE_WRITER_INITIALIZATION_LATENCY_MILLIS;
            case 253:
                return ASSISTANT_CLIENT_SYNC_ZERO_STATE_ASYNC_UPDATE_LATENCY;
            case 254:
                return PROACTIVE_FIRST_LOAD_CARD_COUNT;
            case PrivateKeyType.INVALID:
                return PROACTIVE_CACHE_FETCHED_ENTRY_COUNT;
            case 256:
                return PROACTIVE_NETWORK_FETCHED_ENTRY_COUNT;
            case 257:
                return PROACTIVE_FEED_AGE;
            case 258:
                return PROACTIVE_FEED_MULTIPLE_STREAM_CONTROLLERS_CREATED;
            case 259:
                return PROACTIVE_FEED_CREATE_STREAM_LATENCY_MILLIS;
            case 260:
                return PROACTIVE_STREAM_CONTROLLER_IN_MEMORY_RESTORE_LATENCY_MILLIS;
            case 261:
                return PROACTIVE_STREAM_CONTROLLER_LOAD_FROM_DISK_RESTORE_LATENCY_MILLIS;
            case 262:
                return PROACTIVE_NOW_CONTROLLER_INITIALIZE_VIA_ONCREATE;
            case 263:
                return PROACTIVE_NOW_CONTROLLER_SUCCESSFULLY_RESTORED_STREAM;
            case 264:
                return PROACTIVE_CACHE_FETCH_STARTED_COUNT;
            case 265:
                return PROACTIVE_NETWORK_FETCH_STARTED_COUNT;
            case 266:
                return PROACTIVE_FEED_PRUNED_ENTRY_TREE_NODES_DURING_RESTORE;
            case 267:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_ACTION_HISTORY;
            case 268:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_ANSWERS;
            case 269:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_APP_ACTIONS;
            case 270:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_ASSISTANT_DISTILLED_ACTION_USER_MODEL;
            case 271:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_ASSISTANT_SETTINGS;
            case 272:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_DEEPLINK;
            case 273:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_JINN_ALL_DJ;
            case 274:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_JINN_STARLIGHT;
            case 275:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_JINN_VOICE_PROFILE;
            case 276:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_PKG_ENTITIES;
            case 277:
                return GELLER_NGA_SYNC_LATENCY_MILLIS_PRIVACY_SETTINGS;
            case 278:
                return HOTWORD_SPEAKER_ID_FAILED_IN_NAVIGATION_COUNT;
            case 279:
                return GELLER_NGA_SYNC_SUCCESS_RATE_ACTION_HISTORY;
            case 280:
                return GELLER_NGA_SYNC_SUCCESS_RATE_ANSWERS;
            case 281:
                return GELLER_NGA_SYNC_SUCCESS_RATE_APP_ACTIONS;
            case 282:
                return GELLER_NGA_SYNC_SUCCESS_RATE_ASSISTANT_DISTILLED_ACTION_USER_MODEL;
            case 283:
                return GELLER_NGA_SYNC_SUCCESS_RATE_ASSISTANT_SETTINGS;
            case 284:
                return GELLER_NGA_SYNC_SUCCESS_RATE_DEEPLINK;
            case 285:
                return GELLER_NGA_SYNC_SUCCESS_RATE_JINN_ALL_DJ;
            case 286:
                return GELLER_NGA_SYNC_SUCCESS_RATE_JINN_STARLIGHT;
            case 287:
                return GELLER_NGA_SYNC_SUCCESS_RATE_JINN_VOICE_PROFILE;
            case 288:
                return GELLER_NGA_SYNC_SUCCESS_RATE_PKG_ENTITIES;
            case 289:
                return GELLER_NGA_SYNC_SUCCESS_RATE_PRIVACY_SETTINGS;
            case 290:
                return NGA_INITIAL_DOWNLOAD_AUTOMATICALLY_STARTED_COUNT;
            case 291:
                return NGA_INITIAL_DOWNLOAD_AUTOMATICALLY_SUCCEEDED_COUNT;
            case 292:
                return NGA_INITIAL_DOWNLOAD_MANUALLY_STARTED_COUNT;
            case 293:
                return NGA_INITIAL_DOWNLOAD_MANUALLY_SUCCEEDED_COUNT;
            case 294:
                return NGA_BACKGROUND_DOWNLOAD_SUCCEEDED_COUNT;
            case 295:
                return NGA_INITIAL_DOWNLOAD_AUTOMATIC_CANCELED_COUNT;
            case 296:
                return NGA_INITIAL_DOWNLOAD_MANUAL_CANCELED_COUNT;
            case 297:
                return ASSISTANT_CLIENT_SYNC_PROACTIVE_SYNC_REQUEST_LATENCY;
            case 298:
                return ASSISTANT_CLIENT_SYNC_PROACTIVE_GETCONTENT_REQUEST_LATENCY;
            case 299:
                return HOTWORD_SPEAKER_ID_PASSED_IN_NAVIGATION_COUNT;
            case 300:
                return PROACTIVE_FEED_ATTENTION_LOG_ABANDONED;
            case 301:
                return PROACTIVE_FEED_ATTENTION_LOG_REPORTED;
            case 302:
                return PROACTIVE_FEED_ATTENTION_LOG_STARTED;
            case 303:
                return PROACTIVE_FEED_ATTENTION_LOG_SUCCESSFUL_LATENCY;
            case 304:
                return PROACTIVE_FEED_ATTENTION_LOG_ABANDONED_LATENCY;
            case 305:
                return GELLER_NGA_CORPUS_SIZE_BYTES_ACTION_HISTORY;
            case 306:
                return GELLER_NGA_CORPUS_SIZE_BYTES_APP_ACTIONS;
            case 307:
                return GELLER_NGA_CORPUS_SIZE_BYTES_ASSISTANT_DISTILLED_ACTION_USER_MODEL;
            case 308:
                return GELLER_NGA_CORPUS_SIZE_BYTES_ASSISTANT_SETTINGS;
            case 309:
                return GELLER_NGA_CORPUS_SIZE_BYTES_DEEPLINK;
            case 310:
                return GELLER_NGA_CORPUS_SIZE_BYTES_JINN_ALL_DJ;
            case 311:
                return GELLER_NGA_CORPUS_SIZE_BYTES_JINN_STARLIGHT;
            case 312:
                return GELLER_NGA_CORPUS_SIZE_BYTES_JINN_VOICE_PROFILE;
            case 313:
                return GELLER_NGA_CORPUS_SIZE_BYTES_PKG_ENTITIES;
            case 314:
                return GELLER_NGA_CORPUS_SIZE_BYTES_PRIVACY_SETTINGS;
            case 315:
                return NGA_INITIAL_DOWNLOAD_UI_CREATED;
            case 316:
                return ASSISTANT_CLIENT_SYNC_CHALKBOARD_PREFETCH_LATENCY;
            case 317:
                return VOICE_MATCH_ENROLLMENT_STATE_UNDECIDED_TO_ENROLLED_COUNT;
            case 318:
                return VOICE_MATCH_ENROLLMENT_STATE_UNDECIDED_TO_DECLINED_COUNT;
            case 319:
                return VOICE_MATCH_ENROLLMENT_STATE_DECLINED_TO_ENROLLED_COUNT;
            case 320:
                return VOICE_MATCH_ENROLLMENT_STATE_ENROLLED_TO_DECLINED_COUNT;
            case 321:
                return NGA_INITIAL_DOWNLOAD_FAILURE_NO_NETWORK;
            case 322:
                return NGA_INITIAL_DOWNLOAD_FAILURE_MDD;
            case 323:
                return NGA_INITIAL_DOWNLOAD_FAILURE_AUTOMATIC_FLAG_DISABLED;
            case 324:
                return NGA_INITIAL_DOWNLOAD_FAILURE_AUTOMATIC_MOBILE_DATA_LIMIT;
            case 325:
                return NGA_INITIAL_DOWNLOAD_FAILURE_AUTOMATIC_OTHER_NETWORK;
            case 326:
                return NGA_INITIAL_DOWNLOAD_FAILURE_OTHER;
            case 327:
                return HOTWORD_AUDIO_DUMP_OUTSIDE_ENROLLMENT_COUNT;
            case 328:
                return CACHE_REFRESH_COUNT;
            case 329:
                return CACHE_DUPLICATE_REFRESH_COUNT;
            case 330:
                return ASSISTANT_CLIENT_SYNC_OPA_TV_SEARCH_TAB_LATENCY;
            case 331:
                return CACHE_SUGGESTIONS_SEEN_REFRESH_COUNT;
            case 332:
                return TAPAS_APP_SOURCE_LATENCY_MILLIS;
            case 333:
                return TAPAS_COMMS_SOURCE_LATENCY_MILLIS;
            case 334:
                return TAPAS_COMPLETE_SERVER_SOURCE_LATENCY_MILLIS;
            case 335:
                return TAPAS_GEO_SOURCE_LATENCY_MILLIS;
            case 336:
                return TAPAS_ICING_SOURCE_LATENCY_MILLIS;
            case 337:
                return TAPAS_MEDIA_SOURCE_LATENCY_MILLIS;
            case 338:
                return TAPAS_MESSAGE_SOURCE_LATENCY_MILLIS;
            case 339:
                return TAPAS_MIX_RESPONSE_LATENCY_MILLIS;
            case 340:
                return TAPAS_NOTIFICATION_SOURCE_LATENCY_MILLIS;
            case 341:
                return TAPAS_SHORTCUT_SOURCE_LATENCY_MILLIS;
            case 342:
                return TAPAS_SUGGESTION_FETCH_LATENCY_MILLIS;
            case 343:
                return TAPAS_SUGGESTION_RENDER_LATENCY_MILLIS;
            case 344:
                return TAPAS_APP_ACTION_SOURCE_LATENCY_MILLIS;
            case 345:
                return ASSISTANT_REQUEST_BUILD_TIME;
            case 346:
                return ASSISTANT_REQUEST_SIZE_BYTES;
            case 347:
                return ASSISTANT_REQUEST_DEVICE_CAPABILITIES_SIZE_BYTES;
            case 348:
                return ASSISTANT_REQUEST_DEVICE_CAPABILITIES_BUILD_TIME;
            case 349:
                return OFFLINE_INTERPRETER_TRANSLATE_SUCCESS_RATE;
            case 350:
                return ASSISTANT_REQUEST_BUILD_TIME_MS;
            case 351:
                return ASSISTANT_REQUEST_DEVICE_CAPABILITIES_BUILD_TIME_MS;
            case 352:
                return PODCAST_SERVICE_LATENCY_MILLIS;
            case 353:
                return PODCAST_SERVICE_STATUS_OK_COUNT;
            case 354:
                return PODCAST_SERVICE_STATUS_ERROR_PERMISSION_DENIED_COUNT;
            case 355:
                return PODCAST_SERVICE_STATUS_ERROR_INVALID_ARGUMENT_COUNT;
            case 356:
                return PODCAST_SERVICE_STATUS_ERROR_UNAUTHENTICATED_COUNT;
            case 357:
                return PODCAST_SERVICE_STATUS_ERROR_OTHER_COUNT;
            case 358:
                return ALL_DEEPLINK;
            case 359:
                return SEARCH_DEEPLINK;
            case 360:
                return PROACTIVE_PAGINATED_REQUEST_FIRST_SENT_FOR_TOKEN;
            case 361:
                return PROACTIVE_PAGINATED_RESPONSE_FIRST_ATTEMPT_SUCCESS_FOR_TOKEN;
            case 362:
                return PROACTIVE_PAGINATED_RESPONSE_EVENTUAL_SUCCESS_FOR_TOKEN;
            case 363:
                return PROACTIVE_PAGINATED_RESPONSE_FAILURES_BEFORE_EVENTUAL_SUCCESS_FOR_TOKEN;
            case 364:
                return ASSISTANT_CLIENT_SYNC_TAPAS_SERVER_LATENCY;
            case 365:
                return SPEAKER_ID_ADAPTATION_TASK_ACCOUNT_ERROR_COUNT;
            case 366:
                return SPEAKER_ID_ADAPTATION_TASK_VOICE_MATCH_ERROR_COUNT;
            case 367:
                return SPEAKER_ID_ADAPTATION_TASK_NO_UTTERANCES_ERROR_COUNT;
            case 368:
                return SPEAKER_ID_ADAPTATION_TASK_ENROLLMENT_UTTERANCES_ERROR_COUNT;
            case 369:
                return SPEAKER_ID_ADAPTATION_TASK_ADAPTATION_UTTERANCES_ERROR_COUNT;
            case 370:
                return SPEAKER_ID_ADAPTATION_TASK_ENROLLMENT_SERVICE_ERROR_COUNT;
            case 371:
                return SPEAKER_ID_ADAPTATION_TASK_RE_ENROLL_ERROR_COUNT;
            case 372:
                return SPEAKER_ID_ADAPTATION_TASK_SUCCESS_COUNT;
            case 373:
                return SPEAKER_ID_ADAPTATION_PROCESSING_NO_UTTERANCES_ERROR_COUNT;
            case 374:
                return SPEAKER_ID_ADAPTATION_PROCESSING_MULTIPLE_UTTERANCES_ERROR_COUNT;
            case 375:
                return SPEAKER_ID_ADAPTATION_TASK_NO_RECENT_UTTERANCES_COUNT;
            case 376:
                return PROACTIVE_FEED_SECOND_SCREEN_REQUEST_SUCCESS_RATE;
            case 377:
                return MORRIS_CLIENT_APP_CRASH_COUNT;
            case 378:
                return MORRIS_ASSISTANT_PROCESS_CRASH_COUNT;
            case 379:
                return LENS_INTENT_OPENER_DISPATCH_TO_CALLBACK_SUCCESS_RATE;
            case 380:
                return OPA_ALTT_TASK_DISABLED_COUNT;
            case 381:
                return OPA_ALTT_TASK_DONE_COUNT;
            case 382:
                return OPA_ALTT_SPEAKER_ID_MODEL_TRANSITION_DISABLED_COUNT;
            case 383:
                return OPA_ALTT_SPEAKER_ID_MODEL_TRANSITION_USER_PROFILE_LANG_ENABLED_COUNT;
            case 384:
                return OPA_ALTT_SPEAKER_ID_MODEL_TRANSITION_OLD_ID_NOT_FOUND_COUNT;
            case 385:
                return OPA_ALTT_SPEAKER_ID_MODEL_TRANSITION_FINISHED_COUNT;
            case 386:
                return PODCAST_DOWNLOAD_LEGACY_DIRECTORY_FILE_COUNT;
            case 387:
                return PODCAST_DOWNLOAD_DIRECTORY_FILE_COUNT;
            case 388:
                return ACETONE_SHARED_OVERLAY_OEM_PARTNER_ICON_WIDTH;
            case 389:
                return ACETONE_SHARED_OVERLAY_OEM_PARTNER_ICON_HEIGHT;
            case 390:
                return ACETONE_SHARED_OVERLAY_OEM_PARTNER_ICON_INVALID_COUNT;
            case 391:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_REFRESH_LATENCY_MILLIS;
            case 392:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_SOFT_TIMEOUT_COUNT;
            case 393:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_HARD_TIMEOUT_COUNT;
            case 394:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_INVALID_COUNT;
            case 395:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_READ_FAIL_COUNT;
            case 396:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_REFRESH_DEVICE_CP2_QUERY_ERROR_COUNT;
            case 397:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_REFRESH_MISSING_ACCOUNT_ERROR_COUNT;
            case 398:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CACHE_MISSING_COUNT;
            case 399:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_INELIGIBLE_CONTACT_COUNT;
            case 400:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_GELLER_UPLOAD_UNAVAILABLE_COUNT;
            case 401:
                return LOGS_BASED_TOP_CONTACT_LOOKUP_CONTACTS_NO_AFFINITY_SCORE_COUNT;
            case 402:
                return LENS_CLOUD_COPY_ZERO_STATE_RETRY_DEVICE_LIST_COUNT;
            case 403:
                return LENS_CLOUD_COPY_AUTO_REFRESH_DEVICE_LIST_COUNT;
            case 404:
                return LENS_CLOUD_COPY_TOOLBELT_CHIP_DEVICE_LIST_COUNT;
            case 405:
                return LENS_VIEW_INIT_CORE_FEATURES_MILLIS;
            case 406:
                return LENS_VIEW_INIT_DEFERRED_FEATURES_MILLIS;
            case 407:
                return LENS_VIEW_INIT_FEEDBACK_FOOTER;
            case 408:
                return LENS_VIEW_INIT_FILTER_SELECTOR_MILLIS;
            case 409:
                return LENS_VIEW_INIT_FROZEN_IMAGE_MILLIS;
            case 410:
                return LENS_VIEW_INIT_GLEAM_MILLIS;
            case 411:
                return LENS_VIEW_INIT_MAIN_MILLIS;
            case 412:
                return LENS_VIEW_INIT_OVERLAY_BUTTONS_MILLIS;
            case 413:
                return LENS_VIEW_INIT_REGION_SEARCH_BUTTON_MILLIS;
            case 414:
                return LENS_VIEW_INIT_ROOT_MILLIS;
            case 415:
                return LENS_VIEW_INIT_TEXT_OVERLAY_MILLIS;
            case 416:
                return LENS_VIEW_INIT_THINKING_GLEAMS_MILLIS;
            case 417:
                return APP_OPS_CALENDAR_COUNT;
            case 418:
                return APP_OPS_CONTACTS_COUNT;
            case 419:
                return APP_OPS_LOCATION_COUNT;
            case 420:
                return APP_OPS_MICROPHONE_COUNT;
            case 421:
                return APP_OPS_ACTIVITY_RECOGNITION_COUNT;
            case 422:
                return APP_OPS_OTHER_COUNT;
            case 423:
                return SMARTSPACE_TRIGGER_LOCATION_UPDATE_LATENCY_MILLIS;
            case 424:
                return SMARTSPACE_TRIGGER_LOCATION_UPDATE_COUNT;
            case 425:
                return SMARTSPACE_LOCATION_INFERENCE_LATENCY_MILLIS;
            case 426:
                return SMARTSPACE_LOCATION_INFERENCE_LAST_COUNT;
            case 427:
                return SMARTSPACE_LOCATION_INFERENCE_FRESH_COUNT;
            case 428:
                return APP_OPS_SMS_COUNT;
            case 429:
                return APP_OPS_CAMERA_COUNT;
            case 430:
                return APP_OPS_CALL_PHONE_COUNT;
            case 431:
                return APP_OPS_EXTERNAL_STORAGE_COUNT;
            case 432:
                return APP_OPS_GET_ACCOUNT_COUNT;
            case 433:
                return APP_OPS_CALL_LOG_COUNT;
            case 434:
                return LENS_CLOUD_COPY_REFRESH_BUTTON_DEVICE_LIST_COUNT;
            case 435:
                return SPEAKER_ID_ADAPTATION_PROCESSING_ADAPT_FALSE_WITH_NO_UTTERANCE;
            case 436:
                return SPEAKER_ID_ADAPTATION_PROCESSING_ADAPT_FALSE;
            case 437:
                return SPEAKER_ID_ADAPTATION_PROCESSING_FILE_ERROR_COUNT;
            case 438:
                return SPEAKER_ID_ADAPTATION_PROCESSING_COMPLETE;
            case 439:
                return SPEAKER_ID_ADAPTATION_PROCESSING_DELETE_OLD_UTTERANCE;
            case 440:
                return SMARTSPACE_TRIGGER_LOCATION_UPDATE_TIMEOUT_COUNT;
            case 441:
                return SMARTSPACE_HEURISTIC_CLEAR_CHIP_COUNT;
            case 442:
                return SMARTSPACE_HEURISTIC_THROTTLING_COUNT;
            case 443:
                return APP_OPS_READ_PHONE_STATE;
            case 444:
                return SMARTSPACE_HEURISTIC_WIFI_COUNT;
            case 445:
                return SMARTSPACE_TRIGGER_SCREEN_ON_COUNT;
            case 446:
                return SMARTSPACE_TRIGGER_TIME_TICK_COUNT;
            case 447:
                return SMARTSPACE_TRIGGER_LAUNCHER_VISIBILITY_COUNT;
            case 448:
                return LENS_CAMERA_BLOCKED_ON_STARTUP_COUNT;
            case 449:
                return LENS_CAMERA_GRANTED_ON_STARTUP_COUNT;
            case 450:
                return LENS_CAMERA_PENDING_ON_STARTUP_SHOW_FALLBACK_COUNT;
            case 451:
                return LENS_CAMERA_PENDING_ON_STARTUP_SHOW_ONBOARDING_COUNT;
            case 452:
                return ACETONE_OVERLAY_ORIENTATION_MISMATCH;
            case 453:
                return ACETONE_OVERLAY_ORIENTATION_MISMATCH_RESOLVED;
            case 454:
                return ACETONE_OVERLAY_ORIENTATION_MISMATCH_RESOLVED_DELAY;
            case 455:
                return LENS_APP_SHORTCUT_REQUESTED;
            case 456:
                return LENS_APP_SHORTCUT_INSTALLED;
            case 457:
                return LENS_RESULTS_PANEL_IMAGE_LOAD_SUCCESS_RATE;
            case 458:
                return TAPAS_SERVER_SOURCE_TIMEOUT_COUNT;
            case 459:
                return TAPAS_SERVER_SOURCE_FAILURE_COUNT;
            case 460:
                return SMARTSPACE_TRIGGER_LOCATION_UPDATE_DISCARD_COUNT;
            case 461:
                return SMARTSPACE_TRIGGER_LOCATION_UPDATE_MAX_AGE_DISCARD_COUNT;
            case 462:
                return TAPAS_SERVER_SOURCE_ZERO_PREFIX_SUCCESS_COUNT;
            case 463:
                return TAPAS_SERVER_SOURCE_N_PREFIX_SUCCESS_COUNT;
            case 464:
                return TAPAS_SERVER_SOURCE_ZERO_PREFIX_LATENCY_MILLIS;
            case 465:
                return TAPAS_SERVER_SOURCE_N_PREFIX_LATENCY_MILLIS;
            case 466:
                return ACETONE_GET_VOICE_SEARCH_LANGUAGE_SERVICE_INVOCATION_COUNT;
            case 467:
                return ACETONE_IS_VOICE_DETECTION_RUNNING_SERVICE_INVOCATION_COUNT;
            case 468:
                return ACETONE_REQUEST_VOICE_DETECTION_INVOCATION_COUNT;
            case 469:
                return ACETONE_HAS_OVERLAY_CONTENT_INVOCATION_COUNT;
            case 470:
                return ACETONE_START_SEARCH_INVOCATION_COUNT;
            case 471:
                return LENS_APP_SHORTCUT_MENU_CLICKED;
            case 472:
                return TAPAS_SERVER_SOURCE_SUCCESS_N_PREFIX_LATENCY_MILLIS;
            case 473:
                return TAPAS_SERVER_SOURCE_TIMEOUT_N_PREFIX_LATENCY_MILLIS;
            case 474:
                return TAPAS_SUGGESTION_FETCH_0_PREFIX_LATENCY_MILLIS;
            case 475:
                return TAPAS_SUGGESTION_FETCH_N_PREFIX_LATENCY_MILLIS;
            case 476:
                return TAPAS_SUGGESTION_RENDER_0_PREFIX_LATENCY_MILLIS;
            case 477:
                return TAPAS_SUGGESTION_RENDER_N_PREFIX_LATENCY_MILLIS;
            case 478:
                return TAPAS_MIX_RESPONSE_0_PREFIX_LATENCY_MILLIS;
            case 479:
                return TAPAS_MIX_RESPONSE_N_PREFIX_LATENCY_MILLIS;
            case 480:
                return SMARTSPACE_PLACE_FEEDBACK;
            case 481:
                return LENS_SRP_CACHE_HIT;
            case 482:
                return LENS_SRP_CACHE_MISS;
            case 483:
                return SMARTSPACE_SEARCH_PROCESS_STARTED_COUNT;
            case 484:
                return VOICE_MATCH_INCOMPLETE_ENROLLED_ON_FIRST_ATTEMPT_COUNT;
            case 485:
                return VOICE_MATCH_INCOMPLETE_ENROLLED_ON_SECOND_ATTEMPT_COUNT;
            case 486:
                return VOICE_MATCH_INCOMPLETE_ENROLLED_ON_THIRD_OR_LATER_ATTEMPT_COUNT;
            case 487:
                return SMARTSPACE_HAMMERSPACE_INDEX_DOWNLOAD_COUNT;
            case 488:
                return SMARTSPACE_HAMMERSPACE_SLICES_DOWNLOAD_COUNT;
            case 489:
                return PACKAGE_SUSPENDED_EVENT_COUNT;
            case 490:
                return PACKAGE_UNSUSPENDED_IN_ACETONE_EVENT_COUNT;
            case 491:
                return ACETONE_ACCESS_IN_SUSPENDED_MODE_COUNT;
            case 492:
                return MEDIA_GLANCEABILITY_PREVIOUS;
            case 493:
                return MEDIA_GLANCEABILITY_PAUSE;
            case 494:
                return MEDIA_GLANCEABILITY_PLAY;
            case 495:
                return MEDIA_GLANCEABILITY_NEXT;
            case 496:
                return MEDIA_GLANCEABILITY_SESSION_DESTROYED;
            case 497:
                return SMARTSPACE_FEATURE_KEEP_SLICEPROVIDER_COUNT;
            case 498:
                return VOICE_MATCH_SETTING_ERROR_FROM_DECLINED_STATE;
            case 499:
                return SMARTSPACE_ALARM_SUGGESTIONS_LATENCY_MILLIS;
            case 500:
                return SMARTSPACE_TRIGGER_LOCATION_UPDATE_SPEED_LIMIT_DISCARD_COUNT;
            case 501:
                return TAPAS_BLUE_CHIP_SERVICE_FETCH_LATENCY_MILLIS;
            case 502:
                return SMARTSPACE_SEARCH_PROCESS_DOWN_COUNT;
            case 503:
                return SMARTSPACE_HABITS_PROFILES_PRESENT;
            case 504:
                return SMARTSPACE_HABITS_ACTIVITIES_PROFILE_PRESENT;
            case 505:
                return SMARTSPACE_HABITS_HOME_AUTOMATION_PROFILE_PRESENT;
            case 506:
                return SMARTSPACE_HABITS_MEDIA_PROFILE_PRESENT;
            case 507:
                return SMARTSPACE_HABITS_AWAKE_PROFILE_PRESENT;
            case 508:
                return SMARTSPACE_HABITS_SHOPPING_PROFILE_PRESENT;
            case 509:
                return SMARTSPACE_HABITS_ON_FIRST_ACCESS_PRESENT;
            case 510:
                return SMARTSPACE_WIDGET_SIZE_DIP;
            case 511:
                return SMARTSPACE_HABITS_PERSONALIZATION_ENABLED_STATUS;
            case 512:
                return SMARTSPACE_HABITS_CAST_DEVICE_FOUND;
            case 513:
                return TAPAS_APP_ACTIONS_SHORTCUT_SOURCE_LATENCY_MILLIS;
            case 514:
                return SMARTSPACE_HABITS_PROFILES_FAILURE;
            case 515:
                return SMARTSPACE_HABITS_ON_FIRST_ACCESS_FAILURE;
            case 516:
                return SMARTSPACE_TRIGGER_HEADPHONE_COUNT;
            case 517:
                return SMARTSPACE_HABITS_LOCATION_CAFE_PROFILE_PRESENT;
            case 518:
                return SMARTSPACE_HABITS_LOCATION_GAS_STATION_PROFILE_PRESENT;
            case 519:
                return SMARTSPACE_HABITS_LOCATION_PARKING_PROFILE_PRESENT;
            case 520:
                return SMARTSPACE_HABITS_LOCATION_RESTAURANT_PROFILE_PRESENT;
            case 521:
                return SMARTSPACE_HABITS_LOCATION_SHOPPING_CENTER_PROFILE_PRESENT;
            case 522:
                return SMARTSPACE_HABITS_LOCATION_STORE_PROFILE_PRESENT;
            case 523:
                return SMARTSPACE_HABITS_LOCATION_TRANSIT_STATION_PROFILE_PRESENT;
            case 524:
                return SMARTSPACE_FEATURE_ASSISTANT_SHOPPING_LIST_COUNT;
            case 525:
                return SMARTSPACE_FEATURE_GPAY_LOYALTY_CARD_COUNT;
            case 526:
                return SMARTSPACE_FEATURE_KEEP_SHOPPING_LIST_COUNT;
            case 527:
                return MEDIA_GLANCEABILITY_CARD_IMPRESSION;
            case 528:
                return SMARTSPACE_HABITS_MEDIA_PROFILE_AGE_SECONDS;
            case 529:
                return MEDIA_GLANCEABILITY_TIME_OUT;
            case 530:
                return SMARTSPACE_HABITS_TIME_SPENT_RATIO_THRESHOLD_EXCEEDED_RATE;
            case 531:
                return NGA_DATA_SYNC_DOWNLOADED_GROUP_NO_CONFIG;
            case 532:
                return SEARCH_PROCESS_LIFETIME;
            case 533:
                return TAPAS_SUGGESTION_FETCH_SUCCESS_COUNT;
            case 534:
                return TAPAS_SUGGESTION_FETCH_0_PREFIX_SUCCESS_COUNT;
            case 535:
                return TAPAS_SUGGESTION_FETCH_N_PREFIX_SUCCESS_COUNT;
            case 536:
                return SMARTSPACE_CHIME_REGISTRATION_TRIGGER;
            case 537:
                return SMARTSPACE_CHIME_REGISTRATION_FAILURE;
            case 538:
                return SMARTSPACE_CHIME_REGISTRATION_SUCCESS;
            case 539:
                return SMARTSPACE_CHIME_REGISTRATION_WORKER_ENQUEUE_FAILURE;
            case 540:
                return LENS_UDC_SETTINGS_CHECK_ATTEMPT_COUNT;
            case 541:
                return LENS_UDC_SETTINGS_CHECK_SUCCESS_RATE;
            case 542:
                return SMARTSPACE_WEATHER_PERIODIC_POLLING_TASK_TRIGGER;
            case 543:
                return SMARTSPACE_WEATHER_PERIODIC_POLLING_REQUEST_START_EVENT;
            case 544:
                return OFFLINE_INTERPRETER_OFFLINE_USAGE_RATE;
            case 545:
                return OFFLINE_INTERPRETER_DOWNLOAD_SUCCESS_RATE;
            case 546:
                return OFFLINE_INTERPRETER_DELETE_SUCCESS_RATE;
            case 547:
                return SMARTSPACE_HYBRID_HOTSEAT_SUGGESTION_COUNT;
            case 548:
                return SMARTSPACE_HYBRID_HOTSEAT_SUGGESTION_CONTEXT_COUNT;
            case 549:
                return SMARTSPACE_WEATHER_UPDATE_REQUEST;
            case 550:
                return SMARTSPACE_WEATHER_UPDATE_ACTION;
            case 551:
                return SMARTSPACE_WEATHER_UPDATE_STORAGE;
            case 552:
                return SMARTSPACE_WEATHER_SEND_SURFACE;
            case 553:
                return PCP_SMARTSPACE_WEATHER_UPDATE;
            case 554:
                return PCP_SMARTSPACE_WEATHER_NOTIFICATION;
            case 556:
                return HOTWORD_MODEL_MDD_ADD_PENDING;
            case 557:
                return HOTWORD_MODEL_MDD_ADD_FAILED;
            case 558:
                return HOTWORD_MODEL_MDD_ADD_ALREADY_DOWNLOADED;
            case 559:
                return HOTWORD_MODEL_MDD_ADD_LOST;
            case 561:
                return TAPAS_GEMINI_GRPC_SETUP_LATENCY_MILLIS;
            case 562:
                return TAPAS_GEMINI_GRPC_TRANSIT_LATENCY_MILLIS;
            case 563:
                return SMARTSPACE_CALENDAR_UPDATE_REQUEST;
            case 564:
                return SMARTSPACE_CALENDAR_UPDATE_STORAGE;
            case 565:
                return SMARTSPACE_CALENDAR_SEND_SURFACE;
            case 566:
                return PCP_SMARTSPACE_CALENDAR_NOTIFICATION;
            case 567:
                return QSB_WIDGET_APP_SHORTCUT_REQUESTED;
            case 568:
                return QSB_WIDGET_APP_SHORTCUT_INSTALLED;
            case 569:
                return APP_OPS_BLUETOOTH_COUNT;
            case 570:
                return SMARTSPACE_CALENDAR_UPDATE_THIRD_PARTY;
            case 571:
                return SMARTSPACE_CALENDAR_UPDATE_WORK_PROFILE;
            case 572:
                return GMM_STATE_PARAMS_PROTO_FILLER_GRPC_FETCH_COUNT;
            case 573:
                return CLIENT_EVENT_EMITTED_COUNT;
            case 574:
                return SEARCH_CLIENT_EVENT_EMITTED_RATE;
            case 575:
                return AAP_HOTWORD_DETECTED_COUNT;
            case 576:
                return WEBVIEWS_CREATED;
            case 577:
                return AAP_HOTWORD_ONGOING_SESSION_DETECTED_COUNT;
            case 578:
                return AAP_HOTWORD_ONGOING_SESSION_DETECTED_TNG_COUNT;
            case 579:
                return APP_OPS_MEDIA_IMAGES_COUNT;
            case 580:
                return APP_OPS_MEDIA_VIDEO_COUNT;
            case 581:
                return APP_OPS_MEDIA_AUDIO_COUNT;
            case 582:
                return GELLER_SYNC_WORKER_WEB_SEARCH_DELETION_NOTIFICATION_COUNT;
            case 583:
                return ACTIVITY_ONCREATE_COUNT;
            case 584:
                return PROVIDER_QUERY_COUNT;
            case 585:
                return PROVIDER_INSERT_COUNT;
            case 586:
                return PROVIDER_UPDATE_COUNT;
            case 587:
                return PROVIDER_DELETE_COUNT;
            case 588:
                return PROVIDER_OPEN_FILE_COUNT;
            case 589:
                return PROVIDER_GET_TYPE_COUNT;
            case 590:
                return MANIFEST_RECEIVER_ON_RECEIVE_COUNT;
            case 591:
                return SERVICE_ONCREATE_COUNT;
            default:
                return null;
        }
    }

    /* renamed from: b */
    public static C62959cf m196860b() {
        return C118568a.f329184a;
    }

    public final int getNumber() {
        return this.f329776ks;
    }

    public final String toString() {
        return Integer.toString(this.f329776ks);
    }
}
