package com.google.android.apps.gsa.staticplugins.hotwordenrollment.p7979d;

/* renamed from: com.google.android.apps.gsa.staticplugins.hotwordenrollment.d.m */
/* compiled from: PG */
public enum C101773m {
    DEVICE_SCAN,
    NO_SCREEN,
    HOTWORD_SCREEN,
    VOICE_MATCH_CONSENT_SCREEN,
    PARENT_SELECTOR,
    PARENT_REAUTH_PERMISSION,
    FRESH_ENROLL_SCREEN,
    PROGRESS_UPDATE_SCREEN,
    CLOUD_ENROLL_SCREEN,
    SUMMARY_SCREEN,
    GOOGLE_HOME_PERSONAL_RESULTS_SCREEN,
    AVOCADO,
    VAA_CONSENT_SCREEN,
    PAYMENTS_OPT_IN_SCREEN,
    STRUCTURE_LEVEL_ASSISTANT_ALREADY_ENABLED_SCREEN,
    STRUCTURE_LEVEL_ASSISTANT_CONFIRMATION_SCREEN,
    STRUCTURE_LEVEL_ASSISTANT_VOICE_MATCH_SCREEN,
    STRUCTURE_LEVEL_ASSISTANT_AVOCADO,
    STRUCTURE_LEVEL_ASSISTANT_PERSONAL_RESULTS_SCREEN,
    HANDBACK_TO_PARENT_SCREEN,
    UNICORN_GET_YOUR_PARENT_SCREEN,
    DEPENDENCY_CHECK_SCREEN
}
