package com.facebook.litho;

/* renamed from: com.facebook.litho.gt */
/* compiled from: PG */
public final class C6367gt {

    /* renamed from: a */
    final int f18824a;

    /* renamed from: b */
    public final String f18825b;

    /* renamed from: c */
    public final String f18826c;

    /* renamed from: d */
    public final int f18827d;

    public C6367gt(int i, String str, String str2) {
        int i2;
        this.f18824a = i;
        this.f18825b = str;
        this.f18826c = str2;
        int hashCode = str.hashCode() * 961;
        if (str2 == null) {
            i2 = 0;
        } else {
            i2 = str2.hashCode();
        }
        this.f18827d = hashCode + (i2 * 31) + i;
    }

    public final boolean equals(Object obj) {
        String str;
        String str2;
        if (this == obj) {
            return true;
        }
        if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
        C6367gt gtVar = (C6367gt) obj;
        if (this.f18824a == gtVar.f18824a && ((str = this.f18825b) == (str2 = gtVar.f18825b) || str.equals(str2))) {
            String str3 = this.f18826c;
            String str4 = gtVar.f18826c;
            if (str3 == str4) {
                return true;
            }
            if (str3 == null || !str3.equals(str4)) {
                return false;
            }
            return true;
        }
        return false;
    }

    public final int hashCode() {
        return this.f18827d;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("TransitionId{\"");
        sb.append(this.f18825b);
        sb.append("\", ");
        int i = this.f18824a;
        if (i == 1) {
            sb.append("GLOBAL");
        } else if (i != 2) {
            sb.append("AUTOGENERATED");
        } else {
            sb.append("SCOPED(");
            sb.append(this.f18826c);
            sb.append(")");
        }
        sb.append("}");
        return sb.toString();
    }
}
