package com.google.android.apps.search.googleapp.discover.p10181d;

import com.google.protobuf.C62957cd;

/* renamed from: com.google.android.apps.search.googleapp.discover.d.j */
/* compiled from: PG */
public enum C134221j implements C62957cd {
    CARDS_UNSPECIFIED(0),
    CARDS_FULLY_RENDERED(1),
    CARDS_RENDERED_BUT_IMAGE_LOADING_CANCELLED(2),
    CARDS_RENDERED_BUT_IMAGE_LOADING_FAILED(3),
    INELIGIBLE_DETERMINED_BY_SERVER(14),
    INELIGIBLE_DISCOVER_DISABLED(15),
    INELIGIBLE_GMS_CORE_MISSING(16),
    INELIGIBLE_GMS_CORE_DISABLED(17),
    INELIGIBLE_GMS_CORE_UPDATING(18),
    INELIGIBLE_GMS_CORE_INVALID(19),
    INELIGIBLE_GMS_CORE_MISSING_PERMISSION(20),
    INELIGIBLE_GMS_CORE_OTHER(21),
    INELIGIBLE_USER_SIGNED_OUT(22),
    NO_CARDS_FAILED_TO_GET_AUTH_TOKEN(23),
    NO_CARDS_REQUEST_ERROR_NO_INTERNET(24),
    NO_CARDS_REQUEST_ERROR_OTHER(25),
    NO_CARDS_RESPONSE_ERROR_NON_200(26),
    NO_CARDS_RESPONSE_ERROR_ZERO_CARDS(27),
    NO_CARDS_PREVIOUS_REQUEST_RESPONSE_ERROR(28),
    NO_CARDS_UNKNOWN_REASON(29),
    FAILED_TO_RENDER(5),
    SEARCH_BOX_TAPPED(7),
    VOICE_SEARCH_TAPPED(8),
    NAVIGATED_TO_ANOTHER_TAB(10),
    DOODLE_TAPPED(12),
    ACCOUNT_PARTICLE_DISC_TAPPED(13),
    OVERFLOW_MANAGE_INTERESTS_TAPPED(31),
    OVERFLOW_SETTINGS_TAPPED(32),
    OVERFLOW_FEEDBACK_TAPPED(33),
    OVERFLOW_HELP_TAPPED(34),
    CARD_TAPPED(46),
    VIDEO_CARD_TAPPED(47),
    CHANNEL_CHIP_TAPPED(48),
    MORE_STORIES_TAPPED(49),
    FULL_COVERAGE_ICON_TAPPED(50),
    MANAGE_INTERESTS_TAPPED(51),
    CONFIGURATION_CHANGED(30),
    FRAGMENT_STOPPED(11),
    FRAGMENT_PAUSED(43),
    MINUS_ONE_OVERLAY_CLOSED(52),
    UNKNOWN_HIDE_REASON(44),
    NAVIGATED_BACK(9),
    ABORTED_DUE_TO_INVALID_STATE(6),
    NAVIGATED_AWAY_IN_APP(35),
    FEED_HIDDEN(36),
    INELIGIBLE_EULA_NOT_ACCEPTED(37),
    INELIGIBLE_DISCOVER_DISABLED_BY_ENTERPRISE_POLICY(38),
    CLEAR_ALL_IN_PROGRESS(39),
    DATA_IN_STORE_IS_FOR_ANOTHER_USER(40),
    NOT_A_WEB_CHANNELS_SUBSCRIBER(41),
    SWITCHED_FEED_TABS(42),
    BACKGROUND_APPLICATION(53),
    IN_APP_NAVIGATION_AWAY_FROM_DISCOVER(54);
    

    /* renamed from: ab */
    public final int f365682ab;

    private C134221j(int i) {
        this.f365682ab = i;
    }

    public final int getNumber() {
        return this.f365682ab;
    }

    public final String toString() {
        return Integer.toString(this.f365682ab);
    }
}
