package com.google.assistant.p3994s.p3995a;

/* renamed from: com.google.assistant.s.a.ig */
/* compiled from: PG */
public final class C53286ig {
    /* renamed from: a */
    public static /* synthetic */ String m86807a(int i) {
        switch (i) {
            case 1:
                return "UNKNOWN_USE_CASE";
            case 2:
                return "WHATS_NEXT";
            case 3:
                return "SHORTCUTS";
            case 4:
                return "VIP_BIRTHDAY_NOTIFICATION";
            case 5:
                return "OWN_BIRTHDAY_NOTIFICATION";
            case 6:
                return "ANNIVERSARY_NOTIFICATION";
            case 7:
                return "RICH_EVENT_CONFIRMATION_REFRESH";
            case 8:
                return "CITADEL_WEATHER";
            case 9:
                return "SMARTSPACE_WEATHER";
            case 10:
                return "SMARTSPACE_FLIGHT";
            case 11:
                return "OPEN_ZERO_STATE_FROM_MINUS_ONE_PAGE_UPDATES_BUTTON";
            case 12:
                return "OPEN_ZERO_STATE_FROM_EXPLORE_UPDATES_BUTTON";
            case 13:
                return "OPEN_ZERO_STATE_FROM_UPDATES_TAB";
            case 14:
                return "SHARE_WITH_ASSISTANT";
            case 15:
                return "ASSISTANT_CONVERSATION_ADD_EVENT";
            case 16:
                return "ASSISTANT_CONVERSATION_ADD_REMINDER";
            case 17:
                return "ASSISTANT_CONVERSATION_ADD_NOTE";
            case 18:
                return "ASSISTANT_CONVERSATION_ADD_LIST";
            case 19:
                return "ASSISTANT_CONVERSATION_ADD_SHOPPING_ITEM";
            case 20:
                return "BROKERAGE_CONSENT_CARD_REFRESH";
            case 21:
                return "OTHER_USE_CASE_FROM_AGSA_DEEP_LINK";
            case 22:
                return "OPEN_ZERO_STATE_FROM_OPA_INPUT_PLATE_UPDATES_BUTTON";
            case 23:
                return "OPEN_ZERO_STATE_FROM_OPA_SWIPE_UP";
            case 24:
                return "OPEN_ZERO_STATE_FROM_DREAMLINER_AOD_OPA_LOGO";
            case 26:
                return "ON_MY_WAY_HOME_REFRESH";
            case 27:
                return "AMBIENT_MODE_COMMUTE";
            case 28:
                return "FAB_V2_FLOW_REFRESH";
            case 29:
                return "OPEN_ZERO_STATE_FROM_HOMESCREEN_SHORTCUT";
            case 30:
                return "BILL_NOTIFICATION";
            case 31:
                return "OPEN_SNAPSHOT_FROM_ASSISTANT_DESTINATIONS_TABBAR";
            case 32:
                return "OPEN_ZERO_STATE_FROM_NGA_INPUT_PLATE";
            case 33:
                return "SMARTSPACE_BIRTHDAY";
            case 34:
                return "BANK_CONSENT_CARD_REFRESH";
            case 35:
                return "PHOX_NEW_MOVIE_NOTIFICATION";
            case 36:
                return "CARD_PINNING_REFRESH";
            case 37:
                return "OPEN_SNAPSHOT_FROM_AGSA_MORE_MENU";
            case 38:
                return "ASSISTANT_CONVERSATION_STARTER";
            case 39:
                return "OPEN_ZERO_STATE_FROM_ASSISTANT_SHELL_APP";
            case 40:
                return "DISABLE_CATEGORY_REFRESH";
            case 41:
                return "FORWARDED_FROM_OPA_ACTIVITY";
            case 42:
                return "FORWARDED_FROM_OPA_STARTER";
            case 43:
                return "RESTART_SNAPSHOT_AFTER_OPA_ONBOARDING_SEQUENCE";
            case 44:
                return "RESTART_SNAPSHOT_AFTER_OPA_STARTUP_SEQUENCE";
            case 45:
                return "RESTART_SNAPSHOT_AFTER_STARTUP_SEQUENCE";
            case 46:
                return "RESTART_SNAPSHOT_AFTER_SNAPSHOT_LOCATION_HISTORY_CONSENT_SEQUENCE";
            case 47:
                return "AOG_ACCOUNT_LINK_REFRESH";
            case 48:
                return "AOG_ACCOUNT_UNLINK_REFRESH";
            case 49:
                return "PHOX_NEW_TASK_NOTIFICATION";
            case 50:
                return "SNAPSHOT_WELCOME_SCREEN";
            case 51:
                return "OPEN_SNAPSHOT_FROM_REMINDER_LINK";
            case 52:
                return "CUSTOMISATION_CALLBACK_REFRESH";
            case 53:
                return "PUBLIC_HOLIDAY_OPT_IN";
            default:
                return "null";
        }
    }

    /* renamed from: b */
    public static int m86808b(int i) {
        switch (i) {
            case 0:
                return 1;
            case 1:
                return 2;
            case 2:
                return 3;
            case 3:
                return 4;
            case 4:
                return 5;
            case 5:
                return 6;
            case 6:
                return 7;
            case 7:
                return 8;
            case 8:
                return 9;
            case 9:
                return 10;
            case 10:
                return 11;
            case 11:
                return 12;
            case 12:
                return 13;
            case 13:
                return 14;
            case 14:
                return 15;
            case 15:
                return 16;
            case 16:
                return 17;
            case 17:
                return 18;
            case 18:
                return 19;
            case 19:
                return 20;
            case 20:
                return 21;
            case 21:
                return 22;
            case 22:
                return 23;
            case 23:
                return 24;
            case 25:
                return 26;
            case 26:
                return 27;
            case 27:
                return 28;
            case 28:
                return 29;
            case 29:
                return 30;
            case 30:
                return 31;
            case 31:
                return 32;
            case 32:
                return 33;
            case 33:
                return 34;
            case 34:
                return 35;
            case 35:
                return 36;
            case 36:
                return 37;
            case 37:
                return 38;
            case 38:
                return 39;
            case 39:
                return 40;
            case 40:
                return 41;
            case 41:
                return 42;
            case 42:
                return 43;
            case 43:
                return 44;
            case 44:
                return 45;
            case 45:
                return 46;
            case 46:
                return 47;
            case 47:
                return 48;
            case 48:
                return 49;
            case 49:
                return 50;
            case 50:
                return 51;
            case 51:
                return 52;
            case 52:
                return 53;
            default:
                return 0;
        }
    }
}
