package com.google.protos.p4972d.p4983c;

import org.chromium.net.PrivateKeyType;

/* renamed from: com.google.protos.d.c.j */
/* compiled from: PG */
public final class C64641j {
    /* renamed from: a */
    public static int m96422a(int i) {
        if (i == 0) {
            return 1;
        }
        if (i == 1) {
            return 2;
        }
        if (i == 2) {
            return 3;
        }
        if (i == 3) {
            return 4;
        }
        switch (i) {
            case 100:
                return 101;
            case 101:
                return 102;
            case 102:
                return 103;
            case 103:
                return 104;
            case 104:
                return 105;
            case 105:
                return 106;
            case 106:
                return 107;
            case 107:
                return 108;
            case 108:
                return 109;
            case 109:
                return 110;
            case 110:
                return 111;
            case 111:
                return 112;
            case 112:
                return 113;
            case 113:
                return 114;
            case 114:
                return 115;
            case 115:
                return 116;
            case 116:
                return 117;
            case 117:
                return 118;
            case 118:
                return 119;
            case 119:
                return 120;
            case 120:
                return 121;
            case 121:
                return 122;
            case 122:
                return 123;
            case 123:
                return 124;
            case 124:
                return 125;
            case 125:
                return 126;
            case 126:
                return 127;
            case 127:
                return 128;
            case 128:
                return 129;
            case 129:
                return 130;
            case 130:
                return 131;
            case 131:
                return 132;
            case 132:
                return 133;
            case 133:
                return 134;
            case 134:
                return 135;
            case 135:
                return 136;
            case 136:
                return 137;
            case 137:
                return 138;
            case 138:
                return 139;
            case 139:
                return 140;
            case 140:
                return 141;
            case 141:
                return 142;
            case 142:
                return 143;
            case 143:
                return 144;
            case 144:
                return 145;
            case 145:
                return 146;
            case 146:
                return 147;
            case 147:
                return 148;
            case 148:
                return 149;
            case 149:
                return 150;
            case 150:
                return 151;
            case 151:
                return 152;
            case 152:
                return 153;
            case 153:
                return 154;
            case 154:
                return 155;
            case 155:
                return 156;
            case 156:
                return 157;
            case 157:
                return 158;
            case 158:
                return 159;
            case 159:
                return 160;
            case 160:
                return 161;
            case 161:
                return 162;
            case 162:
                return 163;
            case 163:
                return 164;
            case 164:
                return 165;
            case 165:
                return 166;
            case 166:
                return 167;
            case 167:
                return 168;
            case 168:
                return 169;
            case 169:
                return 170;
            case 170:
                return 171;
            case 171:
                return 172;
            case 172:
                return 173;
            case 173:
                return 174;
            case 174:
                return 175;
            case 175:
                return 176;
            case 176:
                return 177;
            case 177:
                return 178;
            case 178:
                return 179;
            case 179:
                return 180;
            case 180:
                return 181;
            case 181:
                return 182;
            case 182:
                return 183;
            case 183:
                return 184;
            case 184:
                return 185;
            case 185:
                return 186;
            case 186:
                return 187;
            case 187:
                return 188;
            case 188:
                return 189;
            case 189:
                return 190;
            case 190:
                return 191;
            case 191:
                return 192;
            case 192:
                return 193;
            case 193:
                return 194;
            case 194:
                return 195;
            case 195:
                return 196;
            case 196:
                return 197;
            case 197:
                return 198;
            default:
                switch (i) {
                    case 199:
                        return 200;
                    case 200:
                        return 201;
                    case 201:
                        return 202;
                    case 202:
                        return 203;
                    case 203:
                        return 204;
                    case 204:
                        return 205;
                    case 205:
                        return 206;
                    case 206:
                        return 207;
                    case 207:
                        return 208;
                    case 208:
                        return 209;
                    case 209:
                        return 210;
                    case 210:
                        return 211;
                    case 211:
                        return 212;
                    case 212:
                        return 213;
                    case 213:
                        return 214;
                    case 214:
                        return 215;
                    case 215:
                        return 216;
                    case 216:
                        return 217;
                    case 217:
                        return 218;
                    case 218:
                        return 219;
                    case 219:
                        return 220;
                    case 220:
                        return 221;
                    default:
                        switch (i) {
                            case 222:
                                return 223;
                            case 223:
                                return 224;
                            case 224:
                                return 225;
                            case 225:
                                return 226;
                            case 226:
                                return 227;
                            case 227:
                                return 228;
                            case 228:
                                return 229;
                            case 229:
                                return 230;
                            case 230:
                                return 231;
                            case 231:
                                return 232;
                            case 232:
                                return 233;
                            case 233:
                                return 234;
                            case 234:
                                return 235;
                            case 235:
                                return 236;
                            case 236:
                                return 237;
                            case 237:
                                return 238;
                            case 238:
                                return 239;
                            case 239:
                                return 240;
                            case 240:
                                return 241;
                            case 241:
                                return 242;
                            case 242:
                                return 243;
                            case 243:
                                return 244;
                            case 244:
                                return 245;
                            case 245:
                                return 246;
                            case 246:
                                return 247;
                            case 247:
                                return 248;
                            default:
                                switch (i) {
                                    case 250:
                                        return 251;
                                    case 251:
                                        return 252;
                                    case 252:
                                        return 253;
                                    case 253:
                                        return 254;
                                    case 254:
                                        return PrivateKeyType.INVALID;
                                    case PrivateKeyType.INVALID /*255*/:
                                        return 256;
                                    case 256:
                                        return 257;
                                    case 257:
                                        return 258;
                                    case 258:
                                        return 259;
                                    case 259:
                                        return 260;
                                    case 260:
                                        return 261;
                                    case 261:
                                        return 262;
                                    case 262:
                                        return 263;
                                    case 263:
                                        return 264;
                                    case 264:
                                        return 265;
                                    case 265:
                                        return 266;
                                    case 266:
                                        return 267;
                                    case 267:
                                        return 268;
                                    case 268:
                                        return 269;
                                    case 269:
                                        return 270;
                                    case 270:
                                        return 271;
                                    case 271:
                                        return 272;
                                    case 272:
                                        return 273;
                                    case 273:
                                        return 274;
                                    case 274:
                                        return 275;
                                    case 275:
                                        return 276;
                                    case 276:
                                        return 277;
                                    case 277:
                                        return 278;
                                    case 278:
                                        return 279;
                                    case 279:
                                        return 280;
                                    case 280:
                                        return 281;
                                    case 281:
                                        return 282;
                                    case 282:
                                        return 283;
                                    case 283:
                                        return 284;
                                    case 284:
                                        return 285;
                                    case 285:
                                        return 286;
                                    case 286:
                                        return 287;
                                    case 287:
                                        return 288;
                                    case 288:
                                        return 289;
                                    case 289:
                                        return 290;
                                    case 290:
                                        return 291;
                                    case 291:
                                        return 292;
                                    case 292:
                                        return 293;
                                    case 293:
                                        return 294;
                                    case 294:
                                        return 295;
                                    case 295:
                                        return 296;
                                    case 296:
                                        return 297;
                                    case 297:
                                        return 298;
                                    case 298:
                                        return 299;
                                    case 299:
                                        return 300;
                                    case 300:
                                        return 301;
                                    case 301:
                                        return 302;
                                    case 302:
                                        return 303;
                                    case 303:
                                        return 304;
                                    case 304:
                                        return 305;
                                    case 305:
                                        return 306;
                                    case 306:
                                        return 307;
                                    case 307:
                                        return 308;
                                    case 308:
                                        return 309;
                                    case 309:
                                        return 310;
                                    case 310:
                                        return 311;
                                    case 311:
                                        return 312;
                                    case 312:
                                        return 313;
                                    case 313:
                                        return 314;
                                    case 314:
                                        return 315;
                                    case 315:
                                        return 316;
                                    case 316:
                                        return 317;
                                    case 317:
                                        return 318;
                                    case 318:
                                        return 319;
                                    case 319:
                                        return 320;
                                    case 320:
                                        return 321;
                                    case 321:
                                        return 322;
                                    case 322:
                                        return 323;
                                    case 323:
                                        return 324;
                                    case 324:
                                        return 325;
                                    case 325:
                                        return 326;
                                    case 326:
                                        return 327;
                                    case 327:
                                        return 328;
                                    case 328:
                                        return 329;
                                    case 329:
                                        return 330;
                                    case 330:
                                        return 331;
                                    case 331:
                                        return 332;
                                    case 332:
                                        return 333;
                                    case 333:
                                        return 334;
                                    case 334:
                                        return 335;
                                    case 335:
                                        return 336;
                                    case 336:
                                        return 337;
                                    case 337:
                                        return 338;
                                    case 338:
                                        return 339;
                                    case 339:
                                        return 340;
                                    case 340:
                                        return 341;
                                    case 341:
                                        return 342;
                                    case 342:
                                        return 343;
                                    case 343:
                                        return 344;
                                    case 344:
                                        return 345;
                                    case 345:
                                        return 346;
                                    default:
                                        switch (i) {
                                            case 353:
                                                return 354;
                                            case 354:
                                                return 355;
                                            case 355:
                                                return 356;
                                            case 356:
                                                return 357;
                                            case 357:
                                                return 358;
                                            case 358:
                                                return 359;
                                            case 359:
                                                return 360;
                                            case 360:
                                                return 361;
                                            case 361:
                                                return 362;
                                            case 362:
                                                return 363;
                                            case 363:
                                                return 364;
                                            case 364:
                                                return 365;
                                            case 365:
                                                return 366;
                                            case 366:
                                                return 367;
                                            case 367:
                                                return 368;
                                            default:
                                                switch (i) {
                                                    case 369:
                                                        return 370;
                                                    case 370:
                                                        return 371;
                                                    case 371:
                                                        return 372;
                                                    case 372:
                                                        return 373;
                                                    case 373:
                                                        return 374;
                                                    case 374:
                                                        return 375;
                                                    case 375:
                                                        return 376;
                                                    case 376:
                                                        return 377;
                                                    case 377:
                                                        return 378;
                                                    case 378:
                                                        return 379;
                                                    case 379:
                                                        return 380;
                                                    case 380:
                                                        return 381;
                                                    case 381:
                                                        return 382;
                                                    case 382:
                                                        return 383;
                                                    case 383:
                                                        return 384;
                                                    case 384:
                                                        return 385;
                                                    case 385:
                                                        return 386;
                                                    case 386:
                                                        return 387;
                                                    case 387:
                                                        return 388;
                                                    case 388:
                                                        return 389;
                                                    case 389:
                                                        return 390;
                                                    case 390:
                                                        return 391;
                                                    case 391:
                                                        return 392;
                                                    case 392:
                                                        return 393;
                                                    case 393:
                                                        return 394;
                                                    case 394:
                                                        return 395;
                                                    case 395:
                                                        return 396;
                                                    case 396:
                                                        return 397;
                                                    case 397:
                                                        return 398;
                                                    case 398:
                                                        return 399;
                                                    case 399:
                                                        return 400;
                                                    case 400:
                                                        return 401;
                                                    case 401:
                                                        return 402;
                                                    case 402:
                                                        return 403;
                                                    default:
                                                        return 0;
                                                }
                                        }
                                }
                        }
                }
        }
    }
}
