package com.google.p440an.p441a;

/* renamed from: com.google.an.a.j */
/* compiled from: PG */
public final class C8843j {
    /* renamed from: a */
    public static /* synthetic */ String m23484a(int i) {
        switch (i) {
            case 1:
                return "Adlm";
            case 2:
                return "Afak";
            case 3:
                return "Aghb";
            case 4:
                return "Ahom";
            case 5:
                return "Arab";
            case 6:
                return "Armi";
            case 7:
                return "Armn";
            case 8:
                return "Avst";
            case 9:
                return "Bali";
            case 10:
                return "Bamu";
            case 11:
                return "Bass";
            case 12:
                return "Batk";
            case 13:
                return "Beng";
            case 14:
                return "Bhks";
            case 15:
                return "Blis";
            case 16:
                return "Bopo";
            case 17:
                return "Brah";
            case 18:
                return "Brai";
            case 19:
                return "Bugi";
            case 20:
                return "Buhd";
            case 21:
                return "Cakm";
            case 22:
                return "Cans";
            case 23:
                return "Cari";
            case 24:
                return "Cham";
            case 25:
                return "Cher";
            case 26:
                return "Chrs";
            case 27:
                return "Cirt";
            case 28:
                return "Copt";
            case 29:
                return "Cpmn";
            case 30:
                return "Cprt";
            case 31:
                return "Cyrl";
            case 32:
                return "Cyrs";
            case 33:
                return "Deva";
            case 34:
                return "Diak";
            case 35:
                return "Dogr";
            case 36:
                return "Dsrt";
            case 37:
                return "Dupl";
            case 38:
                return "Egyd";
            case 39:
                return "Egyh";
            case 40:
                return "Egyp";
            case 41:
                return "Elba";
            case 42:
                return "Elym";
            case 43:
                return "Ethi";
            case 44:
                return "Geok";
            case 45:
                return "Geor";
            case 46:
                return "Glag";
            case 47:
                return "Gong";
            case 48:
                return "Gonm";
            case 49:
                return "Goth";
            case 50:
                return "Gran";
            case 51:
                return "Grek";
            case 52:
                return "Gujr";
            case 53:
                return "Guru";
            case 54:
                return "Hanb";
            case 55:
                return "Hang";
            case 56:
                return "Hani";
            case 57:
                return "Hano";
            case 58:
                return "Hans";
            case 59:
                return "Hant";
            case 60:
                return "Hatr";
            case 61:
                return "Hebr";
            case 62:
                return "Hira";
            case 63:
                return "Hluw";
            case 64:
                return "Hmng";
            case 65:
                return "Hmnp";
            case 66:
                return "Hrkt";
            case 67:
                return "Hung";
            case 68:
                return "Inds";
            case 69:
                return "Ital";
            case 70:
                return "Jamo";
            case 71:
                return "Java";
            case 72:
                return "Jpan";
            case 73:
                return "Jurc";
            case 74:
                return "Kali";
            case 75:
                return "Kana";
            case 76:
                return "Khar";
            case 77:
                return "Khmr";
            case 78:
                return "Khoj";
            case 79:
                return "Kits";
            case 80:
                return "Knda";
            case 81:
                return "Kore";
            case 82:
                return "Kpel";
            case 83:
                return "Kthi";
            case 84:
                return "Lana";
            case 85:
                return "Laoo";
            case 86:
                return "Latf";
            case 87:
                return "Latg";
            case 88:
                return "Latn";
            case 89:
                return "Lepc";
            case 90:
                return "Limb";
            case 91:
                return "Lina";
            case 92:
                return "Linb";
            case 93:
                return "Lisu";
            case 94:
                return "Loma";
            case 95:
                return "Lyci";
            case 96:
                return "Lydi";
            case 97:
                return "Mahj";
            case 98:
                return "Maka";
            case 99:
                return "Mand";
            case 100:
                return "Mani";
            case 101:
                return "Marc";
            case 102:
                return "Maya";
            case 103:
                return "Medf";
            case 104:
                return "Mend";
            case 105:
                return "Merc";
            case 106:
                return "Mero";
            case 107:
                return "Mlym";
            case 108:
                return "Modi";
            case 109:
                return "Mong";
            case 110:
                return "Moon";
            case 111:
                return "Mroo";
            case 112:
                return "Mtei";
            case 113:
                return "Mult";
            case 114:
                return "Mymr";
            case 115:
                return "Nand";
            case 116:
                return "Narb";
            case 117:
                return "Nbat";
            case 118:
                return "Newa";
            case 119:
                return "Nkgb";
            case 120:
                return "Nkoo";
            case 121:
                return "Nshu";
            case 122:
                return "Ogam";
            case 123:
                return "Olck";
            case 124:
                return "Orkh";
            case 125:
                return "Orya";
            case 126:
                return "Osge";
            case 127:
                return "Osma";
            case 128:
                return "Ougr";
            case 129:
                return "Palm";
            case 130:
                return "Pauc";
            case 131:
                return "Perm";
            case 132:
                return "Phag";
            case 133:
                return "Phli";
            case 134:
                return "Phlp";
            case 135:
                return "Phlv";
            case 136:
                return "Phnx";
            case 137:
                return "Plrd";
            case 138:
                return "Prti";
            case 139:
                return "Rjng";
            case 140:
                return "Rohg";
            case 141:
                return "Roro";
            case 142:
                return "Runr";
            case 143:
                return "Samr";
            case 144:
                return "Sara";
            case 145:
                return "Sarb";
            case 146:
                return "Saur";
            case 147:
                return "Sgnw";
            case 148:
                return "Shaw";
            case 149:
                return "Shrd";
            case 150:
                return "Sidd";
            case 151:
                return "Sind";
            case 152:
                return "Sinh";
            case 153:
                return "Sogd";
            case 154:
                return "Sogo";
            case 155:
                return "Sora";
            case 156:
                return "Soyo";
            case 157:
                return "Sund";
            case 158:
                return "Sylo";
            case 159:
                return "Syrc";
            case 160:
                return "Syre";
            case 161:
                return "Syrj";
            case 162:
                return "Syrn";
            case 163:
                return "Tagb";
            case 164:
                return "Takr";
            case 165:
                return "Tale";
            case 166:
                return "Talu";
            case 167:
                return "Taml";
            case 168:
                return "Tang";
            case 169:
                return "Tavt";
            case 170:
                return "Telu";
            case 171:
                return "Teng";
            case 172:
                return "Tfng";
            case 173:
                return "Tglg";
            case 174:
                return "Thaa";
            case 175:
                return "Thai";
            case 176:
                return "Tibt";
            case 177:
                return "Tirh";
            case 178:
                return "Tnsa";
            case 179:
                return "Toto";
            case 180:
                return "Ugar";
            case 181:
                return "Vaii";
            case 182:
                return "Visp";
            case 183:
                return "Vith";
            case 184:
                return "Wara";
            case 185:
                return "Wcho";
            case 186:
                return "Wole";
            case 187:
                return "Xpeo";
            case 188:
                return "Xsux";
            case 189:
                return "Yezi";
            case 190:
                return "Yiii";
            case 191:
                return "Zanb";
            case 192:
                return "Zinh";
            case 193:
                return "Zmth";
            case 194:
                return "Zsye";
            case 195:
                return "Zsym";
            case 196:
                return "Zxxx";
            case 197:
                return "Zyyy";
            case 198:
                return "Zzzz";
            default:
                return "null";
        }
    }
}
