package com.google.android.apps.gsa.staticplugins.opa.p8595v;

/* renamed from: com.google.android.apps.gsa.staticplugins.opa.v.w */
/* compiled from: PG */
public enum C113919w {
    NO_CONNECTIVITY,
    RECOGNITION_ERROR,
    UNRELIABLE_NETWORK,
    SERVER_ERROR,
    S3_ERROR,
    GENERIC_GSA_ERROR,
    GENERIC_ERROR,
    OPA_SSC_USER_DISCONNECT,
    CANCELED,
    GRAPH_FAILURE,
    HANDED_OVER_TO_OPA,
    HANDOVER_RECEIVED,
    HANDOVER_CONFIRMED,
    END_STATE_LOGGED,
    CLIENT_OP_CORE_DISMISS_ASSISTANT,
    HANDED_OVER_TO_OPA_WITHOUT_UI,
    HANDOVER_WITHOUT_UI_DONE,
    HANDOVER_WITHOUT_UI_CANCELLED,
    HANDOVER_WITHOUT_UI_FAILED,
    HANDOVER_WITHOUT_UI_NO_SPEECH_DETECTED,
    HANDOVER_WITHOUT_UI_ACTION_V2_FOLLOW_ON_QUERY_COMMIT,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_FAILURE_NO_CONNECTIVITY,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_FAILURE_UNRELIABLE_NETWORK,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_CANCEL_USER_ERROR,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_FAILURE_RECOGNIZER_NO_MATCH_FROM_NETWORK,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_FAILURE_MISSING_LANGUAGE_PACK,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_FAILURE_GENERIC_GSA_ERROR,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_FAILURE_SERVER_ERROR,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_FAILURE_S3_ERROR,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_FAILURE_GENERIC_ERROR,
    HANDOVER_WITHOUT_UI_OPA_ENDSTATE_CANCEL_NEW_HOTWORD
}
