package com.google.protos.p4985f.p5036r;

/* renamed from: com.google.protos.f.r.p */
/* compiled from: PG */
public final class C65330p {
    /* renamed from: a */
    public static /* synthetic */ String m96669a(int i) {
        switch (i) {
            case 1:
                return "UNKNOWN";
            case 2:
                return "ALARMS";
            case 3:
                return "ASSISTANT_EXPLORE";
            case 4:
                return "BROADCAST";
            case 5:
                return "BLUE_GINGER";
            case 6:
                return "BLUE_GINGER_PROD";
            case 7:
                return "CALL_ON_CHIRP";
            case 8:
                return "CASSE";
            case 9:
                return "CREATIVE_LAB";
            case 10:
                return "CONCISE_ANSWERS";
            case 11:
                return "CROSS_SURFACE_SENDER";
            case 12:
                return "OPA_SURVEY";
            case 13:
                return "DEVICE_ACTIONS";
            case 14:
                return "DIALOG_MANAGER";
            case 15:
                return "ELENCHUS";
            case 16:
                return "GBOT";
            case 17:
                return "HOME_AUTOMATION";
            case 18:
                return "HEALTH";
            case 19:
                return "HOME_INTELLIGENCE_SERVICE";
            case 20:
                return "INTERACTIVE_QUESTIONS";
            case 21:
                return "KNOWLEDGE_CARD";
            case 22:
                return "MEDIA";
            case 23:
                return "COMMUNICATION";
            case 24:
                return "MISSED_CALL";
            case 25:
                return "NEWS";
            case 26:
                return "OPA_GROWTH";
            case 27:
                return "PERSONAL_ACTIONS";
            case 28:
                return "PHOTOS";
            case 29:
                return "PLAY_SERVICES";
            case 30:
                return "PUNT_SENDER";
            case 31:
                return "QUARTZ";
            case 32:
                return "RECIPES";
            case 33:
                return "COPLEY";
            case 34:
                return "REENGAGEMENT";
            case 35:
                return "REMINDERS";
            case 36:
                return "REVERSE_HANDOFF";
            case 37:
                return "RIFLE_BIRD";
            case 38:
                return "SHOPPING_ASSISTANT";
            case 39:
                return "SIDEKICK";
            case 40:
                return "SUPERROOT";
            case 41:
                return "SOMETHING_GOOD";
            case 42:
                return "SUBSCRIPTIONS";
            case 43:
                return "TELL_ME_MORE";
            case 44:
                return "TIMERS";
            case 45:
                return "MULTI_DEVICE_FEEDBACK";
            case 46:
                return "UDC_PERMISSION";
            case 47:
                return "VILLAGER";
            case 48:
                return "WEB_ANSWERS";
            case 49:
                return "WHERE_ABOUTS";
            case 50:
                return "THIRD_PARTY_PROFILES";
            case 51:
                return "SIGN_IN_PUNT_TO_PHONE";
            case 52:
                return "LENS_REMINDER";
            case 53:
                return "AUTOBOT";
            case 54:
                return "IFTTT";
            case 55:
                return "TRAVEL_ASSISTANT";
            case 56:
                return "NOW_PUSH";
            case 57:
                return "DIALER_AUTH";
            case 58:
                return "MODES";
            case 59:
                return "THIRD_PARTY";
            case 60:
                return "BEQUT";
            case 61:
                return "HEADY";
            case 62:
                return "HOME_CONTROL_SERVICE";
            case 63:
                return "ASSISTANT_ROUTINES_SERVICE";
            case 64:
                return "HEALTH_ASSISTANT";
            case 65:
                return "ASSISTANT_SPEAKERS";
            case 66:
                return "ASSISTANT_SETTINGS_UI_SERVICE";
            case 67:
                return "ASSISTANT_DIALOG_ROUTINE_TRIGGER";
            case 68:
                return "ZEROSTATE";
            case 69:
                return "TACHYON";
            case 70:
                return "MULTI_DEVICE_ARBITRATION";
            case 71:
                return "VUI_CONSENT";
            case 72:
                return "HOME_CONCIERGE";
            case 73:
                return "BLUE_GINGER_MADDEN";
            case 74:
                return "ASSISTANT_FAMILY";
            case 75:
                return "ASSISTANT_RECOMMENDATIONS_FEEDBACK";
            case 76:
                return "ASSISTJS";
            case 77:
                return "PROACTIVE_API";
            case 78:
                return "TRANSACTIONS";
            case 79:
                return "XTALK";
            case 80:
                return "DO_IT_AGAIN";
            case 81:
                return "FLIGHT_STATUS_NOTIFICATION_SERVICE";
            case 82:
                return "GMAIL_INTELLIGENCE_PROACTIVE";
            case 83:
                return "SMARTHOME";
            case 84:
                return "ASSISTANT_HELP";
            case 85:
                return "MEETING_INTELLIGENCE";
            case 86:
                return "CONTACTS";
            case 87:
                return "LOCKROY";
            case 88:
                return "HEALTH_AND_FITNESS";
            case 89:
                return "PRIVACY_ACTIONS";
            case 90:
                return "SMART_DISPLAY_WEB";
            case 91:
                return "GEO_ASSISTANT_PROACTIVE";
            case 92:
                return "APP_ACTIONS";
            case 93:
                return "WARM_WORDS";
            case 94:
                return "PHOX";
            case 95:
                return "BTW_PLATFORM";
            case 96:
                return "STICKY_NOTES";
            case 97:
                return "SETTINGS_PUNTS";
            case 98:
                return "MORRIS_OOBE";
            case 99:
                return "ASSISTANT_PIE";
            case 100:
                return "FAMILY_BELL";
            case 101:
                return "VM_PUNT_FRAME";
            case 102:
                return "UNIT_TESTING";
            case 103:
                return "FAMILY_NUDGE_SERVICE";
            case 104:
                return "GSUITE_LINK_ACCOUNT";
            case 105:
                return "ASSISTANT_ASPIRE";
            case 106:
                return "PROACTIVE_BIOGRAPHER";
            case 107:
                return "ASSISTANT_ECOSYSTEM";
            case 108:
                return "VOICE_ENROLLMENT_ON_DEVICE";
            case 109:
                return "ASSISTANT_CALENDAR";
            case 110:
                return "IMPLICIT_APP_ACTION";
            case 111:
                return "ASSISTANT_SUGGESTIONS";
            case 112:
                return "ASSISTANT_SETTINGS";
            case 113:
                return "MORRIS_DRIVING_SCREEN";
            case 114:
                return "AUTO_ECOSYSTEM";
            case 115:
                return "BLUE_STEEL";
            case 116:
                return "SMARTSPACE_HOLIDAY_ALARMS";
            case 117:
                return "CROSS_DEVICE_TIMER";
            default:
                return "SHELDON";
        }
    }

    /* renamed from: b */
    public static int m96670b(int i) {
        switch (i) {
            case 0:
                return 1;
            case 1:
                return 2;
            case 2:
                return 3;
            case 3:
                return 4;
            case 4:
                return 5;
            case 5:
                return 6;
            case 6:
                return 7;
            case 7:
                return 8;
            case 8:
                return 9;
            case 9:
                return 10;
            case 10:
                return 11;
            case 11:
                return 12;
            case 12:
                return 13;
            case 13:
                return 14;
            case 14:
                return 15;
            case 15:
                return 16;
            case 16:
                return 17;
            case 17:
                return 18;
            case 18:
                return 19;
            case 19:
                return 20;
            case 20:
                return 21;
            case 21:
                return 22;
            case 22:
                return 23;
            case 23:
                return 24;
            case 24:
                return 25;
            case 25:
                return 26;
            case 26:
                return 27;
            case 27:
                return 28;
            case 28:
                return 29;
            case 29:
                return 30;
            case 30:
                return 31;
            case 31:
                return 32;
            case 32:
                return 33;
            case 33:
                return 34;
            case 34:
                return 35;
            case 35:
                return 36;
            case 36:
                return 37;
            case 37:
                return 38;
            case 38:
                return 39;
            case 39:
                return 40;
            case 40:
                return 41;
            case 41:
                return 42;
            case 42:
                return 43;
            case 43:
                return 44;
            case 44:
                return 45;
            case 45:
                return 46;
            case 46:
                return 47;
            case 47:
                return 48;
            case 48:
                return 49;
            case 49:
                return 50;
            case 50:
                return 51;
            case 51:
                return 52;
            case 52:
                return 53;
            case 53:
                return 54;
            case 54:
                return 55;
            case 55:
                return 56;
            case 56:
                return 57;
            case 57:
                return 58;
            case 58:
                return 59;
            case 59:
                return 60;
            case 60:
                return 61;
            case 61:
                return 62;
            case 62:
                return 63;
            case 63:
                return 64;
            case 64:
                return 65;
            case 65:
                return 66;
            case 66:
                return 67;
            case 67:
                return 68;
            case 68:
                return 69;
            case 69:
                return 70;
            case 70:
                return 71;
            case 71:
                return 72;
            case 72:
                return 73;
            case 73:
                return 74;
            case 74:
                return 75;
            case 75:
                return 76;
            case 76:
                return 77;
            case 77:
                return 78;
            case 78:
                return 79;
            case 79:
                return 80;
            case 80:
                return 81;
            case 81:
                return 82;
            case 82:
                return 83;
            case 83:
                return 84;
            case 84:
                return 85;
            case 85:
                return 86;
            case 86:
                return 87;
            case 87:
                return 88;
            case 88:
                return 89;
            case 89:
                return 90;
            case 90:
                return 91;
            case 91:
                return 92;
            case 92:
                return 93;
            case 93:
                return 94;
            case 94:
                return 95;
            case 95:
                return 96;
            case 96:
                return 97;
            case 97:
                return 98;
            case 98:
                return 99;
            case 99:
                return 100;
            case 100:
                return 101;
            case 101:
                return 102;
            case 102:
                return 103;
            case 103:
                return 104;
            case 104:
                return 105;
            case 105:
                return 106;
            case 106:
                return 107;
            case 107:
                return 108;
            case 108:
                return 109;
            case 109:
                return 110;
            case 110:
                return 111;
            case 111:
                return 112;
            case 112:
                return 113;
            case 113:
                return 114;
            case 114:
                return 115;
            case 115:
                return 116;
            case 116:
                return 117;
            case 117:
                return 118;
            default:
                return 0;
        }
    }
}
