package com.google.android.libraries.search.p3047m.p3048a.p3049a;

import com.google.protobuf.C62957cd;

/* renamed from: com.google.android.libraries.search.m.a.a.b */
/* compiled from: PG */
public enum C39219b implements C62957cd {
    APP_OPS_UNKNOWN_COUNT(0),
    APP_OPS_ACTIVITY_RECOGNITION_COUNT(1),
    APP_OPS_ACTIVITY_RECOGNITION_COUNT_QUANTIZED(2),
    APP_OPS_BLUETOOTH_COUNT(3),
    APP_OPS_BLUETOOTH_COUNT_QUANTIZED(4),
    APP_OPS_CALENDAR_COUNT(5),
    APP_OPS_CALENDAR_COUNT_QUANTIZED(6),
    APP_OPS_CALL_LOG_COUNT(7),
    APP_OPS_CALL_LOG_COUNT_QUANTIZED(8),
    APP_OPS_CALL_PHONE_COUNT(9),
    APP_OPS_CALL_PHONE_COUNT_QUANTIZED(10),
    APP_OPS_CAMERA_COUNT(11),
    APP_OPS_CAMERA_COUNT_QUANTIZED(12),
    APP_OPS_CONTACTS_COUNT(13),
    APP_OPS_CONTACTS_COUNT_QUANTIZED(14),
    APP_OPS_EXTERNAL_STORAGE_COUNT(15),
    APP_OPS_EXTERNAL_STORAGE_COUNT_QUANTIZED(16),
    APP_OPS_GET_ACCOUNT_COUNT(17),
    APP_OPS_GET_ACCOUNT_COUNT_QUANTIZED(18),
    APP_OPS_LOCATION_COUNT(19),
    APP_OPS_LOCATION_COUNT_QUANTIZED(20),
    APP_OPS_MEDIA_AUDIO_COUNT(21),
    APP_OPS_MEDIA_AUDIO_COUNT_QUANTIZED(22),
    APP_OPS_MEDIA_IMAGES_COUNT(23),
    APP_OPS_MEDIA_IMAGES_COUNT_QUANTIZED(24),
    APP_OPS_MEDIA_VIDEO_COUNT(25),
    APP_OPS_MEDIA_VIDEO_COUNT_QUANTIZED(26),
    APP_OPS_MICROPHONE_COUNT(27),
    APP_OPS_MICROPHONE_COUNT_QUANTIZED(28),
    APP_OPS_OTHER_COUNT(29),
    APP_OPS_OTHER_COUNT_QUANTIZED(30),
    APP_OPS_READ_PHONE_STATE(31),
    APP_OPS_READ_PHONE_STATE_QUANTIZED(32),
    APP_OPS_SMS_COUNT(33),
    APP_OPS_SMS_COUNT_QUANTIZED(34),
    APP_OPS_UNCONSENTED_LOCATION_COUNT(35);
    

    /* renamed from: K */
    private final int f103214K;

    private C39219b(int i) {
        this.f103214K = i;
    }

    public final int getNumber() {
        return this.f103214K;
    }

    public final String toString() {
        return Integer.toString(this.f103214K);
    }
}
