package com.google.android.apps.gsa.staticplugins.opa.morris2.p8395h;

/* renamed from: com.google.android.apps.gsa.staticplugins.opa.morris2.h.ab */
/* compiled from: PG */
public enum C109657ab {
    UNKNOWN,
    ELIGIBLE,
    NOT_ELIGIBLE_DISABLED_BY_SETTING,
    NOT_ELIGIBLE_DISABLED_BY_EXPERIMENT_FLAG,
    NOT_ELIGIBLE_DISABLED_BY_RAM_SIZE,
    NOT_ELIGIBLE_DISABLED_BY_SDK_VERSION,
    NOT_ELIGIBLE_DISABLED_BY_TALKBACK,
    NOT_ELIGIBLE_DISABLED_BY_OPA_AVAILABILITY,
    NOT_ELIGIBLE_DISABLED_BY_CAR_MODE_ALREADY_ENABLED,
    NOT_ELIGIBLE_DISABLED_BY_OOBE,
    NOT_ELIGIBLE_DISABLED_BY_LANDSCAPE,
    NOT_ELIGIBLE_DISABLED_BY_UPSIDE_DOWN,
    NOT_ELIGIBLE_DISABLED_BY_OPT_IN,
    NOT_ELIGIBLE_OPT_IN_NEEDED,
    NOT_ELIGIBLE_OPT_OUT_DIALOG_A_NEEDED,
    NOT_ELIGIBLE_DISABLED_BY_OPT_OUT,
    NOT_ELIGIBLE_OPT_OUT_DIALOG_B_NEEDED
}
