package com.google.assistant.p3781ad.p3787c.p3788a;

import com.google.protobuf.C62957cd;
import com.google.protobuf.C62959cf;

/* renamed from: com.google.assistant.ad.c.a.u */
/* compiled from: PG */
public enum C48541u implements C62957cd {
    CONTINUOUS_FEATURE_UNKNOWN(0),
    CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_WITH_DISPLAY_TEXT(1),
    CONTINUOUS_FEATURE_LONGEST_COMMON_SUBSTRING_LENGTH_WITH_DISPLAY_TEXT(15),
    CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_WITH_APP_NAME(2),
    CONTINUOUS_FEATURE_LONGEST_COMMON_SUBSTRING_LENGTH_WITH_APP_NAME(16),
    CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_DIV_PREFIX_LENGTH_WITH_DISPLAY_TEXT(3),
    CONTINUOUS_FEATURE_LONGEST_COMMON_SUBSTRING_LENGTH_DIV_PREFIX_LENGTH_WITH_DISPLAY_TEXT(17),
    CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_DIV_PREFIX_LENGTH_WITH_APP_NAME(4),
    CONTINUOUS_FEATURE_LONGEST_COMMON_SUBSTRING_LENGTH_DIV_PREFIX_LENGTH_WITH_APP_NAME(18),
    CONTINUOUS_FEATURE_APP_USAGE_RECENCY(5),
    CONTINUOUS_FEATURE_APP_USAGE_FREQUENCY(6),
    CONTINUOUS_FEATURE_NUM_APP_INSTALLS(7),
    CONTINUOUS_FEATURE_NUM_APP_OPENS(19),
    CONTINUOUS_FEATURE_AVERAGE_APP_RATING(8),
    CONTINUOUS_FEATURE_ANY_PACKAGE_ACTION_USAGE_RATIO_BIG(9),
    CONTINUOUS_FEATURE_ANY_PACKAGE_ACTION_USAGE_RATIO_SMALL(10),
    CONTINUOUS_FEATURE_THIS_PACKAGE_ACTION_USAGE_RATIO_BIG(11),
    CONTINUOUS_FEATURE_THIS_PACKAGE_ACTION_USAGE_RATIO_SMALL(12),
    CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_DIV_DISPLAY_TEXT_LENGTH(13),
    CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_DIV_APP_NAME_LENGTH(14),
    CONTINUOUS_FEATURE_USER_PROFILE_SUGGESTION_TAP_COUNT(20),
    CONTINUOUS_FEATURE_USER_PROFILE_PREFIX_MATCH_SUGGESTION_TAP_COUNT(21),
    CONTINUOUS_FEATURE_USER_PROFILE_APP_PACKAGE_TAP_COUNT(22),
    CONTINUOUS_FEATURE_USER_PROFILE_INTENT_TAP_COUNT(23);
    

    /* renamed from: y */
    public final int f125415y;

    private C48541u(int i) {
        this.f125415y = i;
    }

    /* renamed from: a */
    public static C48541u m85233a(int i) {
        switch (i) {
            case 0:
                return CONTINUOUS_FEATURE_UNKNOWN;
            case 1:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_WITH_DISPLAY_TEXT;
            case 2:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_WITH_APP_NAME;
            case 3:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_DIV_PREFIX_LENGTH_WITH_DISPLAY_TEXT;
            case 4:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_DIV_PREFIX_LENGTH_WITH_APP_NAME;
            case 5:
                return CONTINUOUS_FEATURE_APP_USAGE_RECENCY;
            case 6:
                return CONTINUOUS_FEATURE_APP_USAGE_FREQUENCY;
            case 7:
                return CONTINUOUS_FEATURE_NUM_APP_INSTALLS;
            case 8:
                return CONTINUOUS_FEATURE_AVERAGE_APP_RATING;
            case 9:
                return CONTINUOUS_FEATURE_ANY_PACKAGE_ACTION_USAGE_RATIO_BIG;
            case 10:
                return CONTINUOUS_FEATURE_ANY_PACKAGE_ACTION_USAGE_RATIO_SMALL;
            case 11:
                return CONTINUOUS_FEATURE_THIS_PACKAGE_ACTION_USAGE_RATIO_BIG;
            case 12:
                return CONTINUOUS_FEATURE_THIS_PACKAGE_ACTION_USAGE_RATIO_SMALL;
            case 13:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_DIV_DISPLAY_TEXT_LENGTH;
            case 14:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_PREFIX_LENGTH_DIV_APP_NAME_LENGTH;
            case 15:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_SUBSTRING_LENGTH_WITH_DISPLAY_TEXT;
            case 16:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_SUBSTRING_LENGTH_WITH_APP_NAME;
            case 17:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_SUBSTRING_LENGTH_DIV_PREFIX_LENGTH_WITH_DISPLAY_TEXT;
            case 18:
                return CONTINUOUS_FEATURE_LONGEST_COMMON_SUBSTRING_LENGTH_DIV_PREFIX_LENGTH_WITH_APP_NAME;
            case 19:
                return CONTINUOUS_FEATURE_NUM_APP_OPENS;
            case 20:
                return CONTINUOUS_FEATURE_USER_PROFILE_SUGGESTION_TAP_COUNT;
            case 21:
                return CONTINUOUS_FEATURE_USER_PROFILE_PREFIX_MATCH_SUGGESTION_TAP_COUNT;
            case 22:
                return CONTINUOUS_FEATURE_USER_PROFILE_APP_PACKAGE_TAP_COUNT;
            case 23:
                return CONTINUOUS_FEATURE_USER_PROFILE_INTENT_TAP_COUNT;
            default:
                return null;
        }
    }

    /* renamed from: b */
    public static C62959cf m85234b() {
        return C48540t.f125389a;
    }

    public final int getNumber() {
        return this.f125415y;
    }

    public final String toString() {
        return Integer.toString(this.f125415y);
    }
}
