package com.google.android.apps.gsa.staticplugins.bisto.p7465ac.p7466a.p7467a;

/* renamed from: com.google.android.apps.gsa.staticplugins.bisto.ac.a.a.p */
/* compiled from: PG */
enum C94841p {
    GATT_CONNECTED,
    GATT_DISCONNECTED,
    GATT_REFRESHED,
    SERVICE_DISCOVERED,
    CRYPTO_UNSUBSCRIBED,
    AUDIO_UNSUBSCRIBED,
    CONTROL_UNSUBSCRIBED,
    PROXY_UNSUBSCRIBED,
    CRYPTO_SUBSCRIBED,
    AUDIO_SUBSCRIBED,
    CONTROL_SUBSCRIBED,
    PROXY_SUBSCRIBED,
    OOBE_COMPLETED,
    GATT_ERROR,
    ON_CONTROL_NOTIFICATION,
    ON_CRYPTO_NOTIFICATION,
    ON_AUDIO_NOTIFICATION,
    ON_PROXY_NOTIFICATION,
    ON_CHARACTERISTIC_WRITE,
    ON_MTU_CHANGED,
    FATAL_ERROR,
    NON_FATAL_ERROR,
    ERROR_NOT_SPECIFIED,
    SUBSCRIPTION_SKIPPED,
    UNSUBSCRIPTION_SKIPPED,
    CRYPTO_FATAL_ERROR,
    CRYPTO_SETUP_COMPLETED,
    CRYPTO_PING_TIMEOUT
}
