package com.google.android.apps.search.assistant.libraries.p8942a;

/* renamed from: com.google.android.apps.search.assistant.libraries.a.d */
/* compiled from: PG */
public enum C119207d {
    FAILED_CONTENT_CAPTURE_MANAGER_NOT_ENABLED,
    FAILED_OS_VERSION,
    FAILED_CONTENT_CAPTURE_MANAGER_IS_NULL,
    FAILED_IO_EXCEPTION_ON_WRITE,
    FAILED_UNKNOWN_EXCEPTION_ON_WRITE,
    FAILED_DATA_SHARE_ERROR_UNKNOWN,
    FAILED_DATA_SHARE_ERROR_CONCURRENT_REQUEST,
    FAILED_DATA_SHARE_ERROR_TIMEOUT_INTERRUPTED,
    FAILED_DATA_SHARE_REQUEST_REJECTED,
    SUCCESS
}
