package com.google.p4184bj.p4189b;

/* renamed from: com.google.bj.b.l */
/* compiled from: PG */
public final class C55895l {
    /* renamed from: a */
    public static int m87800a(int i) {
        if (i == 67) {
            return 68;
        }
        if (i == 68) {
            return 69;
        }
        if (i == 70) {
            return 71;
        }
        if (i == 71) {
            return 72;
        }
        switch (i) {
            case 0:
                return 1;
            case 1:
                return 2;
            case 2:
                return 3;
            case 3:
                return 4;
            case 4:
                return 5;
            case 5:
                return 6;
            case 6:
                return 7;
            case 7:
                return 8;
            case 8:
                return 9;
            case 9:
                return 10;
            case 10:
                return 11;
            case 11:
                return 12;
            case 12:
                return 13;
            case 13:
                return 14;
            case 14:
                return 15;
            case 15:
                return 16;
            case 16:
                return 17;
            case 17:
                return 18;
            case 18:
                return 19;
            case 19:
                return 20;
            case 20:
                return 21;
            case 21:
                return 22;
            case 22:
                return 23;
            case 23:
                return 24;
            case 24:
                return 25;
            case 25:
                return 26;
            case 26:
                return 27;
            case 27:
                return 28;
            case 28:
                return 29;
            case 29:
                return 30;
            case 30:
                return 31;
            case 31:
                return 32;
            case 32:
                return 33;
            default:
                switch (i) {
                    case 34:
                        return 35;
                    case 35:
                        return 36;
                    case 36:
                        return 37;
                    case 37:
                        return 38;
                    case 38:
                        return 39;
                    case 39:
                        return 40;
                    case 40:
                        return 41;
                    case 41:
                        return 42;
                    case 42:
                        return 43;
                    case 43:
                        return 44;
                    case 44:
                        return 45;
                    case 45:
                        return 46;
                    case 46:
                        return 47;
                    case 47:
                        return 48;
                    case 48:
                        return 49;
                    case 49:
                        return 50;
                    case 50:
                        return 51;
                    case 51:
                        return 52;
                    case 52:
                        return 53;
                    case 53:
                        return 54;
                    case 54:
                        return 55;
                    case 55:
                        return 56;
                    case 56:
                        return 57;
                    case 57:
                        return 58;
                    case 58:
                        return 59;
                    case 59:
                        return 60;
                    case 60:
                        return 61;
                    case 61:
                        return 62;
                    case 62:
                        return 63;
                    case 63:
                        return 64;
                    default:
                        switch (i) {
                            case 73:
                                return 74;
                            case 74:
                                return 75;
                            case 75:
                                return 76;
                            case 76:
                                return 77;
                            case 77:
                                return 78;
                            case 78:
                                return 79;
                            case 79:
                                return 80;
                            case 80:
                                return 81;
                            case 81:
                                return 82;
                            case 82:
                                return 83;
                            default:
                                switch (i) {
                                    case 84:
                                        return 85;
                                    case 85:
                                        return 86;
                                    case 86:
                                        return 87;
                                    case 87:
                                        return 88;
                                    case 88:
                                        return 89;
                                    case 89:
                                        return 90;
                                    case 90:
                                        return 91;
                                    case 91:
                                        return 92;
                                    case 92:
                                        return 93;
                                    case 93:
                                        return 94;
                                    case 94:
                                        return 95;
                                    case 95:
                                        return 96;
                                    case 96:
                                        return 97;
                                    case 97:
                                        return 98;
                                    case 98:
                                        return 99;
                                    case 99:
                                        return 100;
                                    case 100:
                                        return 101;
                                    case 101:
                                        return 102;
                                    case 102:
                                        return 103;
                                    case 103:
                                        return 104;
                                    case 104:
                                        return 105;
                                    case 105:
                                        return 106;
                                    case 106:
                                        return 107;
                                    case 107:
                                        return 108;
                                    case 108:
                                        return 109;
                                    case 109:
                                        return 110;
                                    case 110:
                                        return 111;
                                    case 111:
                                        return 112;
                                    case 112:
                                        return 113;
                                    case 113:
                                        return 114;
                                    case 114:
                                        return 115;
                                    case 115:
                                        return 116;
                                    case 116:
                                        return 117;
                                    case 117:
                                        return 118;
                                    case 118:
                                        return 119;
                                    case 119:
                                        return 120;
                                    case 120:
                                        return 121;
                                    case 121:
                                        return 122;
                                    case 122:
                                        return 123;
                                    case 123:
                                        return 124;
                                    case 10011:
                                        return 10012;
                                    case 10999:
                                        return 11000;
                                    case 11000:
                                        return 11001;
                                    case 11001:
                                        return 11002;
                                    case 11002:
                                        return 11003;
                                    case 11003:
                                        return 11004;
                                    case 11004:
                                        return 11005;
                                    case 11005:
                                        return 11006;
                                    case 11006:
                                        return 11007;
                                    case 11007:
                                        return 11008;
                                    case 11008:
                                        return 11009;
                                    case 11009:
                                        return 11010;
                                    case 11999:
                                        return 12000;
                                    case 12000:
                                        return 12001;
                                    case 12001:
                                        return 12002;
                                    case 12002:
                                        return 12003;
                                    case 12003:
                                        return 12004;
                                    case 12004:
                                        return 12005;
                                    case 12005:
                                        return 12006;
                                    case 12006:
                                        return 12007;
                                    case 12007:
                                        return 12008;
                                    case 12008:
                                        return 12009;
                                    case 12009:
                                        return 12010;
                                    case 99999:
                                        return 100000;
                                    case 100000:
                                        return 100001;
                                    default:
                                        switch (i) {
                                            case 125:
                                                return 126;
                                            case 126:
                                                return 127;
                                            case 127:
                                                return 128;
                                            case 128:
                                                return 129;
                                            case 129:
                                                return 130;
                                            case 130:
                                                return 131;
                                            case 131:
                                                return 132;
                                            case 132:
                                                return 133;
                                            case 133:
                                                return 134;
                                            case 134:
                                                return 135;
                                            case 135:
                                                return 136;
                                            case 136:
                                                return 137;
                                            case 137:
                                                return 138;
                                            case 138:
                                                return 139;
                                            case 139:
                                                return 140;
                                            case 140:
                                                return 141;
                                            default:
                                                switch (i) {
                                                    case 142:
                                                        return 143;
                                                    case 143:
                                                        return 144;
                                                    case 144:
                                                        return 145;
                                                    case 145:
                                                        return 146;
                                                    default:
                                                        switch (i) {
                                                            case 147:
                                                                return 148;
                                                            case 148:
                                                                return 149;
                                                            case 149:
                                                                return 150;
                                                            case 150:
                                                                return 151;
                                                            case 151:
                                                                return 152;
                                                            case 152:
                                                                return 153;
                                                            case 153:
                                                                return 154;
                                                            case 154:
                                                                return 155;
                                                            case 155:
                                                                return 156;
                                                            case 156:
                                                                return 157;
                                                            case 157:
                                                                return 158;
                                                            case 158:
                                                                return 159;
                                                            case 159:
                                                                return 160;
                                                            case 160:
                                                                return 161;
                                                            case 161:
                                                                return 162;
                                                            case 162:
                                                                return 163;
                                                            case 163:
                                                                return 164;
                                                            case 164:
                                                                return 165;
                                                            case 165:
                                                                return 166;
                                                            case 166:
                                                                return 167;
                                                            case 167:
                                                                return 168;
                                                            case 168:
                                                                return 169;
                                                            case 169:
                                                                return 170;
                                                            case 170:
                                                                return 171;
                                                            case 171:
                                                                return 172;
                                                            case 172:
                                                                return 173;
                                                            case 173:
                                                                return 174;
                                                            case 174:
                                                                return 175;
                                                            case 175:
                                                                return 176;
                                                            case 176:
                                                                return 177;
                                                            case 177:
                                                                return 178;
                                                            case 178:
                                                                return 179;
                                                            case 179:
                                                                return 180;
                                                            case 180:
                                                                return 181;
                                                            case 181:
                                                                return 182;
                                                            case 182:
                                                                return 183;
                                                            case 183:
                                                                return 184;
                                                            case 184:
                                                                return 185;
                                                            case 185:
                                                                return 186;
                                                            default:
                                                                switch (i) {
                                                                    case 10000:
                                                                        return 10001;
                                                                    case 10001:
                                                                        return 10002;
                                                                    case 10002:
                                                                        return 10003;
                                                                    case 10003:
                                                                        return 10004;
                                                                    case 10004:
                                                                        return 10005;
                                                                    case 10005:
                                                                        return 10006;
                                                                    case 10006:
                                                                        return 10007;
                                                                    case 10007:
                                                                        return 10008;
                                                                    case 10008:
                                                                        return 10009;
                                                                    case 10009:
                                                                        return 10010;
                                                                    default:
                                                                        return 0;
                                                                }
                                                        }
                                                }
                                        }
                                }
                        }
                }
        }
    }
}
