package com.google.p4283bv.p4345d.p4346a.p4347a;

import org.chromium.net.PrivateKeyType;

/* renamed from: com.google.bv.d.a.a.b */
/* compiled from: PG */
public final class C56952b {
    /* renamed from: a */
    public static /* synthetic */ String m88241a(int i) {
        if (i == 1) {
            return "REGULAR";
        }
        if (i == 15) {
            return "TOPDECK_MORNING_GREETING";
        }
        if (i == 98) {
            return "CODELAB_NOTIF";
        }
        switch (i) {
            case 17:
                return "WEATHER_DEFAULT_NOTIF";
            case 18:
                return "SPORTS_OTHER_NOTIF";
            case 19:
                return "SPORTS_VIDEO_HIGHLIGHTS_NOTIF";
            case 20:
                return "COMMUTE_GENERAL_NOTIF";
            case 21:
                return "TRANSIT_STATION_INFORMATION_NOTIF";
            case 22:
                return "AT_A_PLACE_LOCATION_NOTIF";
            case 23:
                return "PUBLIC_ALERT_NOTIF";
            case 24:
                return "FLIGHT_STATUS_TIME_TO_LEAVE_NOTIF";
            case 25:
                return "COMMUTE_TRAFFIC_INCIDENT_NOTIF";
            case 26:
                return "THIRD_PARTY_NOTIF";
            case 27:
                return "WEATHER_NEXT_DAY_DEGREE_DELTA_NOTIF";
            case 28:
                return "DEPRECATED_WEATHER_NEXT_DAY_SNOW_RAIN_NOTIF";
            case 29:
                return "FINANCE_EOD_CHANGE_DELTA_NOTIF";
            case 30:
                return "PACKAGE_TRACKING_NOTIF";
            case 31:
                return "FLIGHT_STATUS_DEFAULT_NOTIF";
            case 32:
                return "FLIGHT_STATUS_DELAYED_CANCELLED_NOTIF";
            case 33:
                return "FLIGHT_STATUS_GATE_OR_TERMINAL_NOTIF";
            default:
                switch (i) {
                    case 35:
                        return "HYPERLOCAL_LOCATION_NOTIF";
                    case 36:
                        return "SPORTS_GAME_BASEBALL_NOTIF";
                    case 37:
                        return "SPORTS_GAME_BASKETBALL_NOTIF";
                    case 38:
                        return "SPORTS_GAME_CRICKET_NOTIF";
                    case 39:
                        return "SPORTS_GAME_FOOTBALL_NOTIF";
                    case 40:
                        return "SPORTS_GAME_HOCKEY_NOTIF";
                    case 41:
                        return "SPORTS_GAME_RUGBY_NOTIF";
                    case 42:
                        return "SPORTS_GAME_SOCCER_NOTIF";
                    case 43:
                        return "SPORTS_GAME_TENNIS_NOTIF";
                    case 44:
                        return "FREQUENT_PLACE_COMMUTE_NOTIF";
                    case 45:
                        return "FREQUENT_PLACE_OTHER_NOTIF";
                    case 46:
                        return "TRAFFIC_INCIDENT_NOTIF";
                    case 47:
                        return "WEATHER_HOURLY_SNOW_RAIN_NOTIF";
                    case 48:
                        return "KE_NOW_ACTOR_TO_MOVIE_NOTIF";
                    case 49:
                        return "KE_NOW_DIRECTOR_TO_MOVIE_NOTIF";
                    case 50:
                        return "KE_NOW_MOVIE_NOTIF";
                    case 51:
                        return "KE_NOW_ARTIST_TO_ALBUM_NOTIF";
                    case 52:
                        return "KE_NOW_ATHLETE_TO_TEAM_NOTIF";
                    case 53:
                        return "KE_NOW_TEAM_TO_ATHLETE_NOTIF";
                    case 54:
                        return "KE_NOW_DEFAULT_NOTIF";
                    case 55:
                        return "BILL_PAY_NOTIF";
                    case 56:
                        return "FINANCE_INTRADAY_NOTIF";
                    case 57:
                        return "KE_NOW_STOCK_TO_TICKER_INTRADAY_NOTIF";
                    case 58:
                        return "KE_NOW_TEAM_TO_COACH_NOTIF";
                    case 59:
                        return "KE_NOW_MOVIE_TO_MOVIE_SEQUEL_NOTIF";
                    case 60:
                        return "KE_NOW_COACH_TO_TEAM_NOTIF";
                    case 61:
                        return "WEBKICK_EXPLICIT_INTEREST_NOTIF";
                    case 62:
                        return "CIVICS_DEFAULT_NOTIF";
                    case 63:
                        return "AIR_QUALITY_NOTIF";
                    case 64:
                        return "COMMUTE_NOTIF";
                    case 65:
                        return "FLIGHT_BOARDING_PASS_DAY_BEFORE_NOTIF";
                    case 66:
                        return "FLIGHT_BOARDING_PASS_IMMINENT_NOTIF";
                    case 67:
                        return "EVENT_TICKET_DAY_BEFORE_NOTIF";
                    case 68:
                        return "EVENT_TICKET_IMMINENT_NOTIF";
                    case 69:
                        return "FINANCE_INDEX_NOTIF";
                    case 70:
                        return "LAST_TRAIN_HOME_NOTIF";
                    case 71:
                        return "EVENT_CALENDAR_NOTIF";
                    case 72:
                        return "EVENT_CAR_RENTAL_NOTIF";
                    case 73:
                        return "EVENT_TICKET_CONCERT_NOTIF";
                    case 74:
                        return "EVENT_DEFAULT_NOTIF";
                    case 75:
                        return "EVENT_TICKET_MOVIE_NOTIF";
                    case 76:
                        return "EVENT_RESTAURANT_PLACE_NOTIF";
                    case 77:
                        return "FLIGHT_BOARDING_PASS_BARCODE_NOTIF";
                    case 78:
                        return "INTERNAL_API_DEFAULT_NOTIF";
                    case 79:
                        return "REMINDER_DEFAULT_NOTIF";
                    default:
                        switch (i) {
                            case 81:
                                return "KE_NOW_OLYMPICS_INTRO_NOTIF";
                            case 82:
                                return "KE_NOW_OLYMPICS_COUNTRY_MEDAL_WIN_NOTIF";
                            case 83:
                                return "KE_NOW_OLYMPICS_DAILY_FEATURED_EVENT_NOTIF";
                            case 84:
                                return "KE_NOW_OLYMPICS_DAILY_RECAP_NOTIF";
                            case 85:
                                return "KE_NOW_OLYMPICS_TOP_EVENT_HEADS_UP_NOTIF";
                            case 86:
                                return "KE_NOW_OLYMPICS_TOP_EVENT_SUMMARY_NOTIF";
                            case 87:
                                return "THIRD_PARTY_CARDMAKER_NOTIF";
                            case 88:
                                return "WEBSITE_UPDATE_NOTIF";
                            case 89:
                                return "PRICE_DROP_NOTIF";
                            case 90:
                                return "KE_NOW_OLYMPICS_MEDAL_EVENT_HEADS_UP_NOTIF";
                            case 91:
                                return "FLIGHT_PRICE_DROP_NOTIF";
                            default:
                                switch (i) {
                                    case 94:
                                        return "TRANSLATE_AWARENESS_NOTIF";
                                    case 95:
                                        return "TRANSPORTATION_TICKET_DAY_BEFORE_NOTIF";
                                    case 96:
                                        return "TRANSPORTATION_TICKET_IMMINENT_NOTIF";
                                    default:
                                        switch (i) {
                                            case 100:
                                                return "TIME_TO_LEAVE_NOTIF";
                                            case 101:
                                                return "EVENT_ANDROID_CALENDAR_NOTIF";
                                            case 102:
                                                return "FINANCE_INFERRED_NOTIF";
                                            case 103:
                                                return "INFERRED_REMINDER_DEFAULT_NOTIF";
                                            case 104:
                                                return "FLIGHT_PRICE_NDF_NOTIF";
                                            case 105:
                                                return "NBU_SPORT_AWARENESS_NOTIF";
                                            case 106:
                                                return "DOODLES_NOTIF";
                                            case 107:
                                                return "KE_NOW_TV_SERIES_TO_FIRST_EPISODE_NOTIF";
                                            case 108:
                                                return "SEARCH_AWARENESS_NOTIF";
                                            case 109:
                                                return "KE_NOW_AUTHOR_TO_BOOK_NOTIF";
                                            case 110:
                                                return "UGC_THEATER_VISIT_NOTIF";
                                            case 111:
                                                return "KE_NOW_AWARDS_CEREMONY_NOTIF";
                                            case 112:
                                                return "KE_NOW_FILM_FESTIVAL_NOTIF";
                                            case 113:
                                                return "KE_NOW_MUSIC_FESTIVAL_NOTIF";
                                            case 114:
                                                return "KE_NOW_TOUR_DE_FRANCE_NOTIF";
                                            case 115:
                                                return "FINANCE_IPO_DAY_OF_NOTIF";
                                            case 116:
                                                return "KE_NOW_HEALTH_POLLEN_COUNT_NOTIF";
                                            case 117:
                                                return "KE_NOW_EPHEMERAL_EVENT_NOTIF";
                                            case 118:
                                                return "TRAVEL_ASSISTANT_NOTIF";
                                            case 119:
                                                return "DEPRECATED_WHILE_YOU_WAIT_BOLLYWOOD_CARD_NOTIF";
                                            case 120:
                                                return "FEED_SUMMARY_NOTIF";
                                            case 121:
                                                return "MERCHANT_NOTIF";
                                            case 122:
                                                return "FEED_PROMO_MARKETING_NOTIF";
                                            case 123:
                                                return "VIDYA_ONBOARDING_NOTIF";
                                            case 124:
                                                return "KE_NOW_LOTTERY_NOTIF";
                                            case 125:
                                                return "EVENTS_REMINDER_NOTIF";
                                            case 126:
                                                return "KE_NOW_AIR_QUALITY_DAILY_NOTIF";
                                            case 127:
                                                return "KE_NOW_AIR_QUALITY_CRITICAL_NOTIF";
                                            case 128:
                                                return "KE_NOW_BOOK_TO_BOOK_NOTIF";
                                            case 129:
                                                return "PUBLIC_HEALTH_NOTIF";
                                            case 130:
                                                return "KE_NOW_SEARCH_ENGAGEMENT_ASKJOE";
                                            case 131:
                                                return "KE_NOW_SEARCH_ENGAGEMENT_HIGHLIGHT";
                                            default:
                                                switch (i) {
                                                    case 133:
                                                        return "ACCOUNT_NOTIFIER_NOTIF";
                                                    case 134:
                                                        return "CIVICS_ELECTION_RESULTS_NOTIF";
                                                    case 135:
                                                        return "CIVICS_VOTER_INFO_NOTIF";
                                                    case 136:
                                                        return "DUMMY_NOTIF";
                                                    case 137:
                                                        return "JANATA_HANDSHAKE_NOTIF";
                                                    case 138:
                                                        return "KE_NOW_EXAM_NOTIF";
                                                    case 139:
                                                        return "MERCHANT_HEALTH_CHECK_NOTIF";
                                                    case 140:
                                                        return "MERCHANT_LOCAL_POST_GOING_DARK_NOTIF";
                                                    case 141:
                                                        return "MERCHANT_LOCAL_POST_REMINDER_NOTIF";
                                                    case 142:
                                                        return "MERCHANT_OWNER_REVIEW_NOTIF";
                                                    case 143:
                                                        return "MERCHANT_PHOTO_NOTIF";
                                                    case 144:
                                                        return "MERCHANT_REVIEW_NOTIF";
                                                    case 145:
                                                        return "KE_NOW_UGC_PHOTO_NOTIF";
                                                    case 146:
                                                        return "CRISIS_RESPONSE_SOS_NOTIF";
                                                    case 147:
                                                        return "UGC_LOCALIZATION_NOTIF";
                                                    case 148:
                                                        return "UGC_PLACE_QA_NOTIF";
                                                    case 149:
                                                        return "MERCHANT_FIRST_POST_PROMPT_NOTIF";
                                                    case 150:
                                                        return "MERCHANT_LOCAL_POST_MILESTONE_NOTIF";
                                                    case 151:
                                                        return "KE_NOW_ACTOR_TO_MOVIE_TRAILER_NOTIF";
                                                    case 152:
                                                        return "KE_NOW_DIRECTOR_TO_MOVIE_TRAILER_NOTIF";
                                                    case 153:
                                                        return "KE_NOW_MOVIE_TO_MOVIE_TRAILER_NOTIF";
                                                    case 154:
                                                        return "KE_NOW_TV_SERIES_TO_NEW_EPISODE_NOTIF";
                                                    case 155:
                                                        return "KE_NOW_TICKET_AVAILABILITY_NOTIF";
                                                    case 156:
                                                        return "KE_NOW_WEEKEND_SHOWTIMES_NOTIF";
                                                    case 157:
                                                        return "MINDSEARCH_ANSWERS_NOTIF";
                                                    case 158:
                                                        return "KE_NOW_CELEB_TO_TV_GUEST_APPEARANCE_NOTIF";
                                                    default:
                                                        switch (i) {
                                                            case 160:
                                                                return "AGSA_UPDATE_PROMO_NOTIF";
                                                            case 161:
                                                                return "KE_NOW_MULTISPORT_EVENT_NOTIF";
                                                            case 162:
                                                                return "TOP_STORY_NOTIF";
                                                            case 163:
                                                                return "UGC_PHOTO_EVENT_NOTIF";
                                                            case 164:
                                                                return "AGSA_OPA_I18N_VERSION_GAP_NOTIF";
                                                            case 165:
                                                                return "WORD_COACH_NOTIF";
                                                            case 166:
                                                                return "SEARCH_FEATURES_NOTIF";
                                                            case 167:
                                                                return "KE_NOW_MUSIC_SONG_NOTIF";
                                                            case 168:
                                                                return "SPORTS_AWARENESS_NOTIF";
                                                            case 169:
                                                                return "FINANCE_AWARENESS_NOTIF";
                                                            case 170:
                                                                return "SHOPPING_SUBSCRIBED_PRICE_DROP_NOTIF";
                                                            case 171:
                                                                return "BREAKING_NEWS_NOTIF";
                                                            case 172:
                                                                return "BULLETIN_EVENTS_NOTIF";
                                                            case 173:
                                                                return "KE_NOW_VIDEO_GAME_NOTIF";
                                                            case 174:
                                                                return "EMPLOY_SAVED_SEARCH_NOTIF";
                                                            case 175:
                                                                return "MERCHANT_SITE_MANAGER_ENGAGEMENT_NOTIF";
                                                            case 176:
                                                                return "SPORTS_GAME_CRICKET_MILESTONE_NOTIF";
                                                            case 177:
                                                                return "TV_AWARENESS_NOTIF";
                                                            case 178:
                                                                return "JANATA_EDIT_CARD_FOLLOWUP_NOTIF";
                                                            case 179:
                                                                return "JANATA_POST_IMAGE_FOLLOWUP_NOTIF";
                                                            case 180:
                                                                return "WEATHER_NEXT_DAY_FORECAST_NOTIF";
                                                            case 181:
                                                                return "WEATHER_TODAY_FORECAST_NOTIF";
                                                            case 182:
                                                                return "EMPLOY_APPLY_SIMILAR_JOBS_NOTIF";
                                                            case 183:
                                                                return "SPORTS_GAME_AUSTRALIAN_FOOTBALL_NOTIF";
                                                            case 184:
                                                                return "TRAVEL_PLANNING_TRIP_CREATE_NOTIF";
                                                            case 185:
                                                                return "TRAVEL_PLANNING_TRIP_UPDATE_NOTIF";
                                                            case 186:
                                                                return "TRAVEL_PLANNING_POTENTIAL_TRIP_NOTIF";
                                                            case 187:
                                                                return "MINDSEARCH_QUESTIONS_NOTIF";
                                                            case 188:
                                                                return "EMPLOY_SAVED_JOBS_NOTIF";
                                                            case 189:
                                                                return "SEARCH_QUERY_RECOMMENDATION_NOTIF";
                                                            case 190:
                                                                return "MERCHANT_MONTHLY_PLACE_INSIGHTS_NOTIF";
                                                            case 191:
                                                                return "SUBSCRIPTION_RECOMMENDATION_NOTIF";
                                                            case 192:
                                                                return "FINANCE_DAILY_RECAP_NOTIF";
                                                            case 193:
                                                                return "KE_NOW_ONEOFF_NOTIF";
                                                            case 194:
                                                                return "MERCHANT_INFERRED_OUTREACH_NOTIF";
                                                            case 195:
                                                                return "TIME_GAP_QUERY_SUBSCRIPTION_NOTIF";
                                                            case 196:
                                                                return "FORESIGHT_QUERY_SUBSCRIPTION_NOTIF";
                                                            case 197:
                                                                return "MERCHANT_SIM_OUTREACH_NOTIF";
                                                            case 198:
                                                                return "KE_NOW_FAFSA_NOTIF";
                                                            case 199:
                                                                return "MERCHANT_MATCHED_OUTREACH_NOTIF";
                                                            case 200:
                                                                return "SPORTS_GAME_SOCCER_LINEUPS_NOTIF";
                                                            case 201:
                                                                return "W2W_WEEKLY_RECOMMENDATION_NOTIF";
                                                            case 202:
                                                                return "KE_NOW_ARTIST_TO_EP_NOTIF";
                                                            case 203:
                                                                return "KE_NOW_ARTIST_TO_SINGLE_NOTIF";
                                                            case 204:
                                                                return "JANATA_SOCIAL_PROFILES_FOLLOWUP_NOTIF";
                                                            case 205:
                                                                return "FOOD_ORDERING_PHONE_CALL_NOTIF";
                                                            case 206:
                                                                return "FOOD_ORDERING_GAM_GAM_NOTIF";
                                                            case 207:
                                                                return "FINANCE_CORPORATE_EARNINGS_RESULT_NOTIF";
                                                            case 208:
                                                                return "FINANCE_CORPORATE_EARNINGS_UCPOMING_EVENT_NOTIF";
                                                            case 209:
                                                                return "SPORTS_GAME_GOLF_NOTIF";
                                                            case 210:
                                                                return "TRAVEL_PLANNING_UPCOMING_TRIP_NOTIF";
                                                            case 211:
                                                                return "SPORTS_GAME_ESPORTS_NOTIF";
                                                            case 212:
                                                                return "SWELL_BREAKING_NEWS_NOTIF";
                                                            case 213:
                                                                return "FORESIGHT_WHENIS_SUBSCRIPTION_NOTIF";
                                                            case 214:
                                                                return "FORESIGHT_PORKY_PIG_SUBSCRIPTION_NOTIF";
                                                            case 215:
                                                                return "CRISIS_FLOOD_FORECASTING_NOTIF";
                                                            case 216:
                                                                return "MINDSEARCH_CONTRIBUTE_CONTENT_NOTIF";
                                                            case 217:
                                                                return "FOOD_ORDERING_CHAIN_NOTIF";
                                                            case 218:
                                                                return "CIVICS_CENSUS_NOTIF";
                                                            case 219:
                                                                return "EMPLOY_COVID_AWARENESS_NOTIF";
                                                            case 220:
                                                                return "IMAGES_QUERY_SUBSCRIPTION_NOTIF";
                                                            case 221:
                                                                return "INFERRED_ANSWER_UPDATES_NOTIF";
                                                            case 222:
                                                                return "SQUF_NOTIF";
                                                            case 223:
                                                                return "SHOPPING_SUBSCRIBED_ORGANIC_PRICE_DROP_NOTIF";
                                                            case 224:
                                                                return "FOOD_ORDERING_REORDER_NOTIF";
                                                            case 225:
                                                                return "GOG_IMPACT_STATS_NOTIF";
                                                            case 226:
                                                                return "FINANCE_ENTITY_EOD_PROMOTION_NOTIF";
                                                            case 227:
                                                                return "CHANNELS_SUBSCRIPTION_NOTIF";
                                                            case 228:
                                                                return "GOG_CONTENT_UPDATE_NOTIF";
                                                            case 229:
                                                                return "FULL_COVERAGE_NOTIF";
                                                            case 230:
                                                                return "FORESIGHT_ENTITY_SUBSCRIPTION_NOTIF";
                                                            case 231:
                                                                return "FORESIGHT_INFERRED_NOTIF";
                                                            case 232:
                                                                return "SHOPPING_SUBSCRIBED_QUERY_PRICE_DROP_NOTIF";
                                                            case 233:
                                                                return "LOTTERY_NOTIF";
                                                            case 234:
                                                                return "ARTICLE_CONTENT_NOTIF";
                                                            case 235:
                                                                return "MERCHANT_JANATA_NOTIF";
                                                            case 236:
                                                                return "SEARCH_CONSOLE_CLICK_MILESTONE_NOTIF";
                                                            case 237:
                                                                return "OSRP_STRUCTURED_ANSWER_UPDATES_NOTIF";
                                                            case 238:
                                                                return "W2W_PROMO_NOTIF";
                                                            case 239:
                                                                return "LOCAL_SEARCH_NOTIF";
                                                            case 240:
                                                                return "SEARCH_CONSOLE_CHANGE_TOP_QUERIES_NOTIF";
                                                            case 241:
                                                                return "WORD_OF_THE_DAY_NOTIF";
                                                            case 242:
                                                                return "MERCHANT_SIM_ANDROID_WELCOME_OUTREACH_NOTIF";
                                                            case 243:
                                                                return "LAST_YEAR_TODAY_NOTIF";
                                                            case 244:
                                                                return "WEB_ANSWER_UPDATES_SUBSCRIPTION_NOTIF";
                                                            case 245:
                                                                return "SNOGEIST_ENTITY_SUBSCRIPTION_NOTIF";
                                                            case 246:
                                                                return "WEATHER_TODAY_DEGREE_DELTA_NOTIF";
                                                            case 247:
                                                                return "SNOGEIST_IMPLICIT_NOTIF";
                                                            case 248:
                                                                return "IMAGES_ENTITY_SUBSCRIPTION_NOTIF";
                                                            case 249:
                                                                return "SPORTS_ATHLETE_STATS_NOTIF";
                                                            case 250:
                                                                return "SHOPPING_IMPLICIT_ORGANIC_PRICE_DROP_NOTIF";
                                                            case 251:
                                                                return "IMAGES_QUERY_IMPLICIT_NOTIF";
                                                            case 252:
                                                                return "SNOGEIST_NASH_TRENDS_NOTIF";
                                                            case 253:
                                                                return "MERCHANT_SIGNUP_CHURN_NOTIF";
                                                            case 254:
                                                                return "IMAGES_ENTITY_INFERRED_NOTIF";
                                                            case PrivateKeyType.INVALID /*255*/:
                                                                return "FLOODS_DATAHUB_NOTIF";
                                                            case 256:
                                                                return "TRENDING_VIDEO_ENTITY_SUBSCRIPTION_NOTIF";
                                                            case 257:
                                                                return "REMOVAL_NOTIF";
                                                            case 258:
                                                                return "IMPLICIT_NEXT_STEPS_NOTIF";
                                                            case 259:
                                                                return "RICH_CONTENT_NOTIF";
                                                            case 260:
                                                                return "SPORTS_LEAGUE_VIDEO_HIGHLIGHTS_NOTIF";
                                                            case 261:
                                                                return "SHORT_VIDEO_NOTIF";
                                                            case 262:
                                                                return "LANDSCAPE_VIDEO_NOTIF";
                                                            case 263:
                                                                return "W2X_BOOK_NOTIF";
                                                            case 264:
                                                                return "W2X_RECIPE_NOTIF";
                                                            case 265:
                                                                return "SHOPPING_SALES_NOTIF";
                                                            default:
                                                                switch (i) {
                                                                    case 10001:
                                                                        return "ASSISTANT_NOTIF";
                                                                    case 10002:
                                                                        return "GELLER_NOTIF";
                                                                    case 10003:
                                                                        return "IREACH_NOTIF";
                                                                    case 10004:
                                                                        return "GNEWS_BREAKING_NEWS_NOTIF";
                                                                    case 10005:
                                                                        return "GNEWS_TOP_NEWS_NOTIF";
                                                                    case 10006:
                                                                        return "GNEWS_PERSONALIZED_NOTIF";
                                                                    case 10007:
                                                                        return "GNEWS_DAILY_ARTICLE_NOTIF";
                                                                    default:
                                                                        return "null";
                                                                }
                                                        }
                                                }
                                        }
                                }
                        }
                }
        }
    }

    /* renamed from: b */
    public static int m88242b(int i) {
        if (i == 0) {
            return 1;
        }
        if (i == 14) {
            return 15;
        }
        if (i == 97) {
            return 98;
        }
        switch (i) {
            case 16:
                return 17;
            case 17:
                return 18;
            case 18:
                return 19;
            case 19:
                return 20;
            case 20:
                return 21;
            case 21:
                return 22;
            case 22:
                return 23;
            case 23:
                return 24;
            case 24:
                return 25;
            case 25:
                return 26;
            case 26:
                return 27;
            case 27:
                return 28;
            case 28:
                return 29;
            case 29:
                return 30;
            case 30:
                return 31;
            case 31:
                return 32;
            case 32:
                return 33;
            default:
                switch (i) {
                    case 34:
                        return 35;
                    case 35:
                        return 36;
                    case 36:
                        return 37;
                    case 37:
                        return 38;
                    case 38:
                        return 39;
                    case 39:
                        return 40;
                    case 40:
                        return 41;
                    case 41:
                        return 42;
                    case 42:
                        return 43;
                    case 43:
                        return 44;
                    case 44:
                        return 45;
                    case 45:
                        return 46;
                    case 46:
                        return 47;
                    case 47:
                        return 48;
                    case 48:
                        return 49;
                    case 49:
                        return 50;
                    case 50:
                        return 51;
                    case 51:
                        return 52;
                    case 52:
                        return 53;
                    case 53:
                        return 54;
                    case 54:
                        return 55;
                    case 55:
                        return 56;
                    case 56:
                        return 57;
                    case 57:
                        return 58;
                    case 58:
                        return 59;
                    case 59:
                        return 60;
                    case 60:
                        return 61;
                    case 61:
                        return 62;
                    case 62:
                        return 63;
                    case 63:
                        return 64;
                    case 64:
                        return 65;
                    case 65:
                        return 66;
                    case 66:
                        return 67;
                    case 67:
                        return 68;
                    case 68:
                        return 69;
                    case 69:
                        return 70;
                    case 70:
                        return 71;
                    case 71:
                        return 72;
                    case 72:
                        return 73;
                    case 73:
                        return 74;
                    case 74:
                        return 75;
                    case 75:
                        return 76;
                    case 76:
                        return 77;
                    case 77:
                        return 78;
                    case 78:
                        return 79;
                    default:
                        switch (i) {
                            case 80:
                                return 81;
                            case 81:
                                return 82;
                            case 82:
                                return 83;
                            case 83:
                                return 84;
                            case 84:
                                return 85;
                            case 85:
                                return 86;
                            case 86:
                                return 87;
                            case 87:
                                return 88;
                            case 88:
                                return 89;
                            case 89:
                                return 90;
                            case 90:
                                return 91;
                            default:
                                switch (i) {
                                    case 93:
                                        return 94;
                                    case 94:
                                        return 95;
                                    case 95:
                                        return 96;
                                    default:
                                        switch (i) {
                                            case 99:
                                                return 100;
                                            case 100:
                                                return 101;
                                            case 101:
                                                return 102;
                                            case 102:
                                                return 103;
                                            case 103:
                                                return 104;
                                            case 104:
                                                return 105;
                                            case 105:
                                                return 106;
                                            case 106:
                                                return 107;
                                            case 107:
                                                return 108;
                                            case 108:
                                                return 109;
                                            case 109:
                                                return 110;
                                            case 110:
                                                return 111;
                                            case 111:
                                                return 112;
                                            case 112:
                                                return 113;
                                            case 113:
                                                return 114;
                                            case 114:
                                                return 115;
                                            case 115:
                                                return 116;
                                            case 116:
                                                return 117;
                                            case 117:
                                                return 118;
                                            case 118:
                                                return 119;
                                            case 119:
                                                return 120;
                                            case 120:
                                                return 121;
                                            case 121:
                                                return 122;
                                            case 122:
                                                return 123;
                                            case 123:
                                                return 124;
                                            case 124:
                                                return 125;
                                            case 125:
                                                return 126;
                                            case 126:
                                                return 127;
                                            case 127:
                                                return 128;
                                            case 128:
                                                return 129;
                                            case 129:
                                                return 130;
                                            case 130:
                                                return 131;
                                            default:
                                                switch (i) {
                                                    case 132:
                                                        return 133;
                                                    case 133:
                                                        return 134;
                                                    case 134:
                                                        return 135;
                                                    case 135:
                                                        return 136;
                                                    case 136:
                                                        return 137;
                                                    case 137:
                                                        return 138;
                                                    case 138:
                                                        return 139;
                                                    case 139:
                                                        return 140;
                                                    case 140:
                                                        return 141;
                                                    case 141:
                                                        return 142;
                                                    case 142:
                                                        return 143;
                                                    case 143:
                                                        return 144;
                                                    case 144:
                                                        return 145;
                                                    case 145:
                                                        return 146;
                                                    case 146:
                                                        return 147;
                                                    case 147:
                                                        return 148;
                                                    case 148:
                                                        return 149;
                                                    case 149:
                                                        return 150;
                                                    case 150:
                                                        return 151;
                                                    case 151:
                                                        return 152;
                                                    case 152:
                                                        return 153;
                                                    case 153:
                                                        return 154;
                                                    case 154:
                                                        return 155;
                                                    case 155:
                                                        return 156;
                                                    case 156:
                                                        return 157;
                                                    case 157:
                                                        return 158;
                                                    default:
                                                        switch (i) {
                                                            case 159:
                                                                return 160;
                                                            case 160:
                                                                return 161;
                                                            case 161:
                                                                return 162;
                                                            case 162:
                                                                return 163;
                                                            case 163:
                                                                return 164;
                                                            case 164:
                                                                return 165;
                                                            case 165:
                                                                return 166;
                                                            case 166:
                                                                return 167;
                                                            case 167:
                                                                return 168;
                                                            case 168:
                                                                return 169;
                                                            case 169:
                                                                return 170;
                                                            case 170:
                                                                return 171;
                                                            case 171:
                                                                return 172;
                                                            case 172:
                                                                return 173;
                                                            case 173:
                                                                return 174;
                                                            case 174:
                                                                return 175;
                                                            case 175:
                                                                return 176;
                                                            case 176:
                                                                return 177;
                                                            case 177:
                                                                return 178;
                                                            case 178:
                                                                return 179;
                                                            case 179:
                                                                return 180;
                                                            case 180:
                                                                return 181;
                                                            case 181:
                                                                return 182;
                                                            case 182:
                                                                return 183;
                                                            case 183:
                                                                return 184;
                                                            case 184:
                                                                return 185;
                                                            case 185:
                                                                return 186;
                                                            case 186:
                                                                return 187;
                                                            case 187:
                                                                return 188;
                                                            case 188:
                                                                return 189;
                                                            case 189:
                                                                return 190;
                                                            case 190:
                                                                return 191;
                                                            case 191:
                                                                return 192;
                                                            case 192:
                                                                return 193;
                                                            case 193:
                                                                return 194;
                                                            case 194:
                                                                return 195;
                                                            case 195:
                                                                return 196;
                                                            case 196:
                                                                return 197;
                                                            case 197:
                                                                return 198;
                                                            case 198:
                                                                return 199;
                                                            case 199:
                                                                return 200;
                                                            case 200:
                                                                return 201;
                                                            case 201:
                                                                return 202;
                                                            case 202:
                                                                return 203;
                                                            case 203:
                                                                return 204;
                                                            case 204:
                                                                return 205;
                                                            case 205:
                                                                return 206;
                                                            case 206:
                                                                return 207;
                                                            case 207:
                                                                return 208;
                                                            case 208:
                                                                return 209;
                                                            case 209:
                                                                return 210;
                                                            case 210:
                                                                return 211;
                                                            case 211:
                                                                return 212;
                                                            case 212:
                                                                return 213;
                                                            case 213:
                                                                return 214;
                                                            case 214:
                                                                return 215;
                                                            case 215:
                                                                return 216;
                                                            case 216:
                                                                return 217;
                                                            case 217:
                                                                return 218;
                                                            case 218:
                                                                return 219;
                                                            case 219:
                                                                return 220;
                                                            case 220:
                                                                return 221;
                                                            case 221:
                                                                return 222;
                                                            case 222:
                                                                return 223;
                                                            case 223:
                                                                return 224;
                                                            case 224:
                                                                return 225;
                                                            case 225:
                                                                return 226;
                                                            case 226:
                                                                return 227;
                                                            case 227:
                                                                return 228;
                                                            case 228:
                                                                return 229;
                                                            case 229:
                                                                return 230;
                                                            case 230:
                                                                return 231;
                                                            case 231:
                                                                return 232;
                                                            case 232:
                                                                return 233;
                                                            case 233:
                                                                return 234;
                                                            case 234:
                                                                return 235;
                                                            case 235:
                                                                return 236;
                                                            case 236:
                                                                return 237;
                                                            case 237:
                                                                return 238;
                                                            case 238:
                                                                return 239;
                                                            case 239:
                                                                return 240;
                                                            case 240:
                                                                return 241;
                                                            case 241:
                                                                return 242;
                                                            case 242:
                                                                return 243;
                                                            case 243:
                                                                return 244;
                                                            case 244:
                                                                return 245;
                                                            case 245:
                                                                return 246;
                                                            case 246:
                                                                return 247;
                                                            case 247:
                                                                return 248;
                                                            case 248:
                                                                return 249;
                                                            case 249:
                                                                return 250;
                                                            case 250:
                                                                return 251;
                                                            case 251:
                                                                return 252;
                                                            case 252:
                                                                return 253;
                                                            case 253:
                                                                return 254;
                                                            case 254:
                                                                return PrivateKeyType.INVALID;
                                                            case PrivateKeyType.INVALID /*255*/:
                                                                return 256;
                                                            case 256:
                                                                return 257;
                                                            case 257:
                                                                return 258;
                                                            case 258:
                                                                return 259;
                                                            case 259:
                                                                return 260;
                                                            case 260:
                                                                return 261;
                                                            case 261:
                                                                return 262;
                                                            case 262:
                                                                return 263;
                                                            case 263:
                                                                return 264;
                                                            case 264:
                                                                return 265;
                                                            default:
                                                                switch (i) {
                                                                    case 10000:
                                                                        return 10001;
                                                                    case 10001:
                                                                        return 10002;
                                                                    case 10002:
                                                                        return 10003;
                                                                    case 10003:
                                                                        return 10004;
                                                                    case 10004:
                                                                        return 10005;
                                                                    case 10005:
                                                                        return 10006;
                                                                    case 10006:
                                                                        return 10007;
                                                                    default:
                                                                        return 0;
                                                                }
                                                        }
                                                }
                                        }
                                }
                        }
                }
        }
    }
}
