package com.google.android.libraries.assistant.auto.tng.p1118r.p1141c.p1153c;

import com.google.common.p4522b.C58528ij;

/* renamed from: com.google.android.libraries.assistant.auto.tng.r.c.c.e */
/* compiled from: PG */
public final class C15673e {

    /* renamed from: a */
    public static final C58528ij f46796a = C58528ij.m90015O("car_automation.action.AC_OFF", "car_automation.action.AC_ON", "car_automation.action.AUTO_CLIMATE_OFF", "car_automation.action.AUTO_CLIMATE_ON", "car_automation.action.CABIN_HEAT_OFF", "car_automation.action.CABIN_HEAT_ON", "car_automation.action.DEFROSTER_OFF", "car_automation.action.DEFROSTER_ON", "car_automation.action.FAN_DECREASE", "car_automation.action.FAN_DIRECTION_OFF", "car_automation.action.FAN_DIRECTION_SET", "car_automation.action.FAN_INCREASE", "car_automation.action.FAN_OFF", "car_automation.action.FAN_ON", "car_automation.action.MAX_AC_OFF", "car_automation.action.MAX_AC_ON", "car_automation.action.MAX_DEFROSTER_OFF", "car_automation.action.MAX_DEFROSTER_ON", "car_automation.action.RECIRCULATE_AIR_OFF", "car_automation.action.RECIRCULATE_AIR_ON", "car_automation.action.SEAT_COOLING_OFF", "car_automation.action.SEAT_COOLING_ON", "car_automation.action.SEAT_HEAT_OFF", "car_automation.action.SEAT_HEAT_ON", "car_automation.action.SEAT_TEMPERATURE_DECREASE", "car_automation.action.SEAT_TEMPERATURE_INCREASE", "car_automation.action.SEAT_VENTILATION_DECREASE", "car_automation.action.SEAT_VENTILATION_INCREASE", "car_automation.action.SEAT_VENTILATION_OFF", "car_automation.action.SEAT_VENTILATION_ON", "car_automation.action.STEERING_HEAT_DECREASE", "car_automation.action.STEERING_HEAT_INCREASE", "car_automation.action.STEERING_HEAT_OFF", "car_automation.action.STEERING_HEAT_ON", "car_automation.action.SUNROOF_CLOSE", "car_automation.action.SUNROOF_OPEN", "car_automation.action.TEMPERATURE_DECREASE", "car_automation.action.TEMPERATURE_INCREASE", "car_automation.action.TEMPERATURE_SET", "car_automation.action.TEMPERATURE_SYNC_OFF", "car_automation.action.TEMPERATURE_SYNC_ON", "car_automation.action.WINDOW_CLOSE", "car_automation.action.WINDOW_LOCK", "car_automation.action.WINDOW_OPEN", "car_automation.action.WINDOW_UNLOCK", "car_automation.answer.CHARGE_PORT_LOCATION", "car_automation.answer.EV_BATTERY_LEVEL", "car_automation.answer.EV_CHARGING_TIME", "car_automation.answer.FUEL_RANGE_REMAINING", "car_automation.answer.FUEL_TO_DESTINATION", "car_automation.answer.GAS_DOOR_LOCATION", "car_automation.answer.GAS_LEVEL", "car_automation.answer.HVAC_TEMPERATURE_GET", "car_automation.answer.TIRE_PRESSURE", "car_automation.answer.WINDOW_LOCKUNLOCK_STATUS", "car_automation.answer.WINDOW_OPENCLOSE_STATUS");
}
