package com.google.android.apps.search.assistant.libraries.p8972f.p8973a;

/* renamed from: com.google.android.apps.search.assistant.libraries.f.a.p */
/* compiled from: PG */
enum C119379p {
    OPA_USER_ENABLED_STATUS,
    OPA_UDC_CONSENT_STATUS,
    SCREEN_CONTEXT_OPT_IN_STATUS,
    OPA_EMAIL_OPT_IN_STATUS,
    SPEAKER_MODEL_STATUS,
    THIRD_PARTY_DISCLOSURE_STATUS,
    ASSISTANT_ON_LOCKSCREEN_STATUS,
    SKIP_VOICE_RECOGNITION_STATUS,
    HEADPHONE_PERSONAL_RESULTS_STATUS,
    WARM_ACTIONS_ENROLLMENT_STATUS,
    WARM_ACTIONS_ALARMS_TIMERS_ENROLLMENT_STATUS,
    WARM_ACTIONS_CALLS_ENROLLMENT_STATUS
}
